doc/source/setup.rst
There have been bugs in the interactive google console which made these instructions not work...we couldn't figure them out and think it's probably better to just have people use the user SDK anyway since it's less clunky. (this also fixes some random syntax / display issues I noticed)
=> removing google console refs and cleaning up instructions

doc/source/extending-jupyterhub.rst, doc/source/setup-jupyterhub.rst
Only doc change is that there's now a default 1G memory guarantee
per user
=> Upgrade helm chart to v0.2

doc/source/setup-jupyterhub.rst
Corrected URL to new address (now jupyterhub-v0.3.x was jupyterhub-0.3.x) and also updated to latest v0.3.1
=> Corrected url to jupyterhub helm-chart

doc/source/additional-resources.rst, doc/source/backups.rst, doc/source/cost.rst, doc/source/create-k8s-cluster.rst, doc/source/extending-jupyterhub.rst, doc/source/index.rst, doc/source/resource-mgmt.rst, doc/source/security-considerations.rst, doc/source/upgrading.rst
=> Update to new table of contents structure

doc/environment.yml
RTD is currently depending on mkdocs for its default conda build environment. Although we don't use mkdocs, RTD is trying to load mkdocs from the default conda channel and failing https://github.com/rtfd/readthedocs.org/issues/2975. This PR adds mkdocs to our `environment.yml` that uses conda-forge as its channel. This workaround allowed the docs to build until a more suitable fix is added to RTD.
=> Update conda environment for RTD

doc/source/setup-helm.rst
=> Add note about verifying that helm has installed

doc/source/glossary.rst
This PR adds a glossary directive and reformats the `glossary.rst` file. With these changes, glossary terms throughout the guide can be linked to the glossary with the following syntax:
```
:term:`word`
```
=> Add directive and fix formatting for glossary

doc/source/extending-jupyterhub.rst
Closes #119 
- Clarify that size is the number of nodes
- Improve formatting of the command for cluster status
- Mention it may take a minute or two for the new cluster size to propagate
=> Clarify 'size' when resizing cluster

doc/source/setup-jupyterhub.rst
add missing backslash for line continuation
=> fix syntax error on helm install

doc/source/setup-jupyterhub.rst
if you're pulling from a large docker image you might get a ``Error: timed out waiting for the condition``, adding the ``--timeout`` parameters fixes this.
=> add timeout to helm install

doc/source/user-experience.rst
=> To be used as the basis for deployment, docker images must have jupyterhub

.gitignore, doc/environment.yml, doc/source/_static/custom.css, doc/source/conf.py, doc/source/schema.rst
This adds some python to the end of `conf.py` that generates rST headers based off of the JSON schema. It gives us more control over the information that we expose on the `schema.rst` page, and lets us style it however we like.
e.g. of how it looks now:
http://predictablynoisy.com/zero-to-jupyterhub-k8s/schema.html
thoughts?
=> nicer schema page

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/secret.yaml, jupyterhub/values.yaml
the main part of #165
hub.services is stored in configmap. Token is loaded as SERVICE_TOKEN_[NAME] via hub-secret
For example:
```yaml
hub.services:
binder:
admin: true
apiToken: 'generated-secret'
```
=> [0.5.x] support loading service tokens

Makefile, build.py, images/hub/Dockerfile, images/singleuser-sample/Dockerfile
Use smallest base-notebook with placeholder for installation of packages.
JUPYTERHUB_VERSION is a build arg and specified in the Makefile
includes #190 to avoid adding unused build arg to binderhub image
=> [0.5.x] base singleuser-sample on docker-stacks

minikube-config.yaml
so it can be used unmodified for testing with a predictable URL
=> define proxy.secretToken and NodePort in minikube-config

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/rbac.yaml
This is more secure than granting permissions to the default sa
=> Create a service account specifically for hub

doc/source/create-k8s-cluster.rst
This keeps changing all the time, plus we don't care now that
the default version is 1.7+
=> Remove explicit mention of kubernetes version from gke

binder/environment.yml
we may remove the cost estimator button soon, but in the meantime this just ensures that it will continue to build now that bqplot has been updated.
=> moving environment.yml to binder folder and freezing bqplot version

doc/source/create-k8s-cluster.rst
This now recursively enables the Compute Engine API & the
container registry API
=> Only activate the Google Container Engine API

.gitignore, doc/source/conf.py, doc/source/extending-jupyterhub.rst, doc/source/index.rst, doc/source/reference.txt, doc/source/schema.txt, doc/source/user-experience.rst
The schema is an implementation detail, what this is doing is
producing reference docs
=> Call reference documentation reference & not as schema

jupyterhub/templates/hub/configmap.yaml
When I tried to specify multiple entries in extraEnv, the hub pod would get stuck in a crash loop.  The logs indicated a problem parsing `/etc/jupyterhub/config/hub.extra-config.py`.  As best I could guess from the error message, it was getting everything on a single line.
This change in the templating seems to solve the problem.
=> Allow mutliple extraEnv entries

doc/source/create-k8s-cluster.rst
This is needed if you don't want the helm init sequence to fail.
Note that with Kubernetes 1.8 GKE mandates RBAC, so we can't go
back to the simpler times of everything being root.
=> Add note about making yourself superuser on GKE

doc/source/extending-jupyterhub.rst, images/hub/Dockerfile, images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml
Added support for CILogon auth in the configuration yaml.
There is an issue which is unrelated to k8s with CILogon and Jupyterhub 0.8, see https://github.com/jupyterhub/oauthenticator/issues/132.
I implemented a quick workaround in Jupyterhub (https://github.com/jupyterhub/jupyterhub/pull/1474) and tested that CILogon is working properly in my setup.
A proper fix should be ready soon see https://github.com/jupyterhub/oauthenticator/issues/133, I can then update this PR.
=> Support for CILogon auth

doc/source/extending-jupyterhub.rst, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/ingress-internal.yaml, jupyterhub/templates/proxy/secret.yaml, jupyterhub/values.yaml
usage:
```yaml
proxy:
https:
type: files
files:
cert: |
<paste cert>
key: |
<paste key>
```
closes #244
=> Support HTTPS via user-provided key/cert

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
it was used by `KubeSpawner` but not available in `helm`. I tested it with a `rook-block` storage class and worked fine.
=> pass storage class parameter through

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
This is where they logically belong, rather than under hub or as a top level entry.
=> Move whitelist & admin options under 'auth'

jupyterhub/values.yaml
Currently running master directly will fail, since the image
being specified is too old. This fixes it a little by updating
to more recent image. This isn't a long term solution, since
we need to keep bumping it manually every time we change the image.
But it helps people out right now who wanna run master...
Fixes #252
=> Provide defaults for master that at least sort of work

jupyterhub/templates/ingress.yaml
If `hub.baseUrl` is set this is probably because a user wants to host multiple web services under a domain. The Ingress controller should therefore use this as the path instead of `/`.
=> Use hub.baseUrl for ingress path

doc/source/setup-jupyterhub.rst, jupyterhub/templates/hub/secret.yaml, jupyterhub/values.yaml
- No need to ask users to generate 2 random strings
- Not specifying proxy.secretToken will actually produce an informative error message
=> Simplify secretToken + cookieSecret specification

build.py
To differentiate it from the binderhub chart pushes
=> Put [jupyterhub] in commit messages when pushing built charts

jupyterhub/templates/hub/deployment.yaml, jupyterhub/values.yaml
This is for people *not* on SQLite. This allows them to do an upgrade
by doing a deploy with this setting set to true, rather than having
to hunt down which version of JupyterHub we're running in the helm
chart and use that to upgrade.
=> Allow explicitly setting 'hub.db.upgrade' to force upgrades

jupyterhub/templates/hub/configmap.yaml
`admin.users` in the hub config map doesn't match `auth.admin.users` in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/3ebd38bf6b3b564ecead63b30606499f4cb41fc1/images/hub/jupyterhub_config.py#L220
=> configmap admin.users should be prefixed by auth.

jupyterhub/templates/hub/configmap.yaml
The current configmap leads to an incorrect service yaml. For example, this config:
```
hub:
baseUrl: /test1/
cookieSecret: XXXXXXXX
db:
type: sqlite-memory
extraConfig: |
c.JupyterHub.log_level = 'DEBUG'
c.Spawner.debug = True
services:
showenv:
admin: true
command: '["sh", "-c", "env | grep JUPYTER; exit 1"]'
cull-idle-localhost:
admin: true
command: '["/usr/local/bin/cull_idle_servers.py", "--timeout=3600", "--cull-every=600", "--url=http://127.0.0.1:8081/test1/hub/api"]'
cull:
enabled: false
```
leads to this `hub.service` key:`kubectl get cm hub-config -o yaml`
```
hub.services: |
cull-idle-localhost:
admin: truecommand: ["/usr/local/bin/cull_idle_servers.py", "--timeout=3600", "--cull-every=600", "--url=http://127.0.0.1:8081/test1/hub/api"]showenv:
admin: truecommand: ["sh", "-c", …
```
=> Ensure newlines are present in services config

images/hub/Dockerfile
get the latest patch that should fix orphaned containers on spawn timeout
https://github.com/jupyterhub/kubespawner/pull/98
=> bump kubespawner

jupyterhub/templates/hub/configmap.yaml
> Error: release jupyter-hub failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap: Data: ReadString: expects " or n
=> Fix node selector bad syntax in ConfigMap

doc/source/turn-off.rst
The current setup, where we have:
```
<h3> "For all clouds"
<instructions>
<h4> <specific-cloud-instructions>
```
Seem strange to me, since it's putting "GKE" or "AWS" 'under'
"For all clouds". It also makes the ToC a bit strange.
Not sure if this is the right thing to do!
=> Change heading levels in 'turn-it-off'

images/hub/Dockerfile
Gets in https://github.com/jupyterhub/kubespawner/pull/103. The chart is broken
without it.
=> Bump kubespawner version

images/hub/Dockerfile, images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml
The following changes add Globus as an identity provider, with very similar configuration to the other OAuthenticators: 
auth:
type: globus
globus:
clientId: "my-client-id"
clientSecret: "my-client-secret"
callbackUrl: "https://my-domain/hub/oauth_callback"
Tested with the latest merged changes to the kubespawner: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/292
See also: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/227
=> Added Globus Integration

jupyterhub/values.yaml
Newer kubernetes cluster setups almost always come with RBAC
enforced, so let's work by default on them.
=> Change RBAC to true

jupyterhub/templates/hub/deployment.yaml, jupyterhub/values.yaml
This allows for easier customization of the hub pod. Primarily
useful when you need a sidecar db proxy, such as when using
Google Cloud's managed SQL options (https://cloud.google.com/sql/docs/postgres/sql-proxy)
=> Allow setting extra sidecar containers to the hub

jupyterhub/templates/proxy/service.yaml, jupyterhub/values.yaml, minikube-config.yaml
use a dict now that there are two ports (http, https)
useful with minikube, required for binderhub testing
=> restore ability to specify nodePort on proxy service

minikube-config.yaml
since it's usually not available and now on by default
=> disable rbac on minikube

images/hub/jupyterhub_config.py
No idea why we need to do this explicitly just now when it has
been working just fine till now?!
=> Do not shut down user pods when hub is restarted

doc/source/advanced.md, doc/source/index.rst, jupyterhub/templates/ingress.yaml
Making a new 'advanced' section in the docs for things like this
that need to be documented, but most folks running on public clouds
would not need.
=> Add docs on how to use new ingress setup

jupyterhub/templates/hub/service.yaml
I just ran into this whilst working on travis/minikube tests (#289)
Related to the change in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/319
=> Fix hub service pod selector

.travis.yml, build.py, chartpress.yaml
I'm calling it 'chartpress', like a printing press but for charts.
- Factor out repo specific info into a separate chartpress.yaml file,
so we can move build.py to a separate repo eventually
- Fixup travis to use new commandline params
=> Generalize build.py to be not z2jh specific

.travis.yml
git is run from a few different working directories, so abspath should be more portable
This should fix the build after #325
=> use absolute path to travis ssh key

doc/source/user-experience.rst
Trivial change in doc to address https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/251
=> Solves #251: add a note to the doc on 63 chars limit

doc/source/setup-helm.rst
Tiller is open to connections inside the cluster and someone could try to exploit that. This problem is documented at https://engineering.bitnami.com/articles/helm-security.html.
Until there is an easier fix, I think we need to tell people to essentially `type this` to secure their clusters.
=> Add commands to secure tiller.

images/hub/jupyterhub_config.py
In some clusters, 'hairpin mode' does not quite work - you can't
talk to a pod via its service IP from itself. We don't need it,
since we can just use 127.0.0.1. So we do that!
Also remove a debug print that's been in here forever
Better fix for #280
=> [REVIEW BUT NOT MERGE YET] Fix idle culler not working in some clusters

CONTRIBUTING.md, build.py
Includes fixes needed for it to work with binderhub (https://github.com/jupyterhub/binderhub/pull/343).
None of the changes should affect this repo, other than the removed need for messing with dates.
=> resync build.py from binderhub

doc/source/security.rst
=> Show rbac code block

doc/source/create-k8s-cluster.rst
Previous version is no longer available. This info is gleamed
from https://cloud.google.com/kubernetes-engine/release-notes
=> Update required master version for GKE

doc/source/security.md
This fixes a rendering error on http://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#set-up-manual-https
=> Fix styling of yaml code block in HTTPS section

jupyterhub/Chart.yaml
This starts producing builds in jupyterhub.github.io/helm-chart
that will start as v0.6.0-<hash> rather than the incorrect
v0.5.0-<hash>
=> Bump version to v0.6.0

build.py
So the issue is that `sequence=4` is required to give valid yaml when for you have for example the following within your `values.yaml`. It becomes corrupt [when the `dump` method is invoked](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/373/commits/9701a909ad2ff3a01962116ac95083bc1d9879da#diff-2955d5257f635de1df53f55a171ca5c7R103).
```yaml
extraVolumeMounts:
- name: volume-nbgrader
mountPath: /home/jovyan/exchange
```
if not, it becomes this corrupt yaml using `sequence=2` as default indentation for some reason [discussed here](https://stackoverflow.com/questions/44388701/how-get-the-sequences-properly-indented-with-ruamel-yaml).
```yaml
extraVolumeMounts:
- name: volume-nbgrader
mountPath: /home/jovyan/exchange
```
NOTE: `typ=rt`, `mapping=2`, and `offset=2` are default …
=> Fix #372 - build.py corrupts yaml

doc/source/create-k8s-cluster.rst
The instructions give the option of obtaining some values with jq or looking them up manually. Not sure whether to change this to just look them up manually or just install jq and type these commands.
The service principal creation was necessary for me because of how and when my institution setup AD integration with Azure. I suspect that many others won't need to do this. I can't confirm since I don't have Azure credits on non-work accounts.
=> Update Azure documentation to use AKS.

doc/source/advanced.md, images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
This will try to pack user pods in as few nodes as possible, rather
than the default (which tries to spread them out). This is very
useful when autoscaling!
=> Allow setting schedulerStrategy to 'pack'

images/hub/jupyterhub_config.py
Currently culler doesn't know about baseUrl and keeps getting 404s,
thus making it not work when base_url is specified.
=> Take base_url into account when starting culler

images/hub/Dockerfile, images/hub/requirements.txt
makes it easier for bots and such to track out-of-date dependencies. This will let us inspect the requirements of our image with tools like requires.io or libraries.io. Still investigating what the best options are. It looks like libraries.io monitors dependencies, but can only do email notification. Requires.io appears to be able to attempt automatic pull requests like greenkeeper.
=> move image requirements to requirements.txt

doc/source/authentication.rst
On readthedocs, the raw block does not seem to be rendered
=> Change a raw block to a code block

doc/source/advanced.md, images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml
Using an alphabetically ordered dict also allows meta-charts to
*insert* config between specific upstream configs.
Fixes #320
=> Support extraConfig being a dict

jupyterhub/templates/hub/pdb.yaml, jupyterhub/templates/proxy/pdb.yaml, jupyterhub/values.yaml
This provides a hint to autoscalers that nodes with these
services running should be considered last for scaling down. This
helps keep them from being disrupted unless needed.
Fixes #390
=> Setup a pdb for hub and proxy

images/hub/Dockerfile
- Bumps Python Version to 3.6
- Removes npm / nodejs, which are not required when building
JupyterHub from pypi
=> Bump base image of hub to 17.10

doc/source/advanced.md, doc/source/conf.py, doc/source/index.rst, doc/source/user-resources.rst, doc/source/user-storage.md
This PR updates the documentation for user storage, it does a few main things:
* Incorporate the new storage documentation that we worked on in the hackmd
* Split off the current storage documentation into its own file `user-storage.md`
* Converted the old storage documentation into `md` since that's what the new documentation was written in
Would be worth double-checking the links etc, because converting the old rST into sphinx-friendly markdown is kind of confusing, but I think I figured it out. Here's a demo:
http://predictablynoisy.com/zero-to-jupyterhub-k8s/user-storage.html
=> updating storage documentation

images/hub/Dockerfile, minikube-config.yaml
- Running pre-puller on travis causes trouble, since it takes
more than 10mins apparently to pull the singleuser image from
dockerhub. This causes all times we do not rebuild the singleuser
image to fail on travis
- Fixup z2jh.py location for python3.6
=> Fix travis failures

chartpress.yaml, doc/source/security.md, images/hub/jupyterhub_config.py, images/network-tools/Dockerfile, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/pre-puller/_helpers.yaml, jupyterhub/values.yaml
Uses an iptables block to block access to the cloud metadata
ip used by the most common cloud providers (Google, AWS, Azure).
This is enabled by default so we can be secure by default.
Fixes #407 
TODO:
=> Block access to cloud metadata endpoints by default

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml
- Makes it easier for autoscaling clusters, since we already
have a PodDisruptionPolicy that says do not scale down
clusters with these running!
- As a side effect, also makes hub restarts when doing helm
upgrades faster, since it is most likely going to come back
on the same node, which already has PVC attached and image
pulled
Fixes #395
=> Have hub and proxy stick to same node if possible

ci/deploy.sh
Post-merge, sometimes deploy fails because of build network
failures. This then breaks every succeeding PR, since the image
has not been pushed.
This will retry the build + push upto 3 times if it fails.
Fixes #434
=> Use travis_retry with deploy.sh

ci/install.sh, jupyterhub/templates/pre-puller/job.yaml, jupyterhub/templates/pre-puller/rbac.yaml, minikube-config.yaml
This allows users to retry easier if helm fails to install.
Also enables RBAC in our Travis tests, so we can catch RBAC issues here!
Fixes #425
=> Put time in RBAC for pre-puller names

jupyterhub/templates/hub/deployment.yaml, jupyterhub/values.yaml
This is very useful when you are also mounting extra containers
and want to configure them.
=> Allow mounting extra Volumes / VolumeMounts on hub pod

doc/source/user-environment.rst
There was an indentation type-o for the pre-pulling instructions, this fixes that
=> fixing typo in documentation for pre-pulling

images/singleuser-sample/Dockerfile
should fix path/permissions issues when container is configured to run with elevated permissions, which were briefly broken in docker-stacks and we just so happened to bump the base image while that was true.
cc @cam72cam who reported this on gitter
=> bump singleuser-sample base image

ci/deploy.sh
travis_retry is not available during retry stage!
This broke our CI.
Reverts jupyterhub/zero-to-jupyterhub-k8s#435
=> Revert "Use travis_retry with deploy.sh"

images/pre-puller/node.go
I seem to make this typo all the time.
Fixes #448
=> Fix typo causing helm to hang when unschedulable nodes exist

doc/source/upgrading.md
Partially addresses #392.
- Reordered some sections starting with tips and warnings
- Shorten specific release sections
- refer 0.6 upgrade to CHANGELOG
- refer 0.5 upgrade to 0.5 docs and remove 0.5 specific information
- Make subtopics/subsystems generic
- Add a very brief troubleshooting tip for upgrading
=> Update upgrade doc and make generic

images/pre-puller/node.go
This is usually used to prevent pods from scheduling on a node
without explicit tolerations. The defaults for many cluster management
setups (such as https://github.com/Azure/acs-engine and I think
many amazon setups) use this to prevent master from being scheduled,
so we should respect this.
Fixes #454
=> Handle the 'NoSchedule' taint on nodes properly

doc/source/create-k8s-cluster.rst, doc/source/setup-helm.rst
`helm version` sometimes takes a bit of time for the Server to display.
=> Edit GKE command in doc and add note on helm version

doc/source/debug.rst, doc/source/extending-jupyterhub.rst, doc/source/setup-jupyterhub.rst, jupyterhub/Chart.yaml, jupyterhub/values.yaml
This bumps the helm chart to v0.6 and updates the documentation to reflect the new release.
=> Bump helm chart to v0.6

doc/source/authentication.rst
this seems to be a run-away section that was moved to the end of the doc.
=> Remove duplicated section about whitelist

doc/source/index.rst, doc/source/troubleshooting.rst
- There is already a 'debug' that should have all the debugging info
- The Google Cloud specific stuff in the Troubleshooting section are
out of date and no longer accurate
- We make this into a FAQ, which can be used for both general and
cloud specific questions people might have.
=> Move troubleshooting to FAQ

doc/source/create-k8s-cluster.rst
The old GKE version we recommended is now deprecated, so will cause an error. This bumps it and adds a warning message in case this happens in the future.
cc @yuvipanda
=> updating gke version in docs

CHANGELOG.md, doc/source/setup-helm.rst
https://github.com/kubernetes/helm/issues/3275 has caused
serious amounts of downtime in the last week or so for
various deployments at Berkeley, so let's recommend people use
the last known version that did not have these issues.
=> Pin helm version to v2.6.2

doc/source/_static/custom.css, doc/source/conf.py
This makes a couple of small improvements to the sidebar:
* Moving the search bar to the top of the sidebar so it's more discoverable
* Tweaking the CSS so that section headers are larger than content underneath + bold so that they're more easily separable visually
Old
New
Here's a live version: http://predictablynoisy.com/zero-to-jupyterhub-k8s/
What do folks think about the CSS tweaks? @willingc ?
closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/482
=> sidebar improvements

CONTRIBUTING.md
This adds more fleshed out instructions for cutting a new release, and was inspired by the most recent (v0.6) release of JupyterHub's helm chart. Somebody other than @choldgraf should test this out the next time we need to make a release!
=> Dev instructions for new releases

doc/source/cost.rst
We've had a few conversations about whether to keep / remove the cost estimator, but in the meantime this makes the warning about accuracy a bit more obvious / clear.
Note: I'd prefer if this didn't turn into a "should we just remove the cost estimator link entirely" conversation...I'm happy to have that in another issue. In this case I just want to make sure the warning message is better :-)
=> adding a warning about the cost estimator

doc/source/user-storage.md
Adds a warning to the user storage section about node disk size limits.
closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/274
=> node disk size interaction docs

jupyterhub/values.yaml
avoids redirect when asking the Hub to render an error page
=> add /hub to proxy error-target

jupyterhub/Chart.yaml
This would make CI produce charts like v0.7-<something>
which is more accurate
We should amend the release process to make this be a part
of it!
=> Bump base version to v0.7

doc/source/glossary.rst
Drive-by updated, previous link to jupyterhub authenticator docs returned 404.
=> Doc: fix a link in the glossary

CHANGELOG.md, doc/source/setup-helm.rst
As @consideRatio  pointed out, 2.6 is too old for us -
the hook configuration we are using is not present until 2.7.
=> Revert pinning helm versions to 2.6

images/hub/cull_idle_servers.py
attempting to cull a user whose server is slow to stop results in a `400 DELETE` error, which seems to exit the culler process.
user will be deleted in a later round when the server has finished stopping.
The initial request in `call_sync` was failing, which causes the script to exit. This is replaced with an `add_callback`, in which case errors are logged instead of exiting.
closes #522
=> avoid culling users whose servers haven't stopped

dev-requirements.txt
pinning strict requirements is okay for application deploymens to do, but not for user environments, which is how we are using dev-requirements in CONTRIBUTING.md
=> unpin dev requirements

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml
Follow-up to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/501
This allows [`OAuthenticator.scope`](https://github.com/jupyterhub/oauthenticator/blob/0.7.3/oauthenticator/oauth2.py#L199) to be set. The default is ~`[read:org]` if `auth.github.org_whitelist` is set, otherwise~ empty.
`auth.github.org_whitelist` unset, `auth.scopes` unset:
`auth.github.org_whitelist` set, `auth.scopes` set to `[read:org]`:
`auth.github.org_whitelist` set, `auth.scopes` set to `[read:org, read:user, user:email]`:
In theory this property should also work with other OAuth providers, but I don't have an easy way to test.
=> Allow configuration of OAuthenticator.scope

images/hub/jupyterhub_config.py
To make the 'pack' scheduling strategy so that singleuser-pods first schedule on the hub node, and only if it is full, have them schedule on other nodes, and if so they schedule on the nodes with most singleuser images already.
---
With `schedulerStrategy: pack`, I expect my pods to pack into nodes allowing for a kubernetes cluster scaler to scale up and down efficiently. It cannot scale down if there is a hub on the node, so therefore the pods should start packing on the hub node, then onto other nodes.
I got this issue while having 0 users and 2 nodes. When I added my first user it was spread to the non-hub node, then every other user was packed into that node, and later they would populate the hub node. With only one user, I would not be able to scale down even though I had enough …
=> Fixes #504 - Singleuser pod packing at hub node first

jupyterhub/Chart.yaml, jupyterhub/values.yaml
these values (both name and tag) are autogenerated by chartpress, so the values stores in values.yaml will never be used.
We could also replace these with an empty dict, so that it's extra clear that the image data needs to be filled out by running `chartpress`, and the values.yaml tracked by the repo is never valid.
cc @consideRatio who I think may have run into an issue related to this.
=> fill image tags values.yaml with placeholders

images/hub/cull_idle_servers.py
avoids orphaning Futures when a cull request fails
orphaned futures could end up never finishing their request to the Hub, resulting in a failure to cull servers after the failing request
=> culler: await every Future when culling

doc/source/authentication.rst
Makes GitHub first (since it's the easiest+most free of the auth steps) and adds a bit of extra information
=> small updates to auth docs

doc/source/authentication.rst
Remove "hub" as its an overused term and potentially confusing.
=> Rephrase definition of GitHub

CONTRIBUTING.md
Add same wording that we have in BinderHub contributing re: installing from binaries instead of homebrew for MacOS.
=> Add info about minikube install for MacOS

doc/source/advanced.md
Based on discussion with @yuvipanda on Gitter. This PR provides a specific link to the community maintained nginx ingress controller.
=> clarify recommendation for community nginx ingress controller

jupyterhub/Chart.yaml, jupyterhub/values.yaml
Addresses #556.
- Adds additional information fields to Chart.yaml
- Adds minimal descriptions to values.yaml (See [Chart Best Practices](https://docs.helm.sh/chart_best_practices/#document-values-yaml))
=> Add informational fields and minimal comments to jupyterhub chart

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
This allows the pvc and volumes used for single user to have custom names, which is useful is the user names are long (> 60 characters) as this will fail in kubernetes.
=> Customization options for dynamic storage

images/hub/cull_idle_servers.py
=> use urllib quote to encode username in culler FIX #573

jupyterhub/templates/image-puller/_helper.yaml
Without this, the continuous pre-puller pods do not work,
since they're stuck in the old image version forever.
https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/
has more info
=> Make daemonsets do a rolling update

doc/source/reference.txt
This fix is for issue #561 
Updated references.txt replacing the old `user-experience.html` link with new `user-environment.html` link. Changed the link text to be 'user environment'
=> Update references.txt with new user environment link

jupyterhub/templates/hub/configmap.yaml
truncating whitespace with `{- end }` results in nesting configs within each other, e.g.
```yaml
hub.extra-config.foo.py: |
foo-config
hub.extra-config.bar.py: |
bar-config
```
=> fix newlines between multiple hub.extraConfig entries

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml
As @minrk pointed out in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/367#pullrequestreview-86373648,
this is actually unsafe. My comment about the proxy being safe
also do not make sense in hindsight.
This reverts commit 7d03d6459ff8d186abe2e854d524c71eca3c51d3.
=> Revert "Set maxUnavailable appropriately for hub & proxy pods"

jupyterhub/values.yaml
avoids warning:
> warning: destination for extraConfig is a table. Ignoring non-table value
does not appear to affect behavior, though, only the warnings. I believe the ignored value is the default `extraConfig` empty string, which has no effect.
closes https://github.com/jupyterhub/binderhub/issues/483
=> default extraConfig is a dict

jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/netpol-hub.yaml, jupyterhub/templates/hub/netpol-singleuser.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/netpol-proxy.yaml, jupyterhub/values.yaml
Adds network policies based on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/534#issuecomment-368542041
For now I've included ingress and egress rules so that there's a record of what was discussed above.
Policies are enabled by setting `{hub,proxy,singleuser}.networkPolicy.enabled`, default is `False`.
I've added `{hub,proxy,singleuser}.networkPolicy.egress` with the egress rules I thought could be optional, the idea being:
- Ingress/Egress rules which are required for jupyterhub pods to minimally function should always be defined
- Rules which are useful but which someone might want to restrict further are defaults which can be overridden
Since the proxy and hub should be trusted relaxing the rules and allowing all egress for them could be OK, the main benefit of egress …
=> Initial network Policies for hub proxy singleuser

CONTRIBUTING.md
- removes unnecessary separate macOS command
- adds missing clusterrole fix required for RBAC to work
=> [contributing] update minikube start command

jupyterhub/schema.yaml, jupyterhub/values.yaml
@betatim do you know if this will affect peoples storage solution?
Perhaps we could add this for next release and declare in the upgrade instructions to manually set the gid to 1000 again if they will have some old user storage that has a memory of the gid=1000 situation.
closes #506
=> Fixes #506, gid=100 instead of 1000, causes storage permission issues?

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
This is useful during development of singleuser images. Most other images in this chart already have a `pullPolicy` or `imagePullPolicy` property.
=> Allow singleuser_image_pull_policy to be modified

doc/source/_static/custom.css
Follow up to #594 
- Style the toctree-heading caption CSS to be less prominent
=> style toctree heading in body

images/hub/requirements.txt
Brings in https://github.com/jupyterhub/ltiauthenticator/pull/5
Thanks to @brospars for the patch!
=> Bump ltiauthenticator version

jupyterhub/schema.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/values.yaml
This was discussed back in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/228, but was not done because of difficulties with `toYaml`. It looks like `indent` hadn't been discovered then.
Motivation: I'm adding tracing to the `hub` component, and I need to use `valueFrom` to access the downward API.
=> Change schema of hub.extraEnv to allow use of `valueFrom`

jupyterhub/templates/proxy/autohttps/_README.md, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/autohttps/ingress-internal.yaml, jupyterhub/templates/proxy/autohttps/nginx-configmap.yaml, jupyterhub/templates/proxy/autohttps/rbac.yaml, jupyterhub/templates/proxy/autohttps/service.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/nginx-configmap.yaml, jupyterhub/templates/proxy/secret.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/values.yaml
The extra network hop is worth the following advantages:
1. The code is much easier for us to understand and reason about.
2. We have pod affinity set up to try to place all three components
(hub, proxy, autohttps) in the same node if possible. This
should cut down on hops!
3. For users with at least one proxy in front of the hub,
this is a much cleaner way to disable the extra nginx cost -
both in terms of resources and extra processing overhead.
Longer term, we should build / use a proxy implementation that
can automatically get certificates from ACME and store them
in Kubernetes Secret objects.
We also terminate HTTPS in CHP when using manual HTTPS, avoiding
an extra hop unnecessarily. IIRC this means we lose http/2 when
using manual HTTPS, but that feels fine for now.
=> Separate automatic HTTPS to its own deployment

jupyterhub/templates/proxy/deployment.yaml
Looks like there was a copy and paste error in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/592/files#diff-901145829b96bb9fea44682f2e1d3f83R67
```
$ kubectl get pods --selector=name=proxy
NAME                    READY     STATUS             RESTARTS   AGE
proxy-9564c448d-88qv8   0/1       CrashLoopBackOff   3          1m
$ kubectl logs --selector=name=proxy
error: unknown option `--log-level debug'
```
=> Missing = in configurable-http-proxy args

jupyterhub/templates/hub/deployment.yaml
A simple syntax error with a simple fix - I think! In this PR I simply replaced `{# these types of comments #}` with `# these types of comments`. 
Perhaps `{# this comment syntax #}` is valid, but if so it seem to have caused some indentation errors. I got an error on my `helm upgrade ...` command that appears to be commonly associated with indentation issues.
```shell
Error:
UPGRADE FAILED:
YAML parse error on z2jh-extended/charts/jupyterhub/templates/hub/deployment.yaml:
error converting YAML to JSON: yaml: line 111: could not find expected ':'
```
Ping #597 @mattjbray @yuvipanda
=> {# comments #} replaced with # comments

.travis.yml, ci/deploy.sh, dev-requirements.txt, jupyterhub/values.yaml
- run `git diff` after chartpress to show changes, in case something suspicious is in values.yaml
- pin specific chartpress commit so that chartpress only changes explicitly (there's also a slight possibility of caching being responsible for the recent weird chartpress behavior in #612)
- rerender values.yaml with recent changes that deviated slightly in style to avoid churn when chartpress rerenders values.yaml
closes #612
=> debug chartpress, disable shallow-clone

jupyterhub/templates/hub/rbac.yaml, jupyterhub/templates/image-puller/_helper.yaml, jupyterhub/templates/pod-culler/rbac.yaml, jupyterhub/templates/proxy/autohttps/rbac.yaml
This PR was supposed to fix #619, but became documentation on how to handle the errors encountered on helm upgrades. These are supposedly fixed in Helm 2.8.2 assuming a clean slate of helm release revisions.
```
Error: UPGRADE FAILED: <object type> with the name <object name> not found
```
- [Issue reproduced](https://github.com/kubernetes/helm/issues/2941#issuecomment-363537224)
- [Issue fixed](https://github.com/kubernetes/helm/pull/3539)
You attempt to make a helm upgrade, but something like this hits you...
```
Error: UPGRADE FAILED: no ServiceAccount with the name "pod-culler" found
Error: UPGRADE FAILED: no Deployment with the name "hub" found
Error: UPGRADE FAILED: no ServiceAccount with the name "autohttps" found
Error: UPGRADE FAILED: no DaemonSet with the name …
```
=> Helm upgrade error "... with the name ... not found" and how to handle it

jupyterhub/Chart.yaml
I ran `helm lint` on the chart successfully, but was warned about a missing icon. This PR adds that icon.
PR based on reading up on what to be included in Chart.yaml [according to Helm](https://github.com/kubernetes/helm/blob/master/docs/charts.md#the-chartyaml-file) and [according to kubernetes/charts repo](https://github.com/kubernetes/charts/blob/master/test/circle/yaml-schemas/Chart.yaml) as well as by looking at charts published in kubernetes/charts.
I added required kubeVersion and tillerVersion to be 1.8+ (k8s daemonset API) and 2.7+ (helm delete annotations). See #502 for more details. Having Helm (tiller) 2.8.2 would avoid issues like described in #620 - but is not essential.
=> Chart.yaml - icon + kube & helm versions

jupyterhub/Chart.yaml
An issue arised with comparing ">=1.8.0" with "v1.9.4-gke.1", due to the -gke.1 appendix. This commit reverts the usage of the contraint for now.
* [This is an online SemVer checker](http://jubianchi.github.io/semver-check/), it is supposed to be able to handle `+` something, but not `-`.
* [This is the line it fails on in the comparision](https://github.com/kubernetes/helm/blob/master/pkg/tiller/release_server.go#L260).
* [This is the referenced function called IsCompatibleRange](https://github.com/kubernetes/helm/blob/58e4b6ac61938fe056037826225dd19562c0ed9f/pkg/version/compatible.go#L48-L61)
=> Revert k8s-versioning constraint

doc/source/cost.rst, doc/source/index.rst
Closes #626 
- Moves cost projection section to an appendix of the administrator guide.
- Adds a clarification section at the beginning
- Reorder to have all factors precede the cost estimator
=> clarify expectations for cost estimation

jupyterhub/templates/proxy/netpol-proxy.yaml
I think https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/592 means direct access to port 8000 on the proxy may be required. Without it I get a 504 gateway error from my external K8s ingress.
I'm not sure if this port needs to be always open, or only if the internal HTTPS ingress is disabled
=> NetworkPolicy access to proxy 8000 / 8443

images/pod-culler/culler
if the pod hasn’t started yet
closes https://github.com/jupyterhub/binderhub/issues/510
=> pod.status.start_time can be None

jupyterhub/values.yaml
- hub.extraEnv's default value now {}, before it was [].
- prePuller.extraImages was referenced in the image-puller daemonsets, and now has an empty placeholder.
- I also made some spacing consistent throughout the file.
[@manics wrote](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/597#issuecomment-378667725):
> I thought I'd mention a use case for keeping the backwards compatibility in future too. If extraEnv is a dict you can easily merge a public config in a git repo with private variables set on the command line during, e.g.
>
>```yaml
> hub:
>   extraEnv:
>     OAUTH2_AUTHORIZE_URL: "https://login.elixir-czech.org/oidc/authorize"
>     OAUTH2_TOKEN_URL: "https://login.elixir-czech.org/oidc/token"
>     OAUTH_CALLBACK_URL: https://example.org/hub/oauth_callback
> …
```
=> [MRG] values.yaml: extraEnv and extraImages

doc/source/security.md
Documentation for https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/546#issuecomment-375025036
=> Document network policies

jupyterhub/templates/hub/deployment.yaml
The whitespace trim here causes newline to be removed, so the first line of the `toYaml` block receives the indent from the `if` line. This produces broken output when `extraEnv` of `[]` is present.
=> Dont trim whitespace before toYaml to avoid extra indentation

jupyterhub/Chart.yaml
This works for now. I started some discussion on kubernetes/helm and  regarding the surprise I got when the ">=1.8.0" constraint failed to match "v1.9.4-gke.1".
For reference, see [kubernetes/helm issue #3810](https://github.com/kubernetes/helm/issues/3810) and [Masterminds/semver issue #69](https://github.com/Masterminds/semver/issues/69).
=> kubeVersion in Charts.yaml works now

images/hub/cull_idle_servers.py, images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
from https://github.com/jupyterhub/jupyterhub/pull/1779
- use semaphore to limit Hub API activity, which may improve hub performance with lots of culling (e.g. mybinder.org)
- supports max-age culling (with jupyterhub 0.9), which will allow us to deprecate the podCuller image when we bump jupyterhub
=> import updated culler

images/pod-culler/culler
The existing message log message can be misinterpreted to read that zero of 244 "scheduled for deletion" pods were deleted and implies that 244 more pods need deletion.
```
[I 2018-04-17 15:01:34 culler:143] Culling pods older than 06:00:00
[I 2018-04-17 15:01:34 culler:161] Deleted 0/244 pods
```
I understand that if one has context of the number of total pods then it may not be confusing. But if you don't know if there are 5000 pods or 244, it is easy to misinterpret. Recommend change:
```
[I 2018-04-17 15:01:34 culler:143] Culling pods older than 06:00:00
[I 2018-04-17 15:01:34 culler:161] Deleted 0 pods. Pod count=244
```
=> clarify log message

CONTRIBUTING.md
Minikube is now at version 0.26. This updates the mac instructions. The RBAC instruction is no longer needed in the `minikube start` command as of v0.26.
=> update minikube for mac instructions for latest version

doc/source/microsoft/step-zero-azure.rst
Cloud shell already has kubectl installed and trying to install it within cloud shell will cause access denied errors.
=> add note about kubectl on azure cloud shell

images/hub/jupyterhub_config.py, images/hub/requirements.txt, images/hub/z2jh.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/264
Based on https://github.com/jupyterhub/ldapauthenticator/blob/1bb93f3ad258fdcc464c5e5c88f36005ae579ce0/README.md
I've tried to follow the general pattern in `jupyterhub_config.py` when naming LDAP parameters but not everything is clear to me.
LDAPAuthenticator seems to have many more parameters than the other auth providers, so I added a new function `set_config_if_not_none` in z2jh.py to make it easier to keep the built-in defaults from LDAPAuthenticator when a value isn't overridden.
I've only tested this with my own setup:
```yaml
auth:
type: ldap
ldap:
server:
address: ldap.EXAMPLE.org
port: 389
ssl: False
dn:
templates:
- 'cn={username},ou=edir,ou=people,ou=EXAMPLE-UNIT,o=EXAMPLE'
allowedGroups:
- …
```
=> Support LDAP login (LDAPAuthenticator)

doc/source/setup-jupyterhub.rst
This helps on AWS when the ELB's dns entry is really long
Ex:
```
kubectl --namespace=splat-test get svc proxy-public -o wide
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP                                                               PORT(S)                      AGE       SELECTOR
proxy-public   LoadBalancer   100.70.50.207   aef52d88a4a1911e899ba1253ff0cfc6-1410174889.us-east-1.elb.amazonaws.com   80:30917/TCP,443:30502/TCP   1h        component=proxy,name=proxy,release=splat-test
```
=> Add wide output to public-proxy query

jupyterhub/templates/image-puller/rbac.yaml
The `image-awaiter` job used in conjunction with the `hook-image-puller` does not need a `ClusterRole` and a `ClusterRoleBinding` as it will no longer inspect the nodes in the cluster, but instead simply inspect a `DaemonSet` within the current namespace. This PR simply replaces `ClusterRole` with `Role`, and `ClusterRoleBinding` with `RoleBinding`.
* This PR is based on the insight of @manics and fixes #671.
* I think it will reduce but not fully fix the challenges for @gsemet (#178) who has a JupyterHub on a cluster but is limited to namespace-wide administrative permissions (Role) for the cluster rather than cluster-wide permissions (ClusterRole).
=> Tighten up hook-image-puller's image-awaiter jobs requested RBAC permissions

images/hub/Dockerfile
just bumping the base image now that an LTS is available.
=> base hub image on 18.04 lts

chartpress.yaml
fixes base_url regressions in 0.9b1, other small fixes
=> jupyterhub 0.9.0b2

doc/source/authentication.rst
closes #684
@rsignell-usgs what do you think?
=> authentication github org clarification

doc/source/user-environment.rst
During my first attempt at using a custom Docker image in a k8s JupyterHub deployment, I think I found a documentation bug.
An image built using `repo2docker` without the `--user-name=jovyan` argument embeds my local `$USER` in the Docker image, which causes the single-user server pods to fail (details below).
In a separate commit, I also thought it might not hurt to reiterate the important detail that `jupyterhub` must be specified as a dependency in the image, as I missed that on my first, admittedly hasty reading. If you decide reiteration is unnecessary, feel free to blow that commit away and just keep the one with `--user-name`.
<details>
```
Traceback (most recent call last):
File "/srv/venv/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
value = …
```
=> Repo2docker needs jovyan username

images/hub/Dockerfile
chartpress currently does not consider the chartpress.yml itself when
deciding if an image needs rebuilding. As a result the hub image has
not been rebuilt recently. Touching the Dockerfile is a temporary
fix till chartpress has been updated.
Will self-merge this after discussing with Min on gitter.
=> Add a newline as temporary fix to trigger chartpress rebuild

jupyterhub/templates/hub/deployment.yaml
hub-container container is redundant
=> call the hub container 'hub'

images/singleuser-sample/Dockerfile
Complementing #694 by bumping the singleuser image to jupyterhub 0.9.* as well.
=> JupyterHub 0.9.* for the singleuser image also

doc/source/authentication.rst
This changes the authnetication docs for GitHub organisation OAuth to recommend a scope of `read:user` as this has the least additional complications, see the linked issue:
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/687
=> Clarify auth.scopes setting for github org oauth

jupyterhub/templates/hub/configmap.yaml
Some `auth.ldap` values (mostly used in AD) were missing quotes in the config map.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/679
=> Quote all auth.ldap values

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/image-puller/rbac.yaml, jupyterhub/templates/pod-culler/deployment.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/service.yaml
@minrk realized that by setting the chart label containing the chart version systematically everywhere as was done in #625, some pods, like the hub and the proxy, were restarted without any good reason during helm chart upgrades.
This PR does not fully remove the chart label as #711 propose, but instead selectively removes the chart label and the heritage label for pods created by controllers using a PodTemplate. Such controlled pods will be restarted if the controller concludes that a new template is available, even if it is simply a change to the labeling.
In #625 I also systematically introduced a name field to controllers spec.template.metadata.name, but that field is overridden anyhow so I simply removed it again. For example the hub Deployment's pods will be named …
=> templates' name and label fields fixed

doc/source/turn-off.rst
Was unable to use the CloudFormation page above to delete resources (nothing was there to delete, yes region was correct) 
Terminating resources from ec2 console causes resources to be re-spawned.
Only wan to remove was to run `kops delete cluster`
=> update instructions for spinning down aws resources

doc/source/amazon/efs_storage.rst
For https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/421
=> Create EFS storage guide for AWS

images/hub/requirements.txt
This just bumps the version of kubespawner in the hub requirements file. Perhaps a proper release from kubespawner would be a better idea but in the short term, I'm working on propagating the changes in https://github.com/jupyterhub/kubespawner/pull/193 through to JupyterHub and Binder.
=> bump kubespawner version (actually commit hash)

images/hub/jupyterhub_config.py
using deprecated names in default config can impede users setting the non-deprecated values
closes #745
=> avoid using deprecated `singleuser_` and `user_` config names in kubespawner

doc/environment.yml, doc/source/conf.py
This adds a couple small scripts that add a "copy" button to code blocks, so people don't have to manually copy/paste them. Here's an example!
https://predictablynoisy.com/zero-to-jupyterhub-k8s/google/step-zero-gcp.html
=> adding copy buttons to code blocks

jupyterhub/templates/_helpers.tpl
@betatim @minrk Sorry for causing this, this closes #751.
the helper `jupyterhub.matchLabels` will return labels based on the files parent directory (`component: pod-culler`), but that can be overridden if one passes the helper a scope containing a `.componentLabel`.
Note that the output will be:
`component=singleuser-server,app=jupyterhub,release=prod`
Instead of:
`component=pod-culler,app=jupyterhub,release=prod`
Using the `app` and `release` as selectors as well is done systematically on all pods according to helm chart best practices.
=> Fixes #751 - A pod-culler bug

ci/install.sh, ci/minikube.env
Bumping CI to use latest k8s/helm/minikube.
Currently #758 CI is failing to start because Helm 2.9.1 is required.
- [Minikube changelog](https://github.com/kubernetes/minikube/blob/v0.28.0/CHANGELOG.md)
=> CI bump: k8s 1.9.0 / helm 2.9.1 / minikube 0.28.0

images/hub/jupyterhub_config.py, images/hub/requirements.txt, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
Deploys and exposes https://github.com/jupyterhub/kubespawner/pull/213
events are disabled by default due to recent issues, but should be enabled by default when they are fixed.
=> expose KubeSpawner.events_enabled as singleuser.events

jupyterhub/schema.yaml
Should be JUPYTERHUB_CRYPT_KEY instead of JUPYTERHUB_CRYPTO_KEY
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/deployment.yaml#L139-L143
=> Should be JUPYTERHUB_CRYPT_KEY

jupyterhub/templates/image-puller/_daemonset-helper.yaml
Currently this fails since container should be alphanum.
```
prePuller:
extraImages:
cpu:
name: custom.registry-server/repo/image
tag: latest
```
=> Make sure image puller works with long repo names

doc/source/turn-off.rst
Also, typo further down that page.
=> Clarify gcloud terms in instructions on stopping and cleaning up.

jupyterhub/templates/hub/deployment.yaml, jupyterhub/values.yaml
Since the default storage backend is sqlite on pvc, we should be using the Recreate strategy as we bumped the deployment to apps/v1beta2. Otherwise upgrading will have new hub pod stuck in ContainerCreating state.
This is a regression caused by a84ad294. Detailed analysis can be found in #754.
Closes #754
Closes #757
=> Hub default deployment strategy should be Recreate

doc/source/user-environment.rst
This is an attempt to clarify how to pre-populate the user's $HOME with files.
=> Add specific example and clarification for your $HOME files

jupyterhub/schema.yaml
Fix wrong spelling of the word `description`.
=> Fix incorrect spelling of `description` in chart schema

.travis.yml
Follow up #762 
Since adding a build matrix testing several kubernetes versions we are
deploying twice, once for each kube version. This changes our deploy
setup so it only deploys once.
=> Change travis setup to only deploy once

doc/source/tips.rst
- Provide a bash code-block directive for code blocks.
- Remove single underscores surrounding text: these were presumably
meant for emphasis (as in Markdown), but incorrect for ReST and not
necessary.
- Apply :kbd: role for TAB mention
- Remove trailing whitespace
Fixes #798
=> Clean-up tips section

images/hub/jupyterhub_config.py, images/hub/z2jh.py
Ensure url correctness in jupyterhub_config.py of cull configuration
using url_path_join. Function url_path_join define in z2jh.py.
=> Ensure url correctness

images/hub/cull_idle_servers.py
This PR handles the deletion of named servers in the culling script. The change also affects the main jupyterhub repo, e.g. https://github.com/jupyterhub/jupyterhub/blob/master/examples/cull-idle/cull_idle_servers.py#L190
=> hub: correctly delete named servers

images/hub/requirements.txt
Updates tmpauthenticator to the latest release. Includes useful improvements such as automatically starting a server when a user visits `/`, previously only `/tmplogin` would create a server.
=> Bump jupyterhub-tmpauthenticator to 0.5

doc/source/security.md, jupyterhub/templates/proxy/service.yaml
Rather than always having different target ports for the HTTP and HTTPS frontends, setting proxy.https.type to offload will tell the service to route ports 443 and 80 both to port 80 on the backend.
For this to work, annotations need to be added to proxy.service.annotations to attach certificates to the load balancer.
=> Support offloading SSL to the proxy service

jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/values.yaml
Hello,
I manage my certificates using an external tool (saltstack) that can put secrets into kubernetes, and I wanted for jupyterhub to be able to use an already-existing secret.
I've implemented this funcionality there, and tested it, it takes a secret name and the name of the certs in the secret
It's like one of my first PR ever, so pleas be kind, I'm open to any suggestion, like where to put the documentation, what to document
Thanks for all the work !
=> Funcionality : being able to give an already existing secret as SSL

chartpress.yaml, images/hub/jupyterhub_config.py, images/hub/requirements.txt, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
- jupyterhub 0.9.2
- oauthenticator 0.8.0
adds `hub.consecutiveFailureLimit` config with a default of 5. After 5 consecutive launch failures, the Hub will restart. This should get some self-healing when reflectors get stuck.
After this PR, 0.7 should only be waiting on KubeSpawner release (code-wise), which should come soon after the latest changes get some testing on mybinder.org tomorrow.
=> more hub image bumps

doc/source/conf.py
The sphinx_copybutton API changed (hopefully for the last time) so this unbreaks the docs build
=> copybutton fix

doc/source/_static/custom.css
Closes #847 
Bootstrap used by copybutton brought in a _type.scss file that was increasing the sidebar h1 setting. This PR sets `sphinxsidebar.h1` to a smaller value in our `custom.css`.
Rendered: https://test-zerotojh.readthedocs.io/en/adjust-sidebar/
=> add h1 sidebar setting

doc/source/extending-jupyterhub.rst, doc/source/setup-jupyterhub.rst, jupyterhub/Chart.yaml
"v" may be used as a git tag prefix for versions, but isn't part of the version string itself
=> remove "v" prefix from versions

jupyterhub/templates/hub/configmap.yaml
The config entry cull.maxAge was previously never consumed by the
jupyterhub_config.py as it reads from its configmap where the entry
cull.max-age was never set. This affected maxAge based cullings on
JupyterHub 0.9+ to never cull due to exceeding a set maxAge.
=> cull.maxAge ignored bugfix

jupyterhub/Chart.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/image-puller/rbac.yaml
Thanks to the new `before-hook-creation` deletion policy, we can avoid the `object already exist` error as Helm would simply delete and recreate the resource instead if it found a resource with the same name. This means that we can use a single name for the puller daemonset and won't ever orphan a puller daemonsets after a failed upgrade followed by a successful upgrade.
=> No more duplicates of puller pods

jupyterhub/templates/image-puller/rbac.yaml
Sigh I'm sorry @minrk I messed up... #854 was not free of errors, it did not change all the hook-delete-policy fields as it needed to do.
We must release a 0.7.0-beta.2 (or override beta.1) thanks to this, or it is not stable enough.
=> final (?) bugfix of hook-image-puller

jupyterhub/values.yaml
The event reflector issues should be fixed in kubespawner, so let’s re-enable events by default so that the spawn progress page gets kube events
=> enable events by default

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml
Kubespawner allows you to specify extra annotations for the singleuser notebook pods however there is no way to set this from the helm chart.
This PR adds some extra config to pass these values through.
Fixes #810
=> Add extra annotations option

jupyterhub/schema.yaml, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/singleuser/image-credentials-secret.yaml, jupyterhub/values.yaml
---
@AlexMorreale helped us use config.yaml to install a Kubernetes Secret which could be referenced by pods that want to pull from image registries that required some credentials - this is #801.
This PR complements Alex work by...
- Allowing for the email field to optionally be configured, which seem to be utilized by some registries but not all.
- Adds support for setting large JSON blobs in the password field, something that is required in order to pull from a private gcr.io registry from an external cluster.
- Ensures that the image puller DaemonSets, both `hook-` and `continuous-` have the same credentials to pull the images.
Fixes #871.
---
Note that with #844, this pr will ensure that the Helm template within `jupyterhub/templates/singleuser/image-credentials-secret.yaml` is valid …
=> Pulling images from external private image repositories

README.md
`z2jh.jupyter.org` instead of `zero-to-jupyterhub.readthedocs.io`
=> README.md - Default to z2jh.jupyter.org

jupyterhub/schema.yaml
In the file `jupyterhub/templates/hub/configmap.yaml`, the `imagePullPolicy` for the `singleuser` pods is set with the line:
```
singleuser.image-pull-policy: {{ .Values.singleuser.image.pullPolicy | quote }}
```
I have corrected the docs to indicate this.
Thank you for creating this very useful project!
=> correct error in documentation regarding singleuser.image.pullPolicy

images/singleuser-sample/Dockerfile, images/singleuser-sample/README.md
The singleuser-sample image that we provide needed a refresh.
- I updated the README.md file next to it
- I removed an additional install of jupyterhub (docker-stacks images already has it)
- I added git and nbgitpuller
- The compressed image size went from about 230 to 260.
=> Refreshed singleuser-sample

jupyterhub/templates/hub/netpol.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/singleuser/netpol.yaml
it's redundant to ask for `kubectl get networkpolicy hub-network-policy`.
In general: don't put resource type in resource names
=> remove `-network-policy` from network-policy names

images/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/_helpers.tpl, jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
The user-scheduler is great for use with a cluster autoscaler and bad 
without it. With the user-scheduler optionally enabled users will be 
packed to fill up one node at the time. This in turn tends to create 
totally unused nodes that are easy for a cluster autoscaler to scale 
down the unused node. Without a cluster autoscaler, it is just a waste 
of resources to get yourself unused nodes though, so only enable the 
user-scheduler if you have a cluster autoscaler.
NOTE: This works without k8s 1.11. Only *user-placeholder* utilizing *pod priority* and *pod preemption* require k8s 1.11.
**IMPORTANT:** Everything inside this PR is *disabled by default*, and can be optionally enabled by config.yaml by passing `scheduling.userScheduler.enabled: true`. This means that the PR is very …
=> [Part 2 of #758] user-scheduler added

jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, minikube-config.yaml
log-level 10 gets everything, including every byte of every request and reply made to the kube api. Unfortunately, scheduler decisions and every-request-byte are logged at the same level, so we can't debug scheduling decisions without also getting a truly massive amount of noise.
=> default scheduler log-level to 4

jupyterhub/templates/hub/pdb.yaml, jupyterhub/templates/proxy/pdb.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/pdb.yaml, jupyterhub/values.yaml
to allow controlling where it runs, let it be disrupted for scale-down.
Additionally, `minAvailable` for other pdbs is configurable, so that it can be set to 0 to allow disruptions for scale-down.
=> add pdb, nodeSelector for user-scheduler

images/hub/jupyterhub_config.py
nbgitpuller seems to work without these. I left them in
for an ancient version of Berkeley's DataHub, from which
z2jh was generalized.
Fixes #743
=> Remove deprecated GIT_ environment variables

images/image-awaiter/Dockerfile, images/image-awaiter/daemonset.go, images/image-awaiter/main.go, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/rbac.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/image-puller/rbac.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/autohttps/rbac.yaml, jupyterhub/templates/proxy/deployment.yaml
Many k8s APIs previously in beta have become stable, this is a version bump of these APIs relating to how k8s resources are defined and behave.
* Deployments  from `apps/v1beta2` to `apps/v1`
* DaemonSets changed `apiVersion` from `extensions/v1beta1` to `apps/v1`
* RBAC resources from `rbac.authorization.k8s.io/v1beta1` to `rbac.authorization.k8s.io/v1`
=> [Part 4 of #758] Bump k8s resources to v1.9 available API

jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
Cluster wide objects should be prefixed with the release name,
so we can have multiples hubs in the same cluster. For the
user-scheduler, this involves:
1. RBAC ClusterRoles & RoleBindings
2. Scheduler Name
=> Fix running multiple hubs in same cluster

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/hub/deployment.yaml
We are now using a trick to restart the hub whenever the hash of the
hub's configmap changes. This commit modernizes old logic from when
that trick wasn't in use and reduces the need for an inline explanation
of the code.
Note that this doesn't influence any behavior, it only reduces confusion for developers getting mixed messages about how things work.
---
PS: leaving all refactoring or best practice fixing of jupyterhub_config.py until the final PR where all those are fixed, in order to avoid a challenge of merging/rebasing etc with several PRs to come.
=> [Part 5 of #758] Update outdated logic for hub restarts

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
- [**Storage labels: configurable extras**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/924/commits/a95873b17309c5ca71642b68b34fa6a3698e61e1)
---
=> [Part 6 of #758] Storage labels: configurable extras

images/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/scheduling/_scheduling-helpers.tpl, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
- [**Added `singleuser.tolerations`, for node taints**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/925/commits/f243103627235c6a786bcbd1ec64698576bfb368)
=> [Part 7 of #758] Added `singleuser.tolerations`, for node taints

images/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/scheduling/_scheduling-helpers.tpl, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
- [**Added `singleuser.` node/pod/podAnti affinity**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/926/commits/a3fbb8f788a87bdb2fceb4da5b9e3fd2e105414f)
=> [Part 8 of #758] Added singleuser affinity configuration

images/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/_scheduling-helpers.tpl, jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
- [**Added `scheduling.podPriority` option**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/928/commits/e774b7dd271118fd5ee2d060fa8b1fccd7bfa0ab)
---
Pod priority requires k8s 1.11 and is a foundational functionality in order for us to use user-placeholder pods to create a headroom on nodes. This is also referred to as over provisioning. They can with a lower priority be evicted when a real user needs a place to be scheduled but cant fit on a node with them there, but at the same time when they are left unscheduled, will cause a node scaleup if an autoscaler is enabled.
=> [Part 10 of #758] Added `scheduling.podPriority`

images/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/_scheduling-helpers.tpl, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
- [**Preset: `scheduling.nodeAffinity.matchNodePurpose`**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/927/commits/972af4086517c92389ef7fc5c35326ed57fd3833)
--- 
This preset makes pods of `user | core` kind either `prefer` `require` or `ignore` a scheduling on a node with a matching label for `hub.jupyter.org/node-purpose: user | core`.
=> [Part 9 of #758] Preset: `scheduling.nodeAffinity.matchNodePurpose`

images/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/_scheduling-helpers.tpl, jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/pdb.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml, tools/templates/yamllint-config.yaml
- [**Added `scheduling.userPlaceholder` option**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/929/commits/ef102f8a65e0833bcfbc5ed827976b1c9721ef82)
- [**Refactor: relax linting and simplify code**](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/929/commits/bf9a72d3f81e4508ad93c3e781171f895672adcd)
---
Read about them in schema.yaml please, whats written here propagates to the *configuration reference* in the guide.
=> [Part 11 of #758]  Added `scheduling.userPlaceholder`

jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
This may be useful for mybinder.org's deployment. I've add a small image locality consideration into the mix for how the user-scheduler decides where a user pod should schedule. It will still prioritize the most requested node though.
In practice I suspect it may be of minor importance, but I imagine that when a few nodes are almost full, it may be that these are both at the same requested resource score (from 0-10), and then image locality can come into play to decide the final reason for scheduling.
---
I've also ensure that the weights are causing the final node-rating to be decided in order from the most important thing to the least important thing. For example, `InterPodAffinityPriority` always wins over `MostRequestedPriority` and that in turn always win over …
=> user-scheduler: image locality priority added

doc/source/authentication.rst
Incorrect location of dnAttribute: 'cn'. 
According to images/hub/jupyterhub_config.py
`set_config_if_not_none(c.LDAPAuthenticator, 'lookup_dn_user_dn_attribute', 'auth.ldap.dn.user.dn-attribute')`
dn-attribute should be under dn.user.
=> small fix in docs - aythentication.rst

doc/source/setup-helm.rst
2.10 has a bug that means the "secure helm" breaks Helm.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/959
=> Change minimum helm version to 2.11.0

doc/source/microsoft/step-zero-azure.rst
I recently received some free Azure credits, thought I'd put it to good use 😊. Looks like AKS is no longer preview.
I've explained each of the changes in the individual commit messages.
~Note: the [secure Helm step](https://zero-to-jupyterhub.readthedocs.io/en/stable/setup-helm.html?highlight=secure%20helm#secure-helm) seemed to break Helm for me (worked fine without) so I'll need to investigate.~ This step fails with Helm 2.10, 2.11 works.
=> Update Azure AKS instructions

jupyterhub/schema.yaml, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/image-credentials-secret.yaml, jupyterhub/templates/singleuser/image-credentials-secret.yaml, jupyterhub/values.yaml
This makes it easier to provide credentials to a private docker repo for the hub image. This is mainly a cut-and-paste from the same feature for the singleuser repos. 
This addresses issue #945
=> Allow for imagePullSecret on hub image

jupyterhub/values.yaml
not a list.
Having a list here results in a (harmless, but misleading) warning when users define prePuller.extraImages:
> `warning: destination for extraImages is a table. Ignoring non-table value []`
=> extraImages is a dict

tools/templates/lint-and-validate.py
rather than showing a `CalledProcessError` traceback, exit with a simple error message
=> better output of lint errors

images/hub/jupyterhub_config.py
After https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/941 some configuration params are not loaded correctly from values.yaml.
=> Some fixes after passthrough values

jupyterhub/values.yaml
There is a predefined type for TLS secrets in k8s, and they can be
created with a kubectl command.
Notice `TYPE` in the example below:
```
$ kubectl get secrets -n jupyterhub
NAME                            TYPE                                  DATA      AGE
autohttps-token-99shm           kubernetes.io/service-account-token   3         1d
default-token-dbj5g             kubernetes.io/service-account-token   3		1d
hub-secret                      Opaque                                4		1d
hub-token-mdhg7                 kubernetes.io/service-account-token   3		1d
kube-lego-account               Opaque                                2		1d
kubelego-tls-proxy-jupyterhub   kubernetes.io/tls                     2		1d
user-scheduler-token-hltcf      kubernetes.io/service-account-token   3		1d …
```
=> Set suitable defaults for provided tls-secret

.circleci/config.yml, doc/doc-requirements.txt, doc/requirements.txt, readthedocs.yml
The following corrects the failing doc build:
- sync naming across files for doc build requirements
- minor edits to circleci.yml
- remove caching as we are only building docs
=> update requirements for docs

README.md
Partially reverts jupyterhub/zero-to-jupyterhub-k8s#977
It works now, with https://docs.readthedocs.io/en/latest/alternate_domains.html.
This gives us direct serving from z2jh.jupyter.org and 
HTTPS. 
Leaves the switch from pointing to latest to stable in.
=> Point links back to z2jh.jupyter.org

.circleci/config.yml
- Use sudo to use the built-in pip to install our packages
to the default store.
- Use a newer image to get a newer pip
- Remove unused bashrc modification
=> Simplify documentation building in CircleCI

images/hub/Dockerfile
The default configuration for the hub uses a sqlite database.
This package adds a commandline utility that makes it easier
to see the database contents when debugging.
=> Add sqlite3 to hub image

jupyterhub/schema.yaml, jupyterhub/templates/ingress.yaml, jupyterhub/values.yaml
GKE's default ingress (ingress-gce) matches path by glob-pattern.
Therefore, path `/` doesn't match `/hub` etc.
To make this to work properly, I need to patch the path to `/*`.
Here, I introduced `pathSuffix` option to support these situation.
=> Support glob-matching ingress

jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
Bumping the API to beta resolved an issue I got during a Helm
upgrade of the chart. I previously ran into the following error:
```
Update Complete. ⎈ Happy Helming!⎈
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "PriorityClass" in version "scheduling.k8s.io/v1alpha1"
```
The API bump resolved it though.
=> Bump PriorityClass k8s API to beta from alpha

doc/source/reference.txt
The configuration reference is not exhaustive, so I added a note to look in the values.yaml file containing all the default values to fill in potential blanks.
=> Add note about config reference docs' limitation

jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
I think not having these annotations for helm to make sure the priority class gets created first is the reason for the recent mybinder.org deploy to fail: https://travis-ci.org/jupyterhub/mybinder.org-deploy/builds/458381755
=> Make sure priority class is created before other resources

jupyterhub/schema.yaml, jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml, jupyterhub/values.yaml
Adds configuration options nested under `scheduling.podPriority` and some documentation about it.
Made me realize #1035 
Closes #1032
=> Pod priority configuration

jupyterhub/schema.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
`.Values.ingress.tls` should default to a `[]` instead of `{}` to avoid:
```
2018/11/25 21:56:36 warning: cannot overwrite table with non table for tls (map[])
```
... when the following valid configuration is provided:
```yaml
ingress:
tls:
- secretName: hub-neurips-mybinder-org-tls
hosts:
- hub.neurips.mybinder.org
```
=> Fix ingress.tls's default value

images/hub/Dockerfile, images/hub/requirements.txt
Try to install from git if JUPYTERHUB_VERSION starts with git, such as:
git+https://github.com/jupyterhub/jupyterhub.git@bbc2847530ccdb0f40a48f8e561415ea808a6561
Also switch to python3-pycurl so libcurl4-openssl-dev won't conflict with npm, which
is required by jupyterhub from git for lessc to work.
=> Make it easier to build hub image with git commit hash.

images/hub/jupyterhub_config.py, images/hub/requirements.txt, jupyterhub/templates/image-puller/_daemonset-helper.yaml
- use KubeSpawner.image instead of deprecated .image_spec
- fix pre-puller with profiles when images are not defined
I didn't add backward-compatibility support for `.image_spec` in profileList prepuller since we haven't made a release with support for profileList yet and the consequence is only that profile images won't be pre-pulled if they use the deprecated name. They will still work.
=> kubespawner 0.10

images/hub/requirements.txt
fixes deprecation of hub_connect_ip, which caused launch failures in #1053, #1055
=> kubespawner 0.10.1

jupyterhub/schema.yaml, jupyterhub/templates/hub/service.yaml, jupyterhub/values.yaml
prometheus annotations go on the service, not the pod
adds hub.service.annotations field and enables prometheus annotations by default
=> fix prometheus annotations on the hub service

jupyterhub/templates/ingress.yaml
since wildcards can start with `*` which is inerpreted as a yaml anchor
may close #1058
=> quote hosts in ingress rules

doc/source/google/step-zero-gcp.rst
- The following syntax doesn't work anywhere other than
the google cloud console:
A=5
echo $A
If you want it to, it should be `export A=5`. However,
it is only useful if we re-use them later - but we do
not need to, and we don't. Having them on a separate line
makes it easier to edit rather than having them in the
middle of a command - so I've moved them all towards the
end of the command.
- ZONE is only ever required when you create your cluster,
so don't explicitly set the zone as a requirement to create
cluster.
=> Simplify steps for setting up Kubernetes cluster

doc/source/setup-helm.rst
- Reword note about RBAC to be clearer. We might consider moving
this away in the future, since most clusters do have RBAC enabled.
We set this up when Azure didn't have RBAC enabled by
default, but that's no longer true
- Move 'securing helm' up, since we want people to do that
before verifying
- Remove note about upgrading in 'verify'. It was confusing to
folks, most people never need it, and 'verify' is the
wrong place for it anyway.
=> Simplify helm setup documentation

doc/source/google/step-zero-gcp.rst
This is only needed if you are setting up multiple node
pools - which isn't a common case. Even then, you can create
an additional nodepool for your core then - and you most likely
want to, since it should be sized differently. Removing it
makes the initial setup page fully explainable.
=> Remove setting node labels in gcloud container create

doc/source/google/step-zero-gcp.rst
I *think* all these work in the regular gcloud command,
without needing the beta version
=> Remove 'beta' requirement from gcloud command

jupyterhub/templates/image-puller/_daemonset-helper.yaml
We forgot to check if the parent value was defined at one point. The go
templating that Helm relies on does not allow for a nice way to do this
with `and` functions as I understand it, see:
https://github.com/helm/helm/issues/3708
So, I opted for this functional solution even though it isnt very
elegant.
Closes #1097
=> Fix regarding image-puller & profileList - #1097

doc/source/setup-jupyterhub.rst, doc/source/troubleshooting.rst, doc/source/upgrading.md
Once https://github.com/jupyterhub/helm-chart/pull/94 lands there will be a nice little table with jupyterhub versions listed per helm chart...this adds in links to that table in a few places in Z2JH where we think people might be looking.
=> adding information about helm chart versions etc

doc/source/authentication.rst
Documentation says to use `org_whitelist` key to use:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8c09a0c0907e4beebb3a4f79e75f730df395ad8b/doc/source/authentication.rst#L62-L67
but according to the config it is `orgWhitelist`:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8c09a0c0907e4beebb3a4f79e75f730df395ad8b/images/hub/jupyterhub_config.py#L264-L271
=> fix organisation whitelist config in documentation

jupyterhub/templates/hub/service.yaml, jupyterhub/values.yaml
If jupyterhub is run under a prefix e.g. `hub.baseUrl: /jupyter` this prefix must be included in the Prometheus scrape path. Since Values can't be interpolated I've added a new value `hub.service.annotatePrometheus`. An alternative would be to not add a new value and to unconditionally include the prometheus annotations.
=> Hub Prometheus annotations needs to include baseUrl

doc/source/google/step-zero-gcp.rst
* Typo
* move available regions list to the right bullet point describing `--zone`
=> Minor fixes in step-zero-gcp.rst

doc/source/optimization.md
Alternatively, rather than remove "suitable", replace it with "service" ?
Or remove the last sentence altogether and link "user pods to shut down" to the culler.
=> Remove out-of-order adjective.

README.md
The information about the latest version dev version from the chart repo
was not easily accessible without some additional sorting. Therefore I
made a commit to helm-chart's gh-pages to add a info.json file that
contained exactly the information we require for these badges.
```sh
curl https://jupyterhub.github.io/helm-chart/info.json
```
```json
{
"jupyterhub": {
"latest": "0.8-580f46e",
"stable": "0.7.0"
},
"binderhub": {
"latest": "0.2.0-276d090",
"stable": ""
}
}
```
=> Fix wrong dev version in README badges

dev-requirements.txt
no need to pin some super-stable packages down. Resolves security alert on the repo for out-of-date requests.
=> unpin some dev-requirements

dev-requirements.txt
will add chart version as prefix to image tags (0.8-abc123 instead of just abc123) making it easier to see which image builds go with which chart version
=> use chartpress 0.3

doc/source/security.md
It seem that AKS does support RBAC now.
https://docs.microsoft.com/en-us/azure/aks/faq#does-aks-support-kubernetes-role-based-access-control-rbac
=> Correct outdated warning about AKS

jupyterhub/schema.yaml
Add a section to the doc about the Pod Disruption Budget for the hub and proxy pods.
Would it make sense to also add default values to show that it is enabled by default?
=> Add pdb section to the schema for hub and proxy

images/hub/jupyterhub_config.py
The bugfix relates to using config like:
```yaml
auth:
type: X # where X is cilogin, gitlab, mediawiki or globus
X:
clientId: something... # not utilized pre-fix
clientSecret: something... # not utilized pre-fix
```
---
Closes one bug described in #1167
=> Fix bug affecting config of authenticators

images/hub/jupyterhub_config.py
This single commit PR adds the ability to configure new options introduced with `oauthenticator==0.8.1`, and the config example below is how I understand that a working config would look.
---
The following is now a valid configuration for oauthenticator 0.8.1 I
think:
```yaml
hub:
extraEnv:
GITLAB_URL: https://my-gitlab-instance.example.com
auth:
type: gitlab
gitlab:
clientId: <client id>
clientSecret: <client secret>
callbackUrl: <callback url>
gitlabGroupWhitelist:
- "groupName1"
- "groupName2"
gitlabProjectIdWhitelist:
- "projectId1"
- "projectId2"
```
=> Add missing auth options for gitlab

doc/source/advanced.md, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
If the image pull policy is left out, it will act as "IfNotPresent"
almost always. The difference is that the default is to make an
adjustment if the tag is "latest", then it will become "Always".
So, hardcoding it makes little sense, and this would help us if we have
a hook-image-puller and we make an upgrade using an image with "latest" tag because we are actively developing the image... Hmmm...
Well, perhaps by submitting this commit in a PR, we can conclude whats
best to do about it.
=> MRG after 0.8.0 - Tune image-pullers pull policies

doc/source/user-environment.rst
Fixes a small typo on the User Environment page
=> Fixed typo in user-environment.rst

doc/source/setup-helm.rst
This PR proposes some changes to the documentation surrounding Helm. These are some things I've learned while deploying my own JupyterHub/BinderHub and I thought it would be cool to make these concepts more explicit in the documentation.
Additions are:
* A short description of what a Helm Chart is and does when it is applied
* Making explicit which step it is that allows `helm` commands executed locally to affect a remote cluster without an ssh
* Adding a short explanation as to why the security patch for `tiller` is required, still pointing to the awesome blog post
will fix #1179
=> Docs update: Securing Helm

images/hub/Dockerfile
Builds `pycurl` as a requirement with `openssl` backend
Resolves #1102
=> Switch to openssl backend for pycurl

doc/source/user-environment.rst
The --yes install doesn't seem to exist : https://pip.pypa.io/en/stable/reference/pip_install/
=> Remove --yes option in pip install

jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
If we used the blank value as we had before, Helm would fail to override
it with an object and say:
```
2019/04/03 21:38:31 Warning: Merging destination map for chart 'jupyterhub'. The destination item 'lifecycleHooks' is a table and ignoring the source 'lifecycleHooks' as it has a non-table value of: <nil>
```
=> Fix the default value of lifecycleHooks

jupyterhub/templates/proxy/autohttps/configmap-nginx.yaml, jupyterhub/values.yaml
Currently, if you have a JupyterHub at datahub.berkeley.edu with
HTTPS, you can *not* have a grafana.datahub.berkeley.edu without
HTTPS. This is because the default HSTS is set to 'includeSubdomains',
which means any subdomain must also enforce HTTPS.
This is a bit of an overreach, since the hub doesn't control any
other subdomain. This sets the default to be a bit more relaxed,
and allows people to turn it on if needed.
=> Relax HSTS requirement on subdomains

jupyterhub/templates/NOTES.txt
Ready is a PodCondition type, but status returned from kubectl get pods is the phase, which should be Running.
=> Updated notes, pod status to Running

doc/source/authentication.rst
Had to specify an https callback URL for a keycloak OIDC auth, but didn't find how to do so in the docs. Found it discussed in the issues section with two options:
- OAUTH_CALLBACK_URL environment variables.
- oauth_callback_url in auth.custom.config.
=> Added OAuth callback URL to keycloak OIDC example

.github/ISSUE_TEMPLATE.md
See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1230#issuecomment-482305040
> Can move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the different discussion places and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)
I thought it'd be useful to mention Discourse in the issue template.
=> Suggest Discourse in issue template

doc/source/amazon/step-zero-aws.rst
Mostly removes a lot of extraneous whitespace. The only "substantial" change is here:
=> Adjusts whitespace for a code block in AWS instructions.

jupyterhub/templates/hub/deployment.yaml
Without this the istio-init initContainer fails.
This is a similar issue as existed in this chart: https://github.com/helm/charts/commit/4daf2d02ed2532572872e8cf6eb4915e5a8af53a
=> Supply runAsUser at the container level

jupyterhub/values.yaml
Could help us get #1004 merged. I created the PR to trigger our CI pipeline, but I'm not able to conclude if it is safe to merge.
DockerHub: https://hub.docker.com/r/jupyterhub/configurable-http-proxy/tags
Changelog: https://github.com/jupyterhub/configurable-http-proxy/blob/master/CHANGELOG.md
=> Bump CHP image to 4.1.0 from 3.0.0

jupyterhub/Chart.yaml, tests/conftest.py, tests/test_spawn.py
instead of hardcoding the value in the test
=> test appVersion in Chart.yaml

jupyterhub/values.yaml
This value was previously quoted with ", but when `chartpress` parses this
YAML and writes it back in our CI steps, the following change arise and is
written to the logs which distracted me.
```diff
-    hstsIncludeSubdomains: "false"
+    hstsIncludeSubdomains: 'false'
```
So, by either making this value a boolean or a string with single quote
we get rid of this log entry coming from a `git diff`. I went with
single quotes for a minimalistic change.
=> Clean up a line in the CI logs

images/hub/Dockerfile
When debugging hub network issues, it is handy to have
the following tools:
1. curl - Validate HTTP / HTTPS endpoints
2. dig - Validate DNS
They don't increase the image size too much. This commit
adds them both
=> hub: Add useful debugging tools to hub image

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml
We never need anything to become the root user inside
the hub / proxy containers while they are running.
This removes the ability from them, making it harder
for any exploit in the hub / proxy to be used to gain
root on the underlying machine
=> Disable becoming root inside hub and proxy containers

doc/source/optimization.md, jupyterhub/values.yaml
Along with #1271 and #1272 I figure its time for this as well, which is very useful for autoscaling to function smoothly.
=> Enable continuous prePuller by default

doc/source/google/step-zero-gcp.rst
I followed:
https://zero-to-jupyterhub.readthedocs.io/en/latest/google/step-zero-gcp.html
for the first time today, and found some of the instructions to be incorrect. First, when listing the running nodes, there are actually two nodes (since ``--num-nodes`` is set to 2 in the example). Second, the user pool command is missing the ``zone`` and ``cluster`` options (without these, I am getting errors).
=> Fix a couple of mistakes in Google Kubernetes instructions

images/hub/Dockerfile
workaround for issue https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1794589
which prevents the install of `npm` due to conflict with `libssl-dev`
Resolves #1293
=> Unbreak git build

images/hub/requirements.txt
It would be convenient to have this authenticator, which is nice model for
JupyterHubs used at workshops, available in the hub image by default.
If this change is acceptable, I would be happy to add mention of this option to
the documentation in this PR.
=> Include jupyter-firstuseauthenticator.

jupyterhub/values.yaml
I think we've learned through testing of 0.8 that the user scheduler is a success and we can turn it on by default for users with the next release
=> enable user scheduler by default

doc/source/microsoft/step-zero-azure-autoscale.rst
The command was incorrect and produced an error:
`
az feature --name VMSSPreview --namespace Microsoft.ContainerService
az feature: 'VMSSPreview' is not in the 'az feature' command group. See 'az feature --help'.
`
The correct command should be 
`
az feature register --name VMSSPreview --namespace Microsoft.ContainerService
`
see MS docs: https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler
=>  Fix azure cli VMSSPreview feature register command 

images/hub/requirements.txt
tmpauthenticator is broken in the current devel `0.9-7aaa255`.
See https://github.com/jupyterhub/tmpauthenticator/pull/18
=> tmpauthenticator 0.6 needed for jupyterhub 1.0

doc/source/user-environment.rst
Adds some information about using lifecycle_hooks in kubespawner_override as mentioned by @consideRatio in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1242
(Would have saved me an hour of poking around!)
=> add explanation for lifecycle_hooks in kubespawner_override

images/hub/Dockerfile
Took me awhile to debug this one. Dockerfile doesn't actually point to JH 1.0 in #1263 @minrk
Perhaps it'd be better to remove the arg from the ci system and rely on the dockerfile to keep this from happening again?
=> Update Dockerfile to JH 1.0

doc/source/microsoft/step-zero-azure-autoscale.rst, doc/source/microsoft/step-zero-azure.rst
This PR updates the Azure setup article to use the current full name of AKS, Azure Kubernetes Service.
=> Changing Azure Container Service to Azure Kubernetes Service

images/hub/requirements.txt
https://github.com/benfred/py-spy is a sampling profiler for Python
that works really solidly with minimum fuss, and has been extremely
helpful in debugging issues. It's also very useful in doing performance
analysis. Having this be present in the hub image by default will
make it easier for everyone to create profiles of the hub process
at loads they are having trouble with, and share it with the community
to see what is up.
=> Add py-spy to hub image

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml
I configured liveness/readinessProbe for both proxy and hub.
With this, they will be more robust against failures.
In addition to that, when deployed on GKE with Ingress, health check is configured properly (GKE Ingress's health check is configured automatically by following readinessProbe, or against `/` if not set).
- https://github.com/jupyterhub/configurable-http-proxy/pull/181
- https://github.com/jupyterhub/jupyterhub/pull/2257
⚠️  I believe this works, but not tested yet. I shall take time soon.
=> Configure liveness/readinessProbe

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml
Reverts jupyterhub/zero-to-jupyterhub-k8s#1004
My hub and proxy pod wasn't entering a Ready state after this PR was merged by me. So I'll investigate things further but for now I figure I'll revert the PR so it does not cause disruptions for others like me.
```
Events:
Type     Reason     Age                From                                         Message
----     ------     ----               ----                                         -------
Normal   Scheduled  78s                default-scheduler                            Successfully assigned jupyterhub/proxy-7d4dcc5c64-pqv9w to gke-ds-platform-core-4d566784-54l4
Normal   Pulled     76s                kubelet, gke-ds-platform-core-4d566784-54l4  Container image "jupyterhub/configurable-http-proxy:4.1.0" already present on …
```
=> Revert "Configure liveness/readinessProbe"

doc/source/user-resources.rst
This adds brief instructions to the docs for how to:
* allocate GPUs to users
* increase the shared memory (SHM) allocation for users, which is beneficial for deep learning workloads and even required for functions like PyTorch's DataLoader to run
I noticed #994, but I also think it's beneficial to start adding basic information and instructions into the documentation so users can have something to refer to as a starting point.
Any feedback or comments appreciated!
=> Instructions for adding GPUs and increasing shared memory

doc/source/user-resources.rst
This is a follow up to PR #1358 to fix a formatting issue with the links so that they will render properly. Apologies for the mistake in the previous PR.
=> Fixed formatting error in links

jupyterhub/templates/proxy/deployment.yaml
Using jupyterhub/configurable-http-proxy#187 `--redirect-to` to correctly redirect http to https with manual certificates.
=> Use 443 as https port or redirection. FIX #806

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml
Manages parts of #1357 and lands #1004 finally that I merged and then reverted in #1356.
=> [MRG] Readiness and Liveness probes re-added

images/hub/jupyterhub_config.py
> You'll shoot your eye out, kid
This is a trivial fix to "Dockerfile" misspelling.
=> Fix typo in jupyterhub_config.py comment

jupyterhub/templates/proxy/deployment.yaml
When left on http and http to https redirection is configured the probes may be redirected to the wrong port.
=> Proxy deployment: Change probes to https port

jupyterhub/templates/hub/netpol.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/singleuser/netpol.yaml, jupyterhub/values.yaml
If you have a prometheus server in a different namespace,
explicit 'from' stanzas are needed to make sure it can
have access to your hub and user pods.
This change allows individual administrators to make
these changes.
=> Allow adding additional ingress rules in network policy

doc/source/user-environment.rst
I've added an example that I think would be useful in the documentation in the Customizing User  Environment section. It also shows how multiple commands can be used with the hook.
=> Added example for populating notebook user home directory

.gitignore
These files where generated when installing the venv and should probably be ignored by git.
=> Ignore venv files

images/hub/jupyterhub_config.py, jupyterhub/values.yaml
Added more configurable options into helm chart and updated jupyterhub_config.py for hub image accordingly.
=> more configurable options in helm chart

jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
Using a rolling update by default on the proxy pod is a mistake by us,
because of the JupyterHub / CHP proxy interaction. JupyterHub assumes in
check_routes / add_route etc to be speaking to one specific CHP proxy
server, but there can be different ones responding if we make an upgrade
and the proxy pod is making a rolling upgrade.
For example, consider a hub pod making a recreate upgrade, and a proxy
pod makinga rolling upgrade. The new hub pod could for example get ready
before the proxy pod and start speaking with the old proxy pod and later
at a crucial point start speaking with the new pod. If you switch to
speaking with the new pod at the wrong time, you may end up with failure
to get responses from user pods that are verified to be around, and then
they are deleted.
So, this commit …
=> Recreate as CHP proxy pod's deployment strategy

jupyterhub/values.yaml
Upgrades from previous state to this would fail without this fix of the issue caused by removing the fix in this PR: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1401
=> Bugfix for proxy upgrade strategy pr #1401

jupyterhub/templates/proxy/deployment.yaml
configurable-http-proxy redirects to '--port' which in this case is 8443 and unresolvable outside of the cluster.
The master branch now uses version 4.1.0 of configurable-http-proxy which added '--redirect-to' to solve this problem.
=> Make proxy redirect to 443 instead of 8443

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/values.yaml
This enables using pull secrets in a way that is more consistent with other helm charts.
=> Added the ability to use an existing/shared imge pull secret

.travis.yml, ci/publish, dev-requirements.txt
TravisCI would make two builds if a commit and a tag referencing this
commit was pushed. This could lead to duplication of chart build and
publishing jobs. So, I disabled the tag triggered builds before to avoid
this, in case we ended up with duplicated entries or failure due to
existing entries etc.
In this PR, with chartpress 0.4.2 and the --long flag, we can let both
bulds finish. There are some key benefits.
1. We can now push a tag retrospectively now to trigger a build.
2. We avoid a failure to build a tag because it was pushed not as the
HEAD commit but some steps down the history.
3. We can still build on all pushed commits to master for dev releases.
=> Support CD with git tags

images/hub/requirements.txt
It seems the V1PodSpec in 8.0 does not support enableServiceLinks in case we want to disable it.
=> Bump python-kubernetes to 9.0.*

.travis.yml, ci/common
Helm 2.15.0 stopped using extensions/v1beta1 for tiller, which was
required for installation on k8s 1.16 as we have testing for. So now we
don't have to maintain a separate Helm version for k8s 1.16 tests.
=> Use helm 2.15.1

doc/source/index.rst
Just caught a really small typo in the docs.
=> Fix typo in home page of docs

doc/source/authentication.rst
As I mentioned in #1449 links for OpenID Connect in authentication documents were broken. Replaced the links in this PR.
=> Replaced broken links in authentication document #1449

jupyterhub/schema.yaml
A recent PR (#1426) allowed for existing kubernetes secrets to be used for image pull of the `hub` and `singleuser` images. This PR adds the changes to the schema so they can also carry over into the documentation.
=> Added existing pull secrets changes from PR #1426 to schema

jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/templates/hub/deployment.yaml
Path `/usr/local/lib/python3.6/dist-packages` binds chart to Ubuntu-like distribution and Python 3.6 docker images.
Currently, configuration script is placed in `/etc/jupyterhub/jupyterhub_config.py` and JupyterHub execs it.
```
jupyterhub
--config /etc/jupyterhub/jupyterhub_config.py
...
```
Thus, it is not enough that `z2jh.py` is in `/etc/jupyterhub/` as it is not from where the python config is executed. Thus, the optimal solution could be to add the script to `PYTHONPATH` to container spec.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1464
@consideRatio @mkjpryor-stfc
=> [1464] Move z2jh.py to python and distribution agnostic path

jupyterhub/values.yaml
This will make the proxy pod quickly terminate instead of taking full 30
seconds to terminate, and that in turn allows for the hub pod to not
crash so much on upgrades as it requires the proxy pod to upgrade first
by shutting down and starting up.
Changelog: https://github.com/jupyterhub/configurable-http-proxy/blob/master/CHANGELOG.md#42---2019-11-14
---
Solves the part regarding the proxy pod for #1476.
=> Bump CHP to 4.2.0 - we get quicker chart upgrades now

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1479
=> [1479 ] Make probes in hub configurable

.travis.yml
When we use the lint and validate script, we speak with a server that
has various schema. We do this too much if we do it for more than three
versions it seems, so let's settle for validating the schema against
three kubernetes versions.
=> Avoid rate limiting for k8s resource validation

doc/source/administrator/architecture.rst
Relative path was wrong, one more level needed. This should fix the page https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/architecture.html and show the image correctly.
=> Fix broken link in architecture.rst

.travis.yml, dev, images/hub/requirements.txt, jupyterhub/values.yaml
1. **Make kubespawner function for k8s 1.16**
2. **Bump kube-scheduler**
If I don't bump kube-scheduler, I note that the scheduler stop working in k8s 1.16. I'm not sure why. Anyhow, I bump various versions at the moment to see what works and doesn't work. We are bumping from kube-scheduler v1.11.2 in use by user-scheduler, which is just a configured kube-scheduler. [These are the available images](gcr.io/google_containers/kube-scheduler-amd64).
3. **Bump kubespawner**
Perhaps there are more things needed to be done, but I think all known issues are now addressed.
Closes #1444 entirely, see: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1444#issuecomment-554631155.
=> k8s 1.16 compability - bump kube-scheduler, kubespawner, kubernetes python client

RELEASE.md, images/hub/requirements.txt, jupyterhub/values.yaml
Making a z2jh release is sometimes motivated by bumping dependencies etc. In this PR I add an overview about the relevant dependencies within RELEASE.md and provide lots of relevant links from the hub image's requirements.txt file to facilitate version bumping.
=> Update hub image dependencies and RELEASE.md regarding dependencies

doc/source/customizing/user-management.md
The current link directs to the resource which doesn't exist. So changed it to point to the correct link (https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html)
Link to issue #1511
=> DOC:fixing authentication link in user customization guide

jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
Inspecting the user-schedule-xxxx pod log:
error binding volumes: persistentvolumeclaims "claim-test" is forbidden: User "system:serviceaccount:ns:user-scheduler" cannot update resource "persistentvolumeclaims" in API group "" in the namespace "ns"
I fix it by creating a new roleBinding to let user-scheduler update the volume claim:
=> Fixing #1300 User-scheduler doesn't work with rancher/local-path-provisioner

dev-requirements.txt, images/hub/requirements.txt
Fixes #1501, again.
- By specifying jupyterhub-kubespawner==0.11 we actually pinned it to 0.11.0 where I assumed it would be considered to mean 0.11.* as conda behaves. That was a faulty assumption that is now corrected.
- Bumping chartpress just to stay up to date.
- Disabling ltiauthenticator because it is incompatible with current JupyterHub that depends on oauthlib>=3.0 while ltiauthenticator requires 0.2 and crashes on >=0.3. I may have fixed that upstream in ltiauthenticator with some currently unmerged PRs. See https://github.com/jupyterhub/ltiauthenticator/pulls and https://github.com/jupyterhub/ltiauthenticator/pull/24 specifically.
=> Fix hub image dependency versions, disable ltiauthenticator, use chartpress==0.5.0

images/hub/requirements.txt
ltiauthenticator==0.3 had a dependency requirement, oauthlib==2.*, that conflicted with JupyterHub's depdencny requirement, oauthlib>=3.0. This is now fixed in ltiauthenticator 0.4.0.
=> Re-add ltiauthenticator 0.4.0 to hub image

chartpress.yaml
I am not sure if it makes sense to update JupyterHub version now, since I know you are working on beta version already. I am just looking forward to use some new features without using custom a docker image in the chart :)
=> update jupyterhub version

CONTRIBUTING.md
Looks like the Helm docs have been consolidated on [new website](https://helm.sh)
=> fix link to Helm chart best practices

jupyterhub/templates/proxy/service.yaml
In kubernetes 1.14 if the type is LoadBalancer and the backend has any SSL configuration it will configure an https health check, but it will use the first port which in this case is http and will fail.  Putting the possible https port first fixes this issue.
https://github.com/kubernetes/kubernetes/issues/83070
=> due to a kubernetes change in 1.14 the ssl service must come first

jupyterhub/templates/proxy/service.yaml
The specification for proxy-public disables both HTTPS and HTTP ports if HTTPS is disabled, making it impossible to use an unsecured proxy (e.g. if you're moving to cert-manager)
=> move endif to only bracket https options

doc/source/microsoft/step-zero-azure-autoscale.rst, doc/source/microsoft/step-zero-azure.rst
This PR updates the Step Zero docs for Azure k8s to create a virtual network into which the cluster is deployed. This is because k8s does not come with a network controller by default and so the `networkpolicy` resources installed by a helm chart will not be obeyed.
fixes #1526
=> [MRG] Update step zero for Azure docs with commands to setup an VNet and network policy

dev-requirements.txt
Ping @scottyhq @betatim, this is relevant for Pangeo and BinderHub. When we make releases with chartpress 0.4.*-0.5.* we create dev releases of charts with an invalid semver version. This is resolved in 0.6.0, and that is important to have Helm 3 compatibility.
Here is [the chartpress chagelog](https://github.com/jupyterhub/chartpress/blob/master/CHANGELOG.md#060---2020-01-12).
=> Bump chartpress for Helm 3 compatible dev releases

doc/source/microsoft/step-zero-azure-autoscale.rst
Should fix this warning in the CircleCI docs build:
`/home/circleci/project/doc/source/microsoft/step-zero-azure-autoscale.rst:4: WARNING: duplicate label microsoft-azure, other instance in /home/circleci/project/doc/source/microsoft/step-zero-azure.rst`
=> Fix duplicate docs label

doc/source/administrator/security.md
I added documentation explaining how to configure https using a secret resource.
Storing private keys in a secret resource is better practice than stroing secret information like that in a plain text file.
=> Added documentation of secret https mode

jupyterhub/templates/proxy/autohttps/configmap.yaml
Based on
https://github.com/yuvipanda/zero-to-jupyterhub-k8s/commit/d5892ab50c2bfce1138771bf6b2eca6fef60556c,
this directive is only useful when traefik is *behind* a TLS
termination proxy.
=> Remove unneeded directive in traefik config

doc/source/amazon/step-zero-aws.rst
Still not sure I caught everything, but it does fix the single quote problem on step 8
=> Trying to clean up formatting

images/hub/requirements.txt
remove verbose comments that make it harder to see what's in the hub image and update dependencies
pypi links are always pypi.org/project/$name so duplicating that info in links doesn't make them easier to find
=> simplify hub-requirements

jupyterhub/files/hub/cull_idle_servers.py, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/values.yaml
In a setup like a BinderHub with auth I enable the named server option to allow users to launch the same repository multiple times in an attempt to keep the experience as much like mybinder.org as possible. The reason the bhub has auth is because it has access to private repositories.
This PR adds a flag to the culler to allow it to remove a named server when it culls the server. With the old culler you have to enable culling of users and wait roughly two culling periods before a user who has maxed out their number of allowed named servers can start a new server again. (Or you have to teach users about the control panel and deleting servers there manually.)
I don't really want to cull users as that means you have to click the login button again.
What do people think? What is missing from …
=> [MRG] Add option to remove named server when culling

images/hub/requirements.txt
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1561
Significant changes (taken from https://github.com/jupyterhub/ldapauthenticator/blob/1.3.0/CHANGELOG.md):
-    Avoid binding the connection twice
-    Gracefully handle username lookups with list return values
-    Empty DN templates are now ignored, search_filter and allowed_groups are no longer mutually exclusive*.
-    Allow authentication with empty bind_dn_template when using lookup_dn
-    Ignore username returned by resolve_username - use_lookup_dn_username configuration option added
-    Lookup additional LDAP user info - user_info_attributes is now saved in auth_state for a valid user.
=> jupyterhub-ldapauthenticator==1.3

.travis.yml, ci/common, dev, doc/source/setup-jupyterhub/setup-helm.rst, doc/source/setup-jupyterhub/setup-helm3.rst
Adds Helm 3 to the Travis matrix.
Adds a Helm 3 preview doc.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1532
=> Helm 3 preview

README.md
This makes the contributing guide one-click away from possible contributors :rocket:
This is how it would look like:
[![Contribute](https://img.shields.io/badge/I_want_to_contribute!-grey?logo=jupyter)](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CONTRIBUTING.md)
=> Add contributor badge

doc/source/setup-jupyterhub/setup-helm.rst
Hi, I have just seen that mybinder also had problem with helm history and remembered the issue related to that I opened. So I just want to make the first step and add the  `--history-max 100` setting in the documentation of helm setup. Please feel free to add more, I am not comfortable with my wording and it usually takes more time for me than other people :)
closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1339
=> init helm and tiller with history-max settings

jupyterhub/values.yaml
A security fix in the configurable-http-proxy image caused by having npm
installed.
ref: https://github.com/jupyterhub/configurable-http-proxy/pull/226
=> Bump configurable-http-proxy image

images/singleuser-sample/Dockerfile
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1549 bumps jupyter/base-notebook:d4e60350af15 which has jhub 1.0.0 installed (https://hub.docker.com/r/jupyter/base-notebook/tags/?page=2), but because in Dockerfile `pip install --upgrade jupyterhub` is executed, at the end image has jhub 1.1.0.
Since https://github.com/jupyter/docker-stacks/issues/992 is fixed, we can use the latest jupyter/base-notebook and dont have to manually upgrade jhub anymore.
=> fix: Bump to base-notebook with JH 1.1.0 etc

.circleci/config.yml, doc/doc-requirements.txt, doc/environment.yml, doc/source/administrator/optimization.md, doc/source/amazon/efs_storage.rst, doc/source/repo2docker.rst, doc/source/setup-jupyterhub/setup-helm.rst, doc/source/setup-jupyterhub/setup-helm3.rst, doc/source/setup-jupyterhub/setup-jupyterhub.rst
As suggested in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1601#issuecomment-602637363 changes Sphinx warnings to errors
1. First commit adds `-W` to convert warnings to errors, circle-ci fails.
2. Second commit fixes the errors detected in (1), circle-ci passes. Note the broken cross references from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1601 **were not detected**
3. Third commit fixes the broken internal links
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1601
Updated:
- Bump sphinx so `--keep-going` flag can be used to show all doc errors
=> [MRG] Sphinx: warnings are errors

.travis.yml
Related to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/724
Runs the Sphinx linkcheck in Travis, currently allowed to fail.
Although this means the docs are built twice (in Circle CI and Travis) I think it's clearer to have all the build statuses in one place, and the overhead of building the docs is small compared to that of running the deployment tests.
=> [MRG] sphinx: linkcheck in travis (allowed to fail)

.circleci/config.yml, doc/source/customizing/user-environment.rst, doc/source/reference/glossary.rst, doc/source/setup-jupyterhub/setup-jupyterhub.rst
We make warnings into errors on circle-ci's test of the docs, and when sphinx was bumped a new kind of warning about case mismatched referenced arrived.
I fixed the case mismatches, and made CircleCI less harsh, because we are already checking for errors properly in TravisCI and CircleCI's purpose as I understand it in this repo is to provide us with previews of built documentation.
=> CI: fix sphinx warnings turned into errors

dev-config.yaml
Whenever it works to use a port number that indicates what it is, I appreciate it. This does that for the dev-config, not relevant for production use.
=> DX: more recognizable port numbers

jupyterhub/values.yaml
I was working a lot against treafik in a PR to come, and I bumped it to know that I was working against the latest version of documentation. It seems to work fine even though we can't test it in our CI setup - yet!
=> Dep: Bump deploy/autohttps's traefik to v2.2

jupyterhub/templates/proxy/autohttps/deployment.yaml
When the autohttps deployment is updating, it keeps existing connections 
open for a while before it shuts down, but it closes itself for new 
connections.
After it has closed itself for new connections, it is still considered 
ready by the service that delegates traffic, so that makes the pod 
continue to receive traffic that will crash.
With this change, it will stop receiving traffic, which is preferred as 
it isn't actually doing its job to receive it as it should any more at 
this stage.
=> Feat: autohttps readinessProbe for quicker shutdowns

jupyterhub/templates/proxy/service.yaml
Using `with` has become common enough that all users of helm templates 
needs to know how it works. It will not render anything if the value is 
falsy, but if it is truthy it will make the value accessible as `.` 
instead of needing to rewrite the same long reference again.
=> DX: refactor helm template

doc/source/customizing/user-storage.md
The size of the PVC request for each user belongs to the `singleuser`
object, not the root configuration.
=> Fix user storage customization variable

jupyterhub/files/hub/cull_idle_servers.py, jupyterhub/files/hub/jupyterhub_config.py
I am currently deploying Z2JH on an IPv6-only Kubernetes cluster.
There are a bunch of changes lined up for being upstreamed.
This is the first an easiest one.
=> Do not hardcode IPv4 localhost address for IPv6 compatibility

jupyterhub/schema.yaml
The Reference documentation page is generated from the JupyterHub
schema. Fix the broken links[1] there and enjoy the propagation to
the documentation.
[1]: Turn relative links into absolute links to the stable
documentation page on ReadTheDocs. This mimicks how the other
links are set in the schema.
=> Fix broken links in the Reference documentation

jupyterhub/templates/proxy/autohttps/_configmap-dynamic.yaml, jupyterhub/templates/proxy/autohttps/_configmap-traefik.yaml, jupyterhub/templates/proxy/autohttps/configmap.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/values.yaml
The autohttps deployment run Traefik, and we are in this PR switching from configuring it with YAML instead of TOML, for two reasons.
1. It avoids introducing TOML as yet another markup language to understand to maintain this repo.
2. Yaml is supported better by helm (`fromYaml` exists, but not `fromToml`), and I want to use this.
The configuration options `proxy.traefik.extraStaticConfig` and `.extraDynamicConfig` are added to allow a chart user to add generic configuration into Traefik's config. By doing so, we setup for a more sustainable experience that doesn't require the Chart maintainers to add more and more templating options, while also allowing the chart user to configure whatever is of relevance.
The end goal of this work is to help for example BinderHub hook into our automatic …
=> autohttps: traefik's config now configurable and in YAML

doc/source/administrator/security.md, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/netpol.yaml, jupyterhub/templates/hub/service.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/autohttps/service.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/templates/singleuser/netpol.yaml
- Port definitions `protocol: TCP` is no longer explicitly set
- Ports are now referenced by name from services and network policy ingress
- The deploy/hub and deploy/proxy pods got some ports renamed:
- hub -> http
- proxy-public -> http
- proxy-https -> https
- I removed legacy ports allowed by the deploy/proxy pod's network policy for kube-lego and nginx /health. They could not be accessed anyhow as they were not exposed by the pod.
This should not influence anything.
=> Refactor: reference ports by name instead of repeating the number

jupyterhub/schema.yaml
https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html#proxy-service-type just says `See hub.service.type.`
It's not identical though since the default is different.
=> proxy.service.type: Default is different from hub.service.type

jupyterhub/templates/proxy/deployment.yaml
The `configurable-http-proxy` relies on the `http` module which in turn relies on the `server` module:
https://nodejs.org/api/net.html#net_server_listen
We dont make use of the `ipv6Only` option. Therefore we can safely listen on `::` for dual stack support.
=> Bind proxy on IPv4 and IPv6 for dual stack support

doc/doc-requirements.txt, doc/source/administrator/advanced.md, doc/source/administrator/optimization.md, doc/source/conf.py, doc/source/customizing/user-management.md, doc/source/customizing/user-storage.md, doc/source/reference/reference.txt
Over the last few months, we have been launching a few Sphinx projects that support the [new jupyterbook version](beta.jupyterbook.org). One that I am really excited about is a first-class markdown parser for Sphinx. It is a flavor of markdown called **MyST, for "Markedly Structured Text"**.
The goal of MyST is to do **everything you can do in rST, but in pure markdown**. It has its own syntax pieces for roles, directives, etc, which means you shouldn't ever have to write rST if you're writing in MyST markdown.
[check this page for the syntax pieces supported with MyST](https://myst-parser.readthedocs.io/en/latest/using/syntax.html).
This PR replaces our `recommonmark` extension with `myst_parser`, and makes the modifications needed to the markdown files to use myst syntax. Basically, …
=> switching to myst markdown in docs

doc/doc-requirements.txt
I ran into [this build error](https://readthedocs.org/projects/zero-to-jupyterhub/builds/11003549/) after merging #1628.
I created an issue in myst_parser related to this: https://github.com/executablebooks/MyST-Parser/issues/139
=> Force sphinx>=2,<3 for myst_parser

doc/doc-requirements.txt
A followup to #1657 which actually failed to enforce "sphinx>=2,<3" which was part of myst-parser[sphinx], because pydata-sphinx-theme installed "sphinx" and it was then considered to be resolved.
Doh.
=> RTD build fix: get correct version of sphinx

images/secret-sync/Dockerfile, images/secret-sync/secret-sync.py, jupyterhub/templates/proxy/autohttps/deployment.yaml
During an upgrade, the autohttps pod can restart in a rolling update fashion, which makes us have two autothttps pods, and two secret-sync pods. The new pod may be getting certificates for a new hostname, but suddenly the old pods secret-sync container may override the content. It may not be a big deal, but it will at least slowdown the shutdown of the autohttps pod that the secret-sync container is slow to shutdown and require the full 30 seconds of grace period for no reason.
This fixes that issue by listening to the SIGTERM signal that comes before the SIGKILL as part of kubectl delete or docker stop.
=> autohttps: instant secret-sync shutdown

dev-config.yaml, images/singleuser-sample/Dockerfile, jupyterhub/templates/hub/netpol.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/singleuser/netpol.yaml, jupyterhub/values.yaml, tests/test_spawn.py
If someone wanted to restrict the egress, they would previously need quite a bit of exceptions. With this setup, I hope to make them function even though the Helm chart user removes denies all not explicitly allowed egress by removing the explicit allowance of 0.0.0.0/0 (all IPv4 egress).
=> Flesh out networkpolicies

jupyterhub/values.yaml
With a readinessProbe that polls every ten seconds, we potentially need
to wait ten seconds after the pod is actually ready. By reducing this
number significantly, we avoid eigght potential seconds of waiting for
nothing.
At the same time, this could clutter logs. But, the proxy will not log
these requests, and I made a PR to JupyterHub to only log requests to
the health endpoint on the debug level: https://github.com/jupyterhub/jupyterhub/pull/3047
=> Tweaking readiness/liveness probe: faster startup

doc/source/administrator/security.md, jupyterhub/schema.yaml
This references the documentation about setting up static IPs in the configuration reference section from the automatic https section.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1599
P.S.  After reading a bit through comments and other issues related to this, it seems that the `loadBalancerIP` should be set on the proxy service and not on the hub (or is it both?).
If it's just the proxy, we should probably remove the hub part from the docs.
=> Reference static ip docs

doc/source/administrator/advanced.md, jupyterhub/schema.yaml
Kubernetes v1.11 api reference docs was removed, but the content is the same in k8s 1.18 so I just bumped it.
=> docs: fix broken links

doc/source/customizing/user-resources.rst
As of `gcloud` release [260.0.0 (2019-08-27)](https://cloud.google.com/sdk/docs/release-notes#cloud_sdk_12), this warning appears:
> WARNING: The --size flag is now deprecated. Please use `--num-nodes` instead.
=> Use --num-nodes instead of --size to resize gcloud cluster

jupyterhub/templates/hub/secret.yaml
Having an explicit key for the API token of each service is nice because
it allows the service to mount the particular key as an environment
variable.
We used to have this functionality but in #941 we moved the API tokens to the `values.yaml`. This is a bit tricky to use because now your service has to mount that yaml, parse it and get the token out of the yaml (and it gets access to tokens from all services).
=> [MRG] Add services API tokens in hub-secret

doc/source/customizing/user-environment.rst
jupyter-labhub and command setting are no longer required
=> Simplify setting up JupyterLab as default

jupyterhub/templates/proxy/autohttps/configmap.yaml
While refactoring for autohttps testing I introduced this failure to fail hard on missing contactEmail when it was assumed. This resolves that issue.
=> fix: intentionally error on missing Let's Encrypt contact email configuration

jupyterhub/schema.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/values.yaml
This PR adds the ability to add annotations to the continuous and hook image puller pods.
Fixes #1627
=> Add annotations to image puller pods

jupyterhub/templates/NOTES.txt, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
This makes it possible to override the `securityContext`
for the hub container spec, similar to how the hub container
`resources` are overridable via `values.yaml`. By default the
`securityContext` is the same as before.
One use case for this is to be able to specify `capabilities`
in order to run py-spy [1] on the hub container.
One downside to this approach is that for anyone overriding the
hub container `securityContext` may need to duplicate the
`runAsUser` and `allowPrivilegeEscalation` entries which means
they could fall out of alignment with the upstream chart. So an
alternative to this full replacement approach is to add an
optional `extraContainerSecurityContext` entry similar to how
`extraVolumeMounts` works. The downside to that is it could
eventually conflict with what is not …
=> Add config for hub/proxy/autohttps container's securityContext

images/hub/dependencies, images/hub/requirements.txt
@meneal demonstrated in #1712 how we can use [trivy image scanning](https://github.com/aquasecurity/trivy) to get reports on known vulnerabilities.
After installing trivy and locating myself in the repo folder, this is what we can do to get a nice report.
```
cd images/hub
./dependencies freeze --upgrade
trivy image --clear-cache
trivy image --ignore-unfixed hub-dependencies:latest > trivy-report.txt
```
```
2020-07-10T03:05:17.929+0200	[33mWARN[0m	You should avoid using the :latest tag as it is cached. You need to specify '--clear-cache' option when :latest image is changed
2020-07-10T03:05:17.939+0200	[34mINFO[0m	Need to update DB
2020-07-10T03:05:17.939+0200	[34mINFO[0m	Downloading DB...
2020-07-10T03:05:24.628+0200	[34mINFO[0m	Detecting Ubuntu vulnerabilities... …
```
=> k8s-hub img rebuild -> dependencies refrozen

CONTRIBUTING.md, ci/common, dev-config-pebble.yaml, jupyterhub/values.yaml
I [recently pinned](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/66b917d98ba877d9fad70351dba07b9e08af65a2) v2.2.2 of traefik (running in our autohttps pod) from v2.2 as v2.2.2 contain [a fix](https://github.com/containous/traefik/pull/6939) to [an issue](https://github.com/containous/traefik/issues/6871) that will make our autohttps system stop malfunction randomly in our CI system and with users trying to acquire certificates.
Now I noted that [Traefik released v2.2.3 / 2.2.4](https://github.com/containous/traefik/releases/tag/v2.2.4) to fix a regression, so this PR bumps it once again. The docker image [will soon be out](https://hub.docker.com/_/traefik?tab=tags) but isn't yet. When its out, we restart this test and merge on success.
=> Autohttps reliability fix: bump traefik version

dev-config-pebble.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml
Sometimes autohttps cert acquisition failed, and it was because the
challenge was initiated from a not-k8s-ready pod due to a
readinessProbe that would require to get a successfull response before
it marked the pod as ready.
See: https://github.com/containous/traefik/issues/7033#issuecomment-659589390
Closes #1716 - @AndrewSav provided very useful guidance making me realize this, and I'm truly thankful this help - it made my day! Thank you!!! :tada: :heart:
=> fix: autohttps cert acquisition stability fixed

doc/source/customizing/user-environment.rst
The linkcheck gave a warning about two separate links both referencing
`jupyterlab`, which in turn made the linkcheck job on travis fail as it
is configured to fail on any warning.
I removed the second link, it wasn't important anyhow.
=> docs: fix linkcheck warning

jupyterhub/templates/hub/configmap.yaml
JupyterHub services that didn't have a apiToken set in the Helm chart configuration hub.services.my-service-name.apiToken didn't render into the configmap.
=> fix: jupyterhub services without apiToken was ignored

images/hub/requirements.txt
Main changes:
- changes default named-server template to avoid possible collisions
- use slugs to select profiles
=> update kubespawner to 0.12

doc/source/administrator/authentication.rst
I was getting this error with v0.9.0 and the change in the commit attached fixed it:
```
traitlets.traitlets.TraitError: The 'hosted_domain' trait of a GoogleOAuthenticator instance must be a list, but a value of class 'str'
```
=> Update Google auth to use a list for hosted_domain

doc/doc-requirements.txt
The extra requirement specified like myst-parser[sphinx] is no longer needed, as it's now included by default in myst-parser and that's the deprecation fixed.
=> docs: myst-parser deprecation adjustment

CONTRIBUTING.md
This PR fixes the broken link to the Jupyter contributor guide in `CONTRIBUTING.md`
=> Fix broken link to Jupyter contributor guide

.travis.yml
4.3.0 was just released (https://github.com/docker/docker-py/releases/tag/4.3.0) and changed
the default API version to v1.39 and apparently this is breaking CI.
(See here: https://travis-ci.org/github/jupyterhub/zero-to-jupyterhub-k8s/jobs/716638776#L374)
=> Fix travis by pinning docker python package version

doc/source/administrator/security.md
Ran the [local doc development](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/README.md) instructions to make sure the tabbing looked correct, and it does.
Closes #1750 .
=> Unindent lines to fix the bug in "Specify certificate through Secret resource"

jupyterhub/files/userscheduler-defaultpolicy.yaml, jupyterhub/values.yaml
I've been getting the 0.9.0 chart running on an autoscaling cluster on Digital Ocean.  Most things are working, but it would try to schedule more than seven pods with volumes on a given node.  (Digital Ocean has a relatively low limit of 7 on this.)  This only happened when using the userScheduler; if that was disabled, the limits were respected.
Digital Ocean support pointed out that the scheduler did not have the "MaxCSIVolumeCountPred" predicate, which they use to count the attached volumes.  This appears to be a more general predicate, which will replace the provider specific ones we currently have. (See [here](https://github.com/mjaow/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L61).)
I could only get this to work with an updated version of the …
=> Enable the user scheduler to pay attention to CSI volume count

.gitignore, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/values.yaml
When we want to deploy Jupyterhub on Kubernetes, we have had an issue about that singleuser pod spawner which it is also named Kubespawner doesn't use our existing image pull secrets although we had defined on values.yaml. I have found that jupyterhub_config.py configuration doesn't include that config load so anyone can't use existing image pull secrets on their system. Also Kubespawner takes image pull secret name as string not array so that I have changed format of the image pull secret configuration on values.yaml :)
=> jupyterhub existing image pull secret configuration load bug fixed

jupyterhub/values.yaml
This bumps the traefik versions to v2.3 and stops using a specific patch version. The use of a specific patch version was introduced to avoid nodes with a v2.2 downloaded already that wasn't updating to an important fix.﻿
=> Bump traefik (autohttps pod) to v2.3

.travis.yml
This relates to the discussion in https://github.com/jupyterhub/team-compass/issues/317.
We now always publish before running tests as the publishing stage that contains the publishing job is ordered before the test stage. Previously, the test stage could fail and the publishing stage would then never run.
﻿- CI: publish chart before running test
- Docs: add note about why docker version was pinned
=> CI: always publish helm chart on push to master

jupyterhub/files/hub/jupyterhub_config.py
While wondering where HUB_SERVICE_HOST and HUB_SERVICE_PORT values
come from I stumbled across this comment [1] so I'm adding an inline
comment to the code.
[1] https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1410#issuecomment-531130122
Related #1410
=> Leave a comment about where HUB_SERVICE_* values come from

jupyterhub/templates/image-puller/_daemonset-helper.yaml
This was discussed in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1760. The gist of this PR which was only part of the discussion, is to allow the continuous image puller pods to be evictable in order to prefer letting a user pod schedule than a puller pod if the node becomes full. Sometimes a node can become full because of the sheer number of pods as k8s limits this as there is a limit of IPs for each node.﻿
=> Make continuous image puller pods evictable

.travis.yml, jupyterhub/templates/ingress.yaml, tools/templates/lint-and-validate.py
Rather than have a TODO about the deprecation of the ingress, use a dynamic definition of the ingress `apiVersion`. It makes the chart a little messier, but makes it dynamic.
=> k8s api compatibility: add conditional to ingress apiVersion

jupyterhub/templates/hub/deployment.yaml, jupyterhub/values.yaml
This allows one to set failureThreshold and timeoutSeconds for the hub probes.
Related: #1732
=> Add additional liveness and readiness probe properties

jupyterhub/schema.yaml, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, tools/templates/lint-and-validate-values.yaml, tools/templates/lint-and-validate.py
In short, specifying an environment variable for the JupyterHub pod or the user pods could only be done in a limited fashion that excluded specifying an environment variable that got its value from some Kubernetes ConfigMap/Secret or similar. This has only been only possible with intrusive workarounds. This PR closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1103 and an associated KubeSpawner PR has already closed https://github.com/jupyterhub/kubespawner/issues/306#issuecomment-474934945.
This PR enables `hub.extraEnv` to function with a format either exactly like Kubernetes [EnvVar](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#envvar-v1-core) specification or a shorthand where a `name: ...` is implied. This format is now also documented in the …
=> hub.extraEnv / singleuser.extraEnv in dict format to support k8s EnvVar spec

dev-config.yaml, tests/test_spawn.py
I had not tested the Z2JH + KubeSpawner integration e2e of the singleuser.extraEnv but relied on template rendering tests for hub.extraEnv and a unit test in KubeSpawner. This addition ensures end to end functionality of singleuser.extraEnv.﻿
=> CI: Add test for singleuser.extraEnv

jupyterhub/schema.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/values.yaml
If a k8s cluster has a LimitRange resource, it may end up for example
allocating 100m CPU for containers which is a waste of resources. This
would be a waste as the running container only does `sh -c "Done!"`
anyhow. While there is image pulling happening, that is done before the
actual container starts so its worth noting we don't need any resources
specified for that.
Another reason for specifying resources, and making them configurable,
is that sometimes there is a ResourceQuota resource that requires the
resources to be explicitly specified on pods.
Related:
- Default CPU requests - https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/
- LimitRange https://kubernetes.io/docs/concepts/policy/limit-range/
- ResourceQuota - …
=> Minimal and explicit resource requests for image-puller pods

doc/source/administrator/security.md, jupyterhub/templates/proxy/service.yaml, jupyterhub/values.yaml
For HTTPS, we want to expose port 443 on our service, but
only if it is 'turned on'. Unfortunately, in v 0.9, the
default was set to 'enabled' but it didn't act as enabled
unless hostnames were actually set. This exposed port 443
in proxy-public regardless of wether we were actually
set up for HTTPS or not. This caused weird issues with
AWS, since it was health checking all exposed ports. Since
we didn't have automatic HTTPS setup (since that needs
hostnames), this broke all installs on AWS!
This tries to be backwards compatible change, exposing
port 443 only if we *really* have https running. This
should fix issues with AWS, and be more 'correct'.
Manual HTTPS doesn't actually need hosts lists to be set,
so we remove that from our documentation.
We also re-introduce 'https.enabled' in …
=> https: Only expose port 443 if we really have HTTPS on

jupyterhub/values.yaml
This memory limit seems to include pod overhead, which
can be variable based on cluster config. In my cluster (AKS)
with Calico enabled, the memory limit was too low and kept
crashing these pods with very weird reasons - the usual
reasons aren't reported since it's not *our* process that
is causing OOM kills, but the cluster's overhead.
By removing the default resource limits, we prevent thi
from being a problem. Theoretically this would let the pods
have unbounded memory - but since we control the contents,
it wouldn't be the case.
We leave the explicit default requests be, for reasons
outlined in
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1764.
The capacity for admins to specify their own limits is
still in place, in case you want that for your cluster.
=> Remove memory / cpu limits for pre-puller

jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/values.yaml
This is a followup on #1778 which didn't ensure that pods are scheduled on the most used node correctly because there were some remnant competing logic. This PR disables the competition that makes sense to give lower priority to than the `NodeResourcesMostAllocated` critiera.
See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1778#issuecomment-696079664 for a discussion on this PR.
As this PR is a complementary fix to #1778 recently merged, I'll go ahead and merge this directly if tests succeeds.﻿
=> user-scheduler: tweak modern configuration

images/image-awaiter/daemonset.go, images/image-awaiter/main.go, jupyterhub/schema.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/values.yaml
This PR address a risk of `helm upgrade` failing for a bad reason - that the hook-image-puller pods fail to schedule because the nodes cannot accept more pods on them.
When `helm upgrade` is run, certain k8s resources are rendered and deployed before others using [Chart hooks](https://helm.sh/docs/topics/charts_hooks/). We deploy a `hook-image-awaiter` Pod and a `hook-image-puller` daemonset. The `hook-image-awaiter` pod awaits the pods of the `hook-image-puller` daemonset to become ready, as they do when they have been scheduled and pulled all images in dummy init containers.one node
The failure we can avoid is when the `hook-image-awaiter` pod get stuck waiting for one of the image puller pods that fails to schedule on a node, because a node is out of capacity to schedule more pods - …
=> hook-image-puller: -pod-scheduling-wait-duration flag added for reliability during helm upgrades

jupyterhub/schema.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
the values.yaml implies that this option is available, but it is not. this change adds the template to the proxy deployment so `.Values.proxy.extraEnv` is available
=> enable .Values.proxy.extraEnv

doc/source/digital-ocean/step-zero-digital-ocean.rst
In the [Kubernetes on Digital Ocean](https://zero-to-jupyterhub.readthedocs.io/en/latest/digital-ocean/step-zero-digital-ocean.html) doc page, there are two minor issues.
The `doctl k8s cluster create` command is using an outdated Kubernetes version. Using `1.12.1-do.2` throws a 422 validation error.<br />
When creating a Kubernetes cluster through Digital Ocean's dashboard, only versions 1.16.14 and up seem to be supported.
I've replaced the legacy version with latest `1.18.8-do.0`.
<br />
The `doctl k8s cluster create` command is also missing a double quote at the end. I've added the missing double quote.
Confirmed by testing in Ubuntu 20.04:
=> Fix legacy version in DigitalOcean Kubernetes setup doc

CHANGELOG.md, dev-config.yaml, doc/source/administrator/security.md, jupyterhub/values.yaml
rather than making these opt-in, let's make them opt-out
=> enable network policy by default

jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/values.yaml
Kubespawner allows us to configure user's pod name, but it's not exposed in this z2j chart.
I made it configurable in values.yaml.
ref: https://github.com/jupyterhub/kubespawner/blob/7e515c50bc3aeed75539df321ee63b4d070168d1/kubespawner/spawner.py#L262-L274
=> Allow configuration of Kuberspawner's pod_name_template

jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/secret.yaml
JupyterHub itself, authenticators, etc, all may want to use the values
we also use to render the Helm charts templates. So, we typically take
them av available in {{ .Values }}, split it apart, and render it to a
k8s configmap as well as a k8s secret.
This separation had little to no benefit and was hard to maintain. In
this commit I gather the {{ .Values }} into the hub-secret file. I also
configure c.JupyterHub.cookie_secret instead of passing that
information by mounting a k8s secrets key's value into a
JPY_COOKIE_SECRET environment variable on the hub pod.
=> Complexity reduction - combine passthrough values.yaml data in hub-config (k8s configmap) to hub-secret (k8s secret)

jupyterhub/values.yaml
This configuration makes the hook-image-awaiter start comparing the
number of scheduled image-puller pods with the number of ready
image-puller pods, instead of comparing the number of desired
image-puller pods with the ready number of image-puller pods, after a
duration of 10 seconds.
This helps anyone using the hook-image-puller to avoid failures
of running `helm upgrade` that can happen if a node is full packed with
pods and no more pods can be scheduled on it, because then the
image-awaiter would get stuck waiting forever on an image pulling pod
that never successfully schedules to do the actual pulling.
---
@yuvipanda I merged #1763 and created this as a followup to the review comment https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1763#discussion_r493209514 about sticking …
=> Relax hook-image-puller to make upgrades more reliable

doc/source/amazon/step-zero-aws.rst, doc/source/setup-jupyterhub/setup-helm2.rst
Fixes some warnings found in the CI build that checks for docs warnings.
=> Docs: fix some sphinx warnings

jupyterhub/values.yaml
Closes #1800, this is a very safe change to make I think.
=> hub livenessProbe: bump from 1m to 3m delay before probes are sent

jupyterhub/templates/proxy/autohttps/deployment.yaml, tools/templates/lint-and-validate-values.yaml
This is a remnant change following #1757 to ensure all of our extraEnv configuration support the same syntax.
=> Fix same functionality for proxy.traefik.extraEnv as other extraEnv

jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
Closes #1282 - thank you @rokroskar for reporting this!
=> userScheduler: only render associated PDB resource if userScheduler itself is enabled

.readthedocs.yml, doc/doc-requirements.txt, doc/source/conf.py
It appears that when we build the docs in the PR preview, it works. But,
when we push to master, it doesn't any more. It appears that using
pydata_sphinx_theme to build PDFs and/or ePub files makes it crash if we
using sphinx3 rather than sphinx2. Since a doc dependency that
(executablebooks/myst-parser) previously was limited to sphinx 2 but not
longer is, the PDF / ePub build made our builds when pushing to master
fail.
I'd like to avoid maintaining these things, and would like to stop
building PDFs and ePub files. I don't know if they are used, but I'd
like to focus attention to https://z2jh.jupyter.org anyhow I think.
---
I'll self merge this now as to trial that this actually resolved the issue. If we want to have htmlzip / PDF / ePub builds again, I think we can pin sphinx<3 in …
=> CI: fix RTD builds on push to master

README.md
I've updated the badges that links to the Helm chart repo so that they now go to the various parts of that webpage that is relevant, such as the development release section specifically.
I've also deleted the badge for the pre-releases, because until we identify those specifically at https://jupyterhub.github.io/helm-chart, the are hidden deep in the development releases anyhow, and the badge itself lists not the latest 0.10.0-beta.1 or similarly, but the latest development release.
=> README.md: badges for the helm chart repo to go directly to the relevant view

doc/source/administrator/advanced.md, doc/source/administrator/authentication.rst, doc/source/administrator/optimization.md, doc/source/conf.py, doc/source/google/step-zero-gcp.rst
This fixes some broken links that we were manually hardcoding to specific headers on the reference page. Instead we are now programmatically adding Sphinx labels to each section of that page so that we can reference them in a URL-agnostic way.
The new Sphinx labels have the structure:
```
schema:<object>
```
For example, 
```
schema:scheduling.podPriority
```
So you can refer to them directly like `` Here is my sentence and now I :ref:`refer to pod priority in rST <schema:scheduling.podPriority>` `` .
closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1717
=> fixing broken links

jupyterhub/schema.yaml, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/values.yaml
With a large list of images in the singleuser.profileList, users ended
up with delays caused by images being pulled for so long time that it
blocked what was actually important to pull to get started properly.
This option allows for a long singleuser.profileList with many different
images to be setup, while only pulling the default image, or optionally
those configured under prePuller.extraImages.
Closes #1393, Closes #1739 good enough
---
I also added a commit optimizing the order slightly, where the more likely to be used images are pulled first, in this case i determined that images in singleuser.extraContainers are far more likeley to be used than an image in a profileList
=> Added config prePuller.pullProfileListImages

jupyterhub/schema.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
Closes #1302, thanks for documenting this request well and exploring what happens if you provide a flag twice @ivan-gomes, and as usual @manics - thank you for your presence! I love it :heart:!
=> Added config option: proxy.chp.extraCommandLineFlags

jupyterhub/templates/NOTES.txt
I'm making this PR to emit a warning instead of forcing the template rendering to `fail` as part of `helm upgrade` or `helm install`.
This checks for attempts to configure proxy.https without explicitly setting proxy.https.enable to true, and if so, let the template rendering fail. This is meant to help users that configured https retain the expected functionality by forcing them to use the configuration that is required to maintain such functionality.
The default value was changed in #1758.
This PR implements the idea in #1806 and thereby closes #1806.
---
In this PR I included a commit fixing a warning in our CI system.
=> deprecation: warn when proxy.https is modified and proxy.https.enabled=true

jupyterhub/templates/NOTES.txt, jupyterhub/templates/image-puller/_daemonset-helper.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/proxy/autohttps/_configmap-traefik.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml
This can help us avoid usage of root by default which can cause clusters with [PodSecurityPolicy resources](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) to stop the Helm chart from functioning.
In practice, what I do in this PR is to create Helm chart configuration to set all Pod's containers' `securityContext`, and let this configuration default to have a securityContext like this be injected to all of our managed containers within the pods.
```yaml
spec:
template:
spec:
containers:
- image: ...
securityContext:
runAsUser: 65534
runAsGroup: 65534
allowPrivilegeEscalation: false
```
A securityContext of a pod with a `runAsUser` directive will force the container to startup as that user instead of the default: `root`. This can add another layer of security to by letting …
=> Set container securityContext by default

jupyterhub/templates/image-puller/_daemonset-helper.yaml
I previously removed this logic because it was messy to implement the
deprecation logic, and the container would be so very small anyhow. But,
I realized that the size may only be a smaller part if this matters or
not. Each image needs to be pulled, and if they end up being pulled in
the wrong order, it can be very troublesome.
What could happen without this change, is that the image puller pods
could spend time pulling multiple images, then a user pod arrives to the
node and its image is already pulled and it only needs to pull the small
cloudMetadata blocker image, but, pulling that is blocked currenlty.
Because images are pulled in a sequence as I understand it, so the user
pod arriving may end up needing to wait for its little initContainer
image to be pulled and that is just bad.
So, …
=> Revert recent removal of image-pulling related to cloudMetadata blocker

.travis.yml
It is typically not relevant feedback for the user to run all the different k8s version checks, but its nice to know that linting is okay, upgrade works, and one normal test works.
With this PR, we put ensure we get that early on.
=> CI: reorder ci jobs to provide relevant feedback quickly

jupyterhub/schema.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml, tools/templates/yamllint-config.yaml
This PR is meant to fix https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1130
=> Add nodeSelector and tolerations config for all pods of Helm chart

images/image-awaiter/Dockerfile, images/image-awaiter/daemonset.go, images/image-awaiter/go.mod, images/image-awaiter/go.sum
Uses https://pkg.go.dev/mod/github.com/hashicorp/go-retryablehttp which is drop-in compatible wrapper around the default Go http client.
Will fix issue where `image-awaiter` never becomes healthy when deployed in a cluster with a service mesh - since the service mesh uses an init container to configure pod networking, the network might not be ready to route connections when `image-awaiter` tries to make a connection on startup, so `image-awaiter` should be a good resilient HTTP client and at least retry a few times.
Example using the retry settings of 5 retries:
```
~/Source/zero-to-jupyterhub-k8s/images/image-awaiter(master*) » docker run -it --rm --net=host yolo:test4 /image-awaiter -debug -namespace default -daemonset hook-image-puller …
```
=> Add retryable HTTP client to image-awaiter

jupyterhub/.helmignore
Anything within the root folder of the Helm chart, where Chart.yaml resides, will be embedded into the packaged Helm chart. This is reasonable since only when the templates render after the chart has been packaged and distributed, will the templates logic evaluate that determines if other files were referenced, such as our our files/hub/jupyterhub_config.py.
=> Add schema.yaml and validate.py to .helmignore

chartpress.yaml, images/hub/Dockerfile, images/hub/requirements.txt, jupyterhub/Chart.yaml
and bumps dependencies in hub image
I had to tweak things a bit since our freezing code didn't play nice with the fact that the jupyterhub version is specified both inside requirements.txt and as a separate arg, which results in a conflict when the two versions don't match. I'm not sure what exactly is the best way to deal with that. Perhaps put jupyterhub version in requirements.in instead?
several were removed due to https://github.com/googleapis/google-auth-library-python/pull/619 making aiohttp an optional dependency of google-auth. I *think* this is fine and shouldn't affect us, since this is a transitive dependency and we don't directly use google-auth + aiohttp. Presumably tests will reveal if we should add `google-auth[aiohttp]` as a dependency...
=> try out jupyterhub 1.2.0b1

.github/dependabot.yaml
- Update pip dependencies with `lock-file` versioning strategy 
- Update docker dependencies (EDIT: remove for now)
- Set scheduled dependency checks to weekly (EDIT: daily)
EDIT: May end up closing #1753 if we get this right - keeping it open a while
=> Add dependabot config to update dependencies automatically

artifacthub-repo.yml, jupyterhub/Chart.yaml
This will allow us to register with the distribution center for Helm charts: [Artifact Hub](https://artifacthub.io/). Helm Hub is automatically redirecting there now.
I suggest others in the @jupyterhub/jupyterhubteam that wants to add themselves here as owners/maintainers in the Chart.yaml as well, if not for you please do it for me so it doesn't look like the only maintainer in this collaborative project involving so many parts from the JupyterHub ecosystem!
This relates to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1517.
=> Add maintainers / owners to register with Artifact Hub

jupyterhub/schema.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
Now that we have proxy.traefik.extra(Static|Dynamic)Config,
we can configure traefik to do more proxying. Specifically,
I want it to proxy ssh traffic to an instance of
[jupyterhub-ssh](https://github.com/yuvipanda/jupyterhub-ssh).
This works fine, but we need to have proxy-public expose
port 22 to the world. Currently this is impossible -
this PR allows adding additional ports here.
----
- proxy.service.extraPorts configuration added, influencing the proxy-public service, which goes either to autohttps (traefik) or the proxy pod (chp).
- NetworkPolicy rules for ingress may need to be configured separately to this for the receiving pod to not get this kind of new traffic be blocked.
=> Add proxy.service.extraPorts to add ports to the k8s Service proxy-public

ci/common, jupyterhub/values.yaml, tests/test_spawn.py
Meant to fix #1853.
1. Additional logs on CI failures
2. Traefik pinned to v2.3.0
The motivation is to see if there is a race condition in v2.3.0 specifically, because we have run into some issues in v2.3.1 as can be seen in https://travis-ci.org/github/jupyterhub/zero-to-jupyterhub-k8s/jobs/737397758.
3. Bugfix in the check if a user server has started up.
I think I used a faulty assumption before.
=> CI: Try to improve test stability and autohttps cert aquisition reliability

doc/source/microsoft/step-zero-azure.rst
I broke the link to my own docs as I've redeployed them with Jupyter Book! :D This PR fixes the link out.
=> Fix link to Hub23 docs

jupyterhub/schema.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, tools/templates/lint-and-validate-values.yaml
Allows admins to configure the traefik pod, particularly
to support network policies of *other* charts deployed
in the same namespace
=> Allow adding extra labels to the traefik pod

jupyterhub/values.yaml
Traefik v2.3.1 and v2.3.0 has behaved unreliably, but Traefik v2.3.2 at least managed to reliably work 50/50 times tested.
Assumed to close #1853
=> Pin Traefik to v2.3.2 for cert acquisition stability

doc/source/conf.py
The edit on github button didn't work before, because it referenced /doc instead of /doc/source
=> docs: fix edit button, so it doesn't go to a 404 page

images/hub/requirements.txt
This PR fixes a recently introduced bug influencing the configuration of singleuser.imagePullSecrets.
Thank you @johnhoman :heart:
=> Bump KubeSpawner to 0.14.1 to fix a bug in 0.14.0 about image_pull_secrets

jupyterhub/schema.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This allows the chart to override the JupyterHub commandline.
While I started doing an extraCommandLineArguments idea, that
did not work as specifying the config option twice will not
allow the hub to start.  So this makes the command line in
general overrideable.
=> hub.command and hub.args configuration added

CHANGELOG.md, dev-config.yaml, jupyterhub/schema.yaml, jupyterhub/templates/NOTES.txt, jupyterhub/templates/hub/netpol.yaml, jupyterhub/templates/proxy/autohttps/netpol.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/singleuser/netpol.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
- `proxy.networkPolicy` is deprecated, and `proxy.chp.networkPolicy` and `proxy.traefik.networkPolicy` is introduced.
Since #1670 the proxy pod would not accept incoming traffic from pods in other namespaces, due to a bugfix that caused a breaking change. This can be observed in #1863 for example I think.
```diff
- ports:
- port: http
{{- if or $manualHTTPS $manualHTTPSwithsecret }}
- port: https
{{- end }}
-    - from:
+      from:
- podSelector:
matchLabels:
hub.jupyter.org/network-access-proxy-http: "true"
```
The bug fixed was that `hub.jupyter.org/network-access-proxy-http: "true"` was entirely ignored and had no meaning, but now that it got meaning, we ended up restricting access too much. As an example, the proxy would reject incoming traffic from a nginx-ingress-controller pod …
=> netpol: allowedIngressPorts and interNamespaceAccessLabels config added with defaults retaining 0.9.1 current behavior

jupyterhub/values.yaml
This PR just bumps the CHP images, which has some bugfixes, for example regarding the implementation of the --custom-header flag, but also just makes the Docker image be more updated.
=> Dependency: bump proxy pods image of CHP to 4.2.2 for bugfixes and docker image dependency updates

images/hub/requirements.txt
This should be part of 0.10.0, so we should cut a 0.10.0-beta.2 I guess.
=> Bump OAuthenticator to 0.12.0 from 0.11.0

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/service.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
This PR are some remnant ideas I had from inspecting our Helm chart with the then stricted `helm lint --strict` policy in #1681. `helm lint --strict` is in v3.3.4 less strict than it was before and we now pass with flying colors!
=> Helm template aesthetics fixes

jupyterhub/templates/hub/deployment.yaml
I messed up in #1877, but no harm done except the PR creation noise.
=> Complementary fix to recent aesthetics PR

README.md
I removed it a while back when I thought it would not work.
=> Add back Helm chart badge for latest pre-release (alpha, beta)

images/hub/Dockerfile, images/hub/requirements.in, images/hub/requirements.txt, images/network-tools/Dockerfile, images/singleuser-sample/Dockerfile, jupyterhub/values.yaml
This PR bumps some core images to avoid known vulnerabilities and just keep up to date in general.
`globus_sdk[jwt]` as a dependency could be removed because it was no longer needed for the GlobusOAuthenticator any more, but the azure authenticator still require PyJWT so we still install that.
I choose to keep pinning the docker-stacks/base-notebook version to avoid risking issues introduced without us understanding why.
=> Remove globus_sdk and update various Docker images

README.md
See https://github.com/jupyterhub/team-compass/issues/348 for the JupyterHub org's migration.
=> Update Travis CI badge following .org -> com migration

ci/publish
This mirrors jupyterhub/binderhub setup. The value from this message is that whenever a PR is merged, chartpress will publish a new dev version with a git push to jupyterhub/helm-chart's gh-pages branch along with the package helm chart. Since this is done with a commit message referencing the PR, GitHub will show a notice of the commit mentioning the PR when viewing the PR. And, this commit will in its title have information about the Helm chart version, which can help anyone look at a merged PR to realize what version they need to upgrade to benefit from this.
=> CI: publish with helpful commit message

doc/source/administrator/optimization.md, doc/source/jupyterhub/customizing/user-resources.rst
This adds a short guide to explain the "limit to guarantee ratio" for memory and CPU. It's a tricky subject that we've found a lot of hub admnistrators run into, but it's also a bit of an art-form without a single strict answer. So this tries to add some explanation of the problem and its nuance in the hopes that administrators will be able to more effectively provision their resources.
WDYT @yuvipanda , who was the one to originally explain this to me.
=> DOCS: Adding note on limit to guarantee ratio

jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
Follow-up to #1852. Useful to explicitly expose ports
in deployment too - otherwise you can't use port names like
`ssh` in service definitions. To allow ingress on a port named
`ssh` in traefik right now, you have to know it is listening
on port 8022, and set the following:
```yaml
proxy:
autohttps:
networkPolicy:
allowedIngress: [http, https, 8022]
```
This requires knowledge that `8022` is the ssh port. Instead,
it would be nice to specify `ssh` instead - and that requires
defining that in the deployment. This is true for other places
too - like the service definition.
----
#
=> Allow exposing extra ports in traefik deployment

doc/source/administrator/authentication.rst, jupyterhub/files/hub/jupyterhub_config.py
Enable the parameter to be set in values.yaml. Also add a refernce to
the code that does the mapping, so it is easier for user to figure out
correspondence between ldapauthenticator params and params in
values.yaml.
=> Add use_lookup_dn_username parameter for LDAP

.github/workflows/test.yml, ci/common, ci/publish
@manics I had 34/34 success `install jobs` but had `1/2` failures on `upgrade` jobs when I removed the 1 minute delay and I think I understand at least some parts of the issues. [Here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1904/checks?check_run_id=1377782878) is a failure example of an `upgrade` job.
The autohttps pod doesn't have a readiness probe, it was removed as it is required to be Ready to receive responses for the ACME challenge, but from the perspective of users, this isn't sufficient as a criteria.
We currently await with `await_autohttps_tls_cert_acquisition` which inspects the logs for the text `Issued certificate`, but is this something that will show up if there isn't a need for issuing a certificate because there already exists one? I don't think so. …
=> CI: make upgrades more robust and skip 1m precautionary sleep

jupyterhub/templates/image-puller/job.yaml, jupyterhub/values.yaml
For any user with a ResourceQuota installed and aggregate limits to all pods combined container requests/limits, we need to allow resources be set to being denied by the Admission webhook that comes with a ResourceQuota resource.
Example of error that can come from not having resources configured on a pod are...
jupyterhub   4m49s       Warning   FailedCreate              job/hook-image-awaiter                 (combined from similar events): Error creating: pods "hook-image-awaiter-6mvsc" is forbidden: failed quota: jupyterhub-resourcequota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
Thank you @tirumerla for pointing this out!
Closes #1761 (again).
=> Configurable resource requests for hook-image-awaiter

ci/publish, jupyterhub/Chart.yaml, tools/templates/lint-and-validate.py
I made use of a helm template function (list `concat`) made available in helm v2.16 but not helm v2.15, due to that we need to explicitly require helm v2.16+
Besides that, I also add some small changes to the CI, such as strict linting of helm and passing a commit message when chartpress pushes a new helm chart package commit to our git based helm-chart repo.
=> Require helm v2.16.0 explicitly and minor CI updates

images/hub/requirements.txt
This PR bumps some dependencies in the hub image. There was a bugfix that could cause the kubernetes/python-client library to crash in kubespawner which would make the hub pod crash if the k8s server had some unrelated issues I think.
=> hub image: kubernetes 12.0.1, nativeauth 0.0.6, tornado 6.1

CHANGELOG.md
I think this may contain a relevant bugfix by bumping kubernetes/python-client used by kubespawner from 12.0.0 to 12.0.1, it also contains a few smaller enhancements.
I have set my eyes on the 1.0.0 release of z2jh btw, I think it would be helpful to be able to use major/minor/patch to signal changes impact better.
I set the release date to monday tomorrow as a hopeful guess this will be reviewed and merged by then ;)
- @yuvipanda this contains your extra ports release
- @matthew-brett this may contain a fix to the hub pod restarts, I don't know though, see #1912. It will also remove the harmless warning you have observed in the user-scheduler pod, see #1895.
=> Add changelog for 0.10.3 release

images/hub/requirements.txt
Closes #1917 which behaves a bit differently, hmmm... This bump was made with the `./dependency freeze --freeze` and it results in a bit different changes than dependencybot gives us. It does notify us about something though.
=> hub image: bump oauthenticator and prometheus-client

images/hub/requirements.txt
fixes issue with deprecated Authenticator config being ignored instead of preserved
closes #1914 (which was also fixed in release 0.10.6)
=> bump oauthenticator to 0.12.2

images/hub/requirements.txt
This PR closes #1930 and Closes #1931 which manipulated the dependencies a bit inaccurate to align with our Dockerimage it seems.
=> hub image: bump ltiauthenticator to 1.0.0 and oauthenticator to 0.12.3

.github/workflows/test.yml, dev-config.yaml, tests/test_spawn.py
This PR fixes a issue in our tests caused by jupyter.org added a new IP address, so when we tried to access jupyter.org which was assumed be sent to one of two ips, it could sometime be sent to another IP.
This PR Closes #1927.
In this PR I also bump helm to 3.4.1 from 3.4.0, and starts using manics/actions-k3s-helm of the latest version so we get a more modern version of Calico for example. These changes only influence the test suite and shouldn't hurt having as part of this PR in my mind, so I'm saving myself the trouble of creating a dedicated PR.
=> CI: fix of intermittent netpol test failure

jupyterhub/values.yaml
This PR closes #1936 and stems from a deliberations in #1732 that I suggest we close when we have added a startupProbe as suggested in an action point in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1732#issuecomment-705277165.
The actual changes are:
1. Enable hub's livenessProbe by default.
2. Make hub's livenessProbe start after 5 minutes (from 3), and trigger a pod restart after >5 minutes without any response (from >30s).
3. Make hub's readinessProbe very relaxed so it won't fail before the hub's livenessProbe or generally at all, because it would not serve a purpose to have a non-ready hub pod as it doesn't support being run in parallel with another pod.
4. Make proxy's readinessProbe be very relaxed for the same reasons at the hub pod.
=> Enable hub livenessProbe by default and relax hub/proxy probes

.github/workflows/image-scan.yaml, .github/workflows/vuln-scan.yaml, README.md
In this PR I've created a workflow scheduled to run once daily scanning the images we manage with chartpress for known vulnerabilities using [aquasecurity/trivy](https://github.com/aquasecurity/trivy) by using the [aquasecurity/trivy-action](https://github.com/aquasecurity/trivy-action).
Closes #1712.
=> ci: cronjob to scan images for known vulnerabilities

jupyterhub/templates/proxy/service.yaml
This extra space is breaking the lexing of old version of Rancher that I'm stuck with.  It's related to this issue: https://go-review.googlesource.com/c/go/+/168457
=> Helm template linting - remove extra space

jupyterhub/files/hub/jupyterhub_config.py
#1805 softly deprecated a configuration, but the new configuration didn't work which made the user pods not startup with an initContainer blocking access to the metadata server which is known to be a security concern.
=> Fix failure to block insecure metadata server IP

.github/workflows/vuln-scan.yaml
In the edge case situations when we multiple kinds of vulnerabilities are found, we needed a fix to the `jq` logic.
Test failed due to unrelated intermittent failure of cert acquisition :'( Not again...
=> ci: vuln scan fix

doc/source/jupyterhub/customizing/user-management.md
The target path was apparently moved. This updates the link down here.
=> Fixes link to authentication guide from user-management.md

jupyterhub/schema.yaml, jupyterhub/templates/NOTES.txt, jupyterhub/templates/proxy/autohttps/pdb.yaml, jupyterhub/templates/proxy/pdb.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This PR follows #1937 and discussion in #1934. I suggest we continue the discussion about _what to do_ in #1934 unless it is about the lines of codes changed.
I've opened https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1951 to represent the wish for better documentation about HA so that the we are more explicit with assumptions.
This is done to close #1934, and motivated by them being non-HA applications. For more in-depth discussion, see #1934.
This is done for completeness as it would generally make sense to enable PDBs for proxy/hub/autohttps all at once if either was enabled.
This was done to make the configuration more cohesive and easy to understand now that we have one for the proxy pod and the autohttps pod. This is in alignment of how we have mapped the other …
=> Disable PDBs for hub/proxy, add PDB for autohttps, and relocate config proxy.pdb to proxy.chp.pdb

chartpress.yaml, images/hub/Dockerfile, images/hub/requirements.in, images/singleuser-sample/Dockerfile
I wanted to make dependabot also manage the jupyterhub version. To make that happen, I had to stop pinning it explicitly here and there.
Associated with this in the PR, is a removal of the JUPYTERHUB_VERSION --build-args. I added PIP_OVERRIDES instead as it would be more generally helpful.
=> ci: let dependabot update jupyterhub, replace JUPYTERHUB_VERSION with PIP_OVERRIDES

doc/source/jupyterhub/customizing/extending-jupyterhub.rst
Bad things happen if you don't have this linebreak in place. In particular, it looks like helm is upgrading, but the values in your config file are not propagated and you get the wrong version onto your hub. Both of which can take hours to figure out (speaking from personal experience 😅)
=> Adds a linebreak

.github/workflows/test.yml
Just adds testing against k8s 1.20 which is now supported by k3s, not so long after k8s 1.20 was made available.
---
It has not been fully published yet it seems, probably around by tomorrow at least.
=> ci: Test against k8s 1.20

.github/workflows/test.yml
When dependabot opens a branch for its PR it also directly creates, it leads to the triggering of two separate test executions in parallel: one for the push event to a branch, and one for the PR. This change makes us ignore pushes to the `dependabot/**` branches.
=> ci: help dependabot only trigger one set of tests

.github/dependabot.yaml
With just a requirements.txt file, I should not have `versioning-strategy: lockfile-only` as I added for singleuser-sample.
=> ci: dependabot, add notes to config, fix singleuser-sample config

.github/workflows/test.yml, ci/common
The full_namespace_report functioned defined in ci/common prints some useful output about the current k8s namespace using kubectl. This PR updates that function.
1. We now always run it, it only takes 1 second for a local k3s cluster.
2. We provide headers with nice colors, yellow / red depending on if the content to known to be associated with an error or not.
3. I refactored the function a bit, removing xargs as it was hard to only print headers when a condition was met without duplicating a lot of code.
=> ci: full_namespace_report function improved

.github/workflows/test.yml
I'd like to try using k3s-channel, which pins k8s to v1.19 for example instead of v1.19.3+k3s1 etc. I believe if there is an issue for bumping a patch version, it will be observed in only one of the several tests in general.
In this case, we have an issue with k8s 1.20 in the latest channel, after a while it will go away without intervention thanks to this. It is a k8s issue rather than k3s issue btw.
=> ci: use k3s-channel instead of k3s-version

.github/workflows/test.yml, .pre-commit-config.yaml
I was skeptical, but now I fully understand that pre-commit really doesn't bother you unless you change the specific liens of codes in the specific file that would be influenced.
For example, assume you have run `chartpress --skip-build`, the Chart.yaml file will have its line `version: 0.10.6-n123.h1234567` set, which should be `0.0.1-set.by.chartpress` by default. But, if you commit another line change in this file, you will be fine! Having `chartpress --reset` run as part of pre-commit won't change a thing and everything will be fine.
=> pre-commit: chartpress --reset on Chart.yaml/values.yaml changes

.github/workflows/test-docs.yaml, doc/Makefile, doc/make.bat
Since we now only run this job on changes to the doc folder, I think it can be acceptable to let it fail loudly for a while.
=> ci: linkcheck rework: avoid duplicated build, add colors, make it fail loud

.github/workflows/test-chart.yaml
Working on #1923 it became very relevant to inspect the changes in rendered helm templates. The [helm diff plugin](https://github.com/databus23/helm-diff) can provide a diff compared to an already installed helm chart, so in other words it is only sensible to add as part of the upgrade tests, diffing from the installed version and the version to be installed.
In this PR I add another upgrade tests, so instead of just going from the latest stable release, we try to upgrade also from the latest dev release. By upgrading from the latest dev release we can also smoothly inject a `helm diff` first that provides us with the specific details on what changed in the Helm template rendered output of this PR.
While this is a good start, I'm not sure about what happens if the PR isn't recently …
=> ci: add another upgrade test and provide a template rendering diff

.github/workflows/test-chart.yaml, ci/common
I extracted the namespace report logic to a dedicated action to be reused in binderhub/mybinder.org-deploy/daskhub etc. So, now I'm trying it out here in z2jh.
https://github.com/jupyterhub/action-k8s-namespace-report
=> ci: use extracted github action for namespace report

ci/common, dev-config.yaml, jupyterhub/values.yaml
Just a maintenance bump, keeping up to date with kube-scheduler binary version used in the user-scheduler deployment.
The lint failure come from helm being upgraded and warns about deprecated API matters which make `helm lint --strict` fail.
=> dep: bump kube-scheduler from 1.19.2 to 1.19.7

.github/workflows/test-chart.yaml, ci/common, doc/source/jupyterhub/customizing/extending-jupyterhub.md, tools/templates/lint-and-validate.py
Without `helm template --validate`, I could not properly test #1983. And, with it added, it is redundant to have the kubeval steps in our CI system. For local development, `helm template --validate` can be used as well even though it now requires a k8s cluster which it didn't before, but I think it's too much maintenance to retain it just for that.
---
kubeval and the json schemas is a project with too little maintainers,
so now we can't validate against k8s 1.19 or 1.20. Thankfully, we have
helm template --validate now that allow us to use a k8s api-server to
validate that our rendered templates are valid k8s resources.
By running a helm template --validate step with the
lint-and-validate-values.yaml we can ensure that they are valid.
This transition also solves a problem we have had …
=> ci: replace kubeval with helm template --validate

jupyterhub/templates/ingress.yaml, jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
- k8s: bump Ingress apiVersion to v1 if capability exist (k8s 1.19+)
- k8s: bump PriorityClass apiVersion to v1 (k8s 1.14+ req.)
=> k8s: update Ingress / PriorityClass apiVersions

.github/workflows/test-chart.yaml, tools/templates/lint-and-validate.py
Helm lint emits warnings about deprecated versions, but since we have some logic like below, we will end up failing non no matter what until we remove support for k8s 1.18 etc at this point. Due to that, I went and allowed that check to fail but made sure it will emit a warning for us still (A GitHub Workflow run annotation).
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8b315ce66fd3faa1e8b707299c202d0d15449546/jupyterhub/templates/ingress.yaml#L2-L6
=> ci: accept helm lint --strict failure, but ensure GitHub UI warns

jupyterhub/values.yaml
Just a maintenance bump. Changelog at https://github.com/traefik/traefik/blob/master/CHANGELOG.md.
=> dep: bump traefik (autohttps pod) from v2.3.2 to v2.3.7

jupyterhub/templates/ingress.yaml, tools/templates/lint-and-validate-values.yaml
Our linting example didn't cover the ingress Helm template properly and a basic syntax error sneaked past in #1983.
I'll release 0.11.1 with this bugfix.
=> fix: fix of ingress regression and improved testing

.github/workflows/test-chart.yaml
Workaround the intermittent failures caused by a k8s regression to be fixed in k8s 1.20.3, see #1962 for details about this regression.
While it is allowed to fail, it will emit an "annotation", like a warning, to the GitHub workflow user interface looking like this.
=> ci: accept k8s 1.20 failures until 1.20.3 is out

jupyterhub/Chart.yaml
Helm 2 reached end of life in November 2020, so for future releases of
this Helm chart, just like many other Helm charts have opted to do, we
drop support for Helm 2 and allow ourselves to depend on Helm 3. By
updating this Chart.yaml to apiVersion 2 we will require Helm 3.
By relying on Helm 3.1+, we can solve some long standing issues, for
example the need to manually specify proxy.secretToken.
=> Require Helm 3 to allow for enhancements

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/pvc.yaml, jupyterhub/templates/ingress.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/templates/scheduling/_scheduling-helpers.tpl
This PR transforms statements like this using `if`...
```yaml
{{- if .Values.hub.annotations }}
{{- .Values.hub.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
{{- end }}
```
Into statements like this using `with`...
```yaml
{{- with .Values.hub.annotations }}
{{- . | toYaml | trimSuffix "\n" | nindent 8 }}
{{- end }}
```
This is a practice that has become popular and common practice among Helm charts. Currently our chart use a mix of these, but not after this PR where we only use the `with` variation.
No, As can be seen in [the rendered helm template diff](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2003/checks?check_run_id=1737818655), this didn't change anything. The test failure is intermittent k8s 1.20 stuff discussed in #1962.
=> refactor: systematically prefer use of with in templates

artifacthub-repo.yml
This reverts #1820 which was a mistake, it should really been added to the jupyterhub/helm-chart repo's gh-pages branch. I did this in https://github.com/jupyterhub/helm-chart/pull/114.
It would be good if a few jupyterhub team members created an account on artifactshub.io to avoid single points of failures. Ping me and I'll invite you to the JupyterHub org i created on artifactshub.
=> cleanup: remove mistakenly added artifactshub.io config file

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Closes #1486 by adding a default toleration to our core pods to a specific taint [according to our current documentation](https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html#hub-tolerations). This is done according to strategy described in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1486#issuecomment-648993410.
@minrk I recall trimming away this feature (but apparently missed that part in the docs) while adding the user equivalent tolerations because the complexity of the implementation I went for. Since then we have added configurable tolerations for all our core pods on request by users, this is to me something that indicates the value of having a default toleration.
What do you think about this implementation? I lean towards thinking its a good …
=> fix: set tolerations to predefined labels on core pods

ci/publish
Chartpress 1.0.0 which we now use doesn't push a chart that is already
published unless we also pass --force-publish-chart, due to that we no
longer need --long when publishing our charts.
See https://github.com/jupyterhub/chartpress/pull/102
=> ci: stop using --long as chartpress 1.0.0 makes it not needed

.github/workflows/test-chart.yaml, jupyterhub/templates/hub/_helpers-passwords.tpl
I'm debugging an issue with the seed secrets PR which seemingly misbehaves a bit.
Unless my algorithm is implemented wrong, it should mean that randAlphaNum first a-f letter is always showing up after its first 0-9 digit for some reason.
Answer: it turns out `randAlphaNum 1` in helm/sprig always starts with a number. See 9f0889c.
Answer: The logic failed as I forgot to inspect the `data` value. See f243d3c
=> Followup fixes to seed secrets PR (#1993)

dev-config.yaml, images/hub/Dockerfile, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/files/hub/z2jh.py, jupyterhub/schema.yaml, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/secret.yaml, jupyterhub/templates/singleuser/secret.yaml, jupyterhub/values.yaml, tests/test_spawn.py, tools/templates/lint-and-validate-values.yaml
- Added `hub.extraFiles` and `singleuser.extraFiles` allowing the chart users to inject files to the pods in specific locations with specific permissions (644, 400, etc).
- Added automatic loading of jupyterhub config files in `/etc/jupyterhub.d`.
- Closes #1990.
Injecting files to the hub / singleuser pods have a wide range of applications:
- To manage an external jupyterhub config file instead of embedding it to `hub.extraConfig` that. Related: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1987, https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1580.
- To mount configuration files to the user environments, such as `jupyter_notebook_config.json`, `gitconfig`, etc. Related: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1691
- To mount templates for …
=> Allow extraFiles to be injected to hub / singleuser pods and automatically load config in /usr/local/etc/jupyterhub_config.d

jupyterhub/values.yaml
This seem to work, but as I've grown cautious about Traefik's ability to reliably work as an ACME client against Let's encrypt I'm restarting the tests several times to see if there is a obvious degradation in reliability.
=> dep: bump traefik from v2.3.7 to v2.4.1

.github/workflows/test-chart.yaml
While developing Helm charts, we need to await them to become ready before running additional test than just verifying it starts up properly. Doing this requires some logic that I've extracted into a GitHub action.
1. Ability to declare / inspect k8s on what resources to await (workloads, namespace)
2. Ability to opt in to failure on detected container restarts (max-restarts)
3. Ability to time out after a total amount of time (timeout)
More details in https://github.com/jupyterhub/action-k8s-await-workloads
=> ci: use jupyterhub/action-k8s-await-workloads

jupyterhub/files/hub/jupyterhub_config.py
Closes #2022 by the implementation suggested by @minrk.
=> fix: load only .py files in jupyterhub_config.d folder

jupyterhub/templates/hub/service.yaml
Without this, the hub metrics don't seem to be
scraped.
=> Specify prometheus.io/port for hub service

.github/workflows/test-chart.yaml, jupyterhub/Chart.yaml
By relying on k8s 1.17+, we can cut away a hard to maintain
user-scheduler implementation for k8s 1.16 and earlier that is different
from the implementation we use for k8s 1.17+. See #1995.
@yuvipanda suggested holding off until GKE's stable release channel defaults to k8s 1.17, which I think will be in a week or two.
> 1.16 is still the 'stable' version listed on GKE - https://cloud.google.com/kubernetes-engine/docs/release-notes. I think we shouldn't drop support for it until 1.17 is the stable version.
=> Require k8s 1.17+ to reduce complexity

.github/workflows/test-chart.yaml, doc/source/administrator/advanced.md, jupyterhub/templates/NOTES.txt, jupyterhub/templates/ingress.yaml
Feedback greatly appreciated if this seem to make sense as I've not thought it through so much myself!
1. __Complications__
This won't cause complications for existing users, right?
1. __Customization__
Do we need to let some part of this new section be configurable in any way, and if so, in what way and why?
1. __Implementation__
Does the change technically seem to be correct?
- [v1 Ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1-networking-k8s-io) `backend` -> {`serviceName`, `servicePort`}
- [v1beta1 Ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1beta1-networking-k8s-io) - `defaultBackend` -> `service` -> {`name`, `port` -> {`name`, `number`}}
Closes #1314
=> Allow ingress.hosts to be omitted for a more generic rule

jupyterhub/schema.yaml
`list` -> `array`
`int` -> `integer`
`bool` -> `boolean`
I made some values allowed to be null also and not just string or integer.
=> Fix schema.yaml jsonschema syntax errors

jupyterhub/values.yaml
Contains a bugfix related to ACME, so potentially relevant to us.
https://github.com/traefik/traefik/releases/tag/v2.4.2
=> traefik / autohttps: bump v2.4.2 to v2.4.3

jupyterhub/README.md
This PR adds a dedicated README.md specific to the Helm chart to packaged as part of the Helm chart and be available to read [here in artifacthub.io](https://artifacthub.io/packages/helm/jupyterhub/jupyterhub).
I concluded that I preferred to not copy the local GitHub repo's README.md as it was written with various assumptions that I felt would break if read at artificathub.io. This chart specific README.md was made very lightweight to ensure we minimize required maintenance.
---
This PR closes #2011 and is the missing piece needed to continue with https://github.com/jupyterhub/helm-chart/issues/117.
=> docs: package chart specific README.md with the chart

images/hub/Dockerfile
Default shell for Docker build is `sh`, the double bracket is not supported and pip overrides wont work.
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/runs/1804962086?check_suite_focus=true#step:8:1181
I used the `test` notation as few lines below.
=> hub image build: fix use of PIP_OVERRIDES arg

.github/workflows/publish.yml
Forgot to add pyyaml as a dependency in the release workflow, which is used by the script generating the values.schema.json file before the chart is packaged.
=> ci: install pyyaml before publishing to generate json schema

doc/source/jupyterhub/installation.md
This actually really kicked my butt. The way that authentication is configured was changed between 0.10.6 and 0.11.1; I couldn't figure out why my Jupyterhub instance would accept any user/password combo without complaining, and logs seemed to show that it just wasn't loading any of my configuration at all. This was very confusing!
It would be great if this version number could be tied in to the actual released version somehow, but I think that may be too much to ask - although I'm no sphinx expert, maybe it can be done.
It would also be great if unexpected configuration keys got a warning of some kind in logs. Wouldn't have helped here, but it will help for future changes to the way things are configured.
=> doc: Update installation docs to refer to current latest version

jupyterhub/schema.yaml, jupyterhub/templates/hub/pdb.yaml, jupyterhub/templates/proxy/autohttps/pdb.yaml, jupyterhub/templates/proxy/pdb.yaml, jupyterhub/templates/scheduling/user-scheduler/pdb.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
If you want to lower the replicas of user-scheduler to 1, then you will get the same PDB issues we have had with hub/proxy (#1938) where they block upgrades etc because we have `minAvailable: 1` instead of `maxUnavailable: 1` in order to handle workloads.
=> pdb: default to maxUnavailable=1 instead of minAvailable=1

jupyterhub/templates/_helpers.tpl
`imagePullSecret.create` were to be the new `.enabled` which should still work, but it turns out that I've missed one entry making `.create` function while `.enabled` wouldn't function.
=> fix: imagePullSecret.enabled to work alongside imagePullSecret.create

.github/workflows/publish.yml, tools/set-chart-yaml-annotations.py
Closes #2044 and provides the published version of the Helm chart with artifacthub.io based vulnerability scans of our chart's images.
=> Add artificathub.io annotations to Chart.yaml before publishing

jupyterhub/README.md, jupyterhub/values.yaml
Contain some ACME bugfixes as usual.
=> traefik/autohttps: bump traefik to v2.4.5 from v2.4.2

.github/workflows/publish.yml, README.md
Followup of #2045 which worked except for I didn't make sure chartpress had updated values.yaml with relevant image tags before reading values.yaml as basis for the annotations to add to Chart.yaml.
This PR fixes that by running chartpress --skip-build before. Dummy commits ensure the chart will be republished with a new version in order to get the correct annotations in Chart.yaml and test the process works out correctly artifacthub.io
=> Fix Chart.yaml annotations for artifacthub.io image scanning

doc/source/administrator/debug.md, doc/source/administrator/upgrading.md, doc/source/jupyterhub/customizing/extending-jupyterhub.md, doc/source/jupyterhub/installation.md
- Various situations when `helm` is used such as `helm list` now requires `--namespace`.
- By adopting `<chart-version>` placeholders instead of hardcoded version strings, I consider this to close close #2041.
- I started referencing https://jupyterhub.github.io/helm-chart/ instead of https://github.com/jupyterhub/helm-chart#release-notes which get outdated quickly.
- I did some smaller docs refactoring
=> docs: helm3 compliance, avoid specification of chart versions

jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
It wasn't possible to reset the resource requests such as `hub.resources` to `null` because of our helm template logic assumed an object. This PR makes it so that if a .resources chart config value is `null`, then the resources section will be omitted.
=> Support setting resources to null to omit them

.github/workflows/test-chart.yaml
Closes #1962. We no longer need to accept test failures intermittently caused by a regression in k8s 1.20, as it is fixed in 1.20.4
=> ci: stop accepting test failures in k8s 1.20

jupyterhub/schema.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/values.yaml
This is to disable `http/80` LoadBalancer port when deploying with `offload` proxy service type.
Without this, even though the hub resides behind the https terminating proxy, `http/80` port is still available, and even reuses the cookies from `https/443` endpoint.
=> Add option to disable http port on LoadBalancer service

jupyterhub/templates/hub/rbac.yaml
=> Allow hub pod to manage k8s Secrets/Services for KubeSpawner.internal_ssl

doc/source/administrator/advanced.md
I think there are three separate problems with the documented example for injecting an environment variable into the user container environment.
```yaml
hub:
extraConfig: |
import time
c.Spawner.environment += {
"CURRENT_TIME": str(time.time())
}
```
1. The documentation claims that `extraConfig` accepts either a dict of strings or a single string (of Python code), but it actually only accepts the first one. If you give it a single string, following the documented example, it warns
```
coalesce.go:196: warning: cannot overwrite table with non table for extraConfig (map[])
```
and it does not take effect. See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/653 which seems to observe the same issue.
2. The documentation uses `+=` to update the `Spawner.environment` configurable, …
=> Fix spawner env injection example.

jupyterhub/schema.yaml, jupyterhub/values.yaml
- [mem_limit / mem_guarantee](https://github.com/jupyterhub/jupyterhub/blob/c3ca924ba896bf2da40cab29e2a08784850a945b/jupyterhub/spawner.py#L567) is a ByteSpecification, which can accept numbers, strings, and None.
- [cpu_limit / cpu_guarantee](https://github.com/jupyterhub/jupyterhub/blob/c3ca924ba896bf2da40cab29e2a08784850a945b/jupyterhub/spawner.py#L590) is a Float or None.
Closes #2068, closes #2069 which is like this PR.
=> Fix schema validation for Spawner.cpu/memory limits/guarantees

jupyterhub/templates/proxy/deployment.yaml
Restarting the proxy pod causes current user sessions to
drop until the pod restarts, the hub notices it, and sets up
all the routes again. On a hub with a few thousand users, this
can be minutes. Instead, we provide the proxy pod with just the
one key it needs, so it'll restart only if that changes.
=> Don't restart the proxy pod with each deploy

jupyterhub/schema.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
mybinder.org-deploy used to set the whole CHP command, but this is no longer allowed (not quite sure how I feel about that - pros and cons), making it impossible to override these values.
- defaultTarget ~never makes sense, but it felt weird to leave it out.
It may make sense in the future if JupyterHub develops an option
to register itself *only* as a handler for `/hub`.
This hasn't come up yet, as that behavior only makes sense when
another service is providing the default target
because requests to `/user/foo` will not behave sensibly without something handling the default route.
- errorTarget can be useful in API-only deployments like BinderHub to reduce load on the Hub
and/or show more friendly messages to users who shouldn't need to know they are using jupyterhub
=> allow override of CHP defaultTarget, errorTarget

tests/conftest.py
I think our test became a bit unstable due to a too short timeout for user pods to start. This PR increase a timeout in the CI system for user pods to startup.
Here is an example failure: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/runs/2040709684?check_suite_focus=true
=> ci: increase test timeout for test reliability

doc/source/jupyterhub/customizing/user-environment.md
The tag `177037d09156` has come up a few times recently on the Discourse forum: https://discourse.jupyter.org/search?q=177037d09156
I don't know if this is the source, but given it's ancient [(6 Aug 2018)](https://github.com/jupyter/docker-stacks/tree/177037d09156e557b334e4b3be2092e5965084d7) I think we should avoid specifying a tag here.
If you're not too keen on latest then maybe we could use a placeholder like `tag: <replace-me>` instead?
=> Don't hard-code an old tag in customizing/user-environment.md

jupyterhub/schema.yaml
The `postgres` dialect is deprecated and has been removed
in sqlalchemy 1.4, we should be using `postgresql` now. See
the discussion in https://github.com/jupyterhub/jupyterhub/pull/3383.
=> Update postgres db url dialect in schema docs

doc/source/administrator/index.md
I frequently link to the items in the Z2JH customisation section when answering posts on Discourse.
Every time _without fail_ I make the same mistake :smile: 
1. Go to the Z2JH guide https://zero-to-jupyterhub.readthedocs.io/en/stable/
2. Click on `Administrator Guide`
3. Wonder why I can't find the user storage configuration section
4. Remember it's under `Setup JupyterHub`
Does anyone else have this problem? I've added customisation under the `Administrator Guide`. The downside is a the pages appear in two TOCs so I'm happy to try any other suggestions.
=> Include customisation under "Administrator Guide"

doc/source/kubernetes/digital-ocean/step-zero-digital-ocean.md
keep cluster name consistent throughout the instructions
=> fix cluster name for DO installation instructions

doc/source/kubernetes/digital-ocean/step-zero-digital-ocean.md
Not using the version that was there gets error: 
```
Error: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 validation error: invalid version slug
```
For latest errors, calling `doctl kubernetes options versions` shows: 
```
=> doctl kubernetes options versions
Slug            Kubernetes Version
1.20.2-do.0     1.20.2
1.19.6-do.0     1.19.6
1.18.14-do.0    1.18.14
```
=> update k8 version for DO to currently available version

doc/requirements.txt
This PR makes our documentation buil on RTD functional by pinning docutils to 0.16 as the recent version 0.17 seem to have a breaking change.
I'm not sure if there is tooling that should adjust to this, for example in myst-parser or not. Perhaps knowing about this is relevant for @chrisjsewell or @choldgraf? (EDIT: woops already reported in https://github.com/executablebooks/MyST-Parser/issues/343, and haha it is Chris Sewell who reported the docutils bug but I failed to notice ;D)
The issue we ran into is reported in docutils already: https://sourceforge.net/p/docutils/bugs/415/
The build failure we experienced is available to inspect at: https://readthedocs.org/projects/zero-to-jupyterhub/builds/13469169/
I could reproduce it locally if I ran the command ran in RTD to build the docs …
=> docs: fix rtd build by pinning docutils

.github/workflows/publish.yml, .github/workflows/test-chart.yaml
- runs publish workflow for push and pull request
- moves credential-requiring conditions to individual steps instead of workflow as a whole
- on pull request, upload as artifact instead of publishing to the chart repository
This will only *fully* work if there are no changes to images in the PR, since image upload won't happen without credentials.
closes #2043
=> upload chart as github artifact

doc/requirements.txt
Following https://github.com/executablebooks/MyST-Parser/pull/344 the pinning of docutils isn't needed any more.
=> Revert docutils pin, myst-parser fixed issue

jupyterhub/values.yaml
Final piece of the checklist written down about arm64 compatible images here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2125#issuecomment-817196142
=> Bump CHP from 4.3.1 to 4.3.2 for arm64 compatibility

.github/workflows/test-docker-build.yaml, chartpress.yaml, ci/publish, dev-requirements.txt, images/hub/Dockerfile, images/secret-sync/Dockerfile
Part 1 of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2119#issuecomment-812101837: Minor changes to get Docker images building on ARM64
- `hub`: `psycopg2-binary` is not available as a precompiled binary, so `libpq-dev` needs to be installed for compilation. This increases the build time and the image size. An alternative would be to omit PostgreSQL support from the arm64 image, what do you think?
- `secret-sync`: `tini` for the correct architecture needs to be downloaded.
=> Publish Arm64 compatible images

.github/workflows/publish.yml
This is a complementary PR for #2125 that adds QEMU / Docker buildx before chartpress tries to build and publish multi-arch images.
=> publish workflow: build amd64 and arm64 prerequisites added

doc/source/administrator/index.md, doc/source/administrator/services.md, doc/source/kubernetes/amazon/step-zero-aws-eks.md, jupyterhub/schema.yaml, jupyterhub/templates/hub/service.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This can close/replace https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2132 if you prefer this direction @consideRatio, and fixes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2102
This PR adds a `hub.service.extraPorts` empty array in `values.yaml`.  If it's filled out in `config.yaml` then the array gets dropped into `service.yaml` underneath the default `name: hub / port: 8081 / targetPort: http` item.  This is pretty much identical to `proxy.service.extraPorts`.
I updated `schema.yaml` and added an example into the Administrator section below Authentication because that's the closest layout match to the [JupyterHub docs](https://jupyterhub.readthedocs.io/en/stable/reference/services.html).
@consideRatio I still don't really understand what to put in the …
=> hub.service.extraPorts config option

.github/workflows/vuln-scan.yaml
Follow-up from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2151#issuecomment-821198727
The committer defaults to `GitHub <noreply@github.com>` which is fine.
=> Set author and pin SHA in vuln-scan workflow PR

dev-config.yaml, tests/test_spawn.py
It appears that the IPs we use to test the charts network policies have become outdated. They were IPs associated with jupyter.org's webhosting, so, the new IPs are the new IPs I got from doing `nslookup jupyter.org`.
=> ci: update network tests as jupyter.org IPs changed

jupyterhub/templates/NOTES.txt
Also includes direct commands for extracting IPs/NodePort (not sure if this is too complicated? though it makes it easier for people who don't immediately understand how to parse `kubectl get svc proxy-public`)
TODO:
=> Update NOTES.txt, including removing "alpha" designation

.github/workflows/publish.yml, .github/workflows/test-docker-build.yaml, .github/workflows/vuln-scan.yaml
This PR is a followup of having the JupyterHub org's permission level of the available secrets.GITHUB_TOKEN now only have read access to the repo by default.
Along with this, I'm also pinning github actions referenced to specific hashes in the jobs requesting write permissions for the GITHUB_TOKEN.
=> ci: precautions for security, update github_token permissions, pin actions

images/hub/requirements.txt
Dependabot only updates what we have in requirements.in, but leaves the dependencies of these libraries. So, I ran `./dependencies freeze --upgrade` from the /images/hub folder to do that.
=> images/hub - a regular run of script: hub/images/dependencies freeze --upgrade

.github/workflows/test-chart.yaml
Our GitHub action to await workloads that we install have a `max-restarts` parameter. It can abort the wait process quickly if we observe issues, but setting it to `0` is a bit too strict as timings on when pod/hub restarts especially during upgrade jobs can cause the hub pod for example to restart.
For good measure, I also made the max-restarts for the non-upgrade ci jobs be 1 instead of 0 - preferring to not experience erroring ci jobs for no serious reasons even though it could make sense to also enforce they install reliably. At this point, let's go for 1 restart to be acceptable.
=> ci: accept 1 pod restart but not 2, test against k8s 1.21

jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/job.yaml
This PR helps debug an error observed by @yuvipanda related to the feature prePuller.hook.pullOnlyOnChanges that compares the checksum of the previously generated DaemonSet resource.
A comparison is made between two checksums, one that was stored from the last `helm install/upgrade` command in the hub ConfigMap, and one for the current `helm install/upgrade`. The checksum are for the hook-image-puller DaemonSet.
This PR anyhow, just emits those strings and prints them in the `hook-image-awaiter` Job and associated Pod.
=> inline comment: info about the state used by prePuller.hook.pullOnlyOnChanges

jupyterhub/templates/hub/configmap.yaml, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/rbac.yaml
Closes #2172 by the strategy described in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2172#issuecomment-832234254.
In brief:
1. the checksum of the hook-image-puller daemonset that was calculated became different based on from what template origin calculated the checksum as `.Templates.Name` changed which in turn influenced rendered labels.
2. the checksum of the hook-image-puller daemonset that was calculated became different based on .Chart.Version as found in labels as well, which was irrelevant to re-pull on.
3. the rbac resources used by hook-image-awaiter were created no matter what, but now they are created based on if the hook-image-awaiter job is created.
Note though that we do want to pull again if something has changed about node affinity etc, so instead of just …
=> fix: prePuller.hook.pullOnlyOnChanges didn't work, now it does

.github/workflows/test-chart.yaml, jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
At one point in time, `helm` installed PriorityClass resources too late - after they were referenced. Due to that, we added a workaround to make them _helm hooks_ - resources that could be installed _pre-upgrade_. The need for this workaround is long gone though, and the resources can just as well be normal resources. This PR makes them normal resources after having been helm hook resources.
I wasn't sure this would work without name collisions, but it seems like `helm` 3 manages this fine as our CI tests making a `helm` upgrade didn't have any issues.
Closes #1035.
---
Note that the commit 62b41b5 just addressed an intermittent unrelated harmless CI failure.
=> maint: revert a workaround to make our priorityclass resources helm hooks

.github/workflows/vuln-scan.yaml
```yaml
permissions:
contents: write
pull-requests: write
```
Both ability to push to a branch and create/update pull requests is required for an action in the vuln-scan workflow. This PR fixes that. It also removes some inline comments that would become outdated quickly.
=> ci: fix permissions of PR creating action

doc/source/conf.py, doc/source/index.md, jupyterhub/values.yaml
By enabling this feature by default, those with `prePuller.hook.enabled=true` will not need to wait ~10 seconds on `hook-image-awaiter` and `hook-image-puller` pods to startup and shut down if no new image has been configured.
In practice, this feature works by inspecting the rendered Helm template of the hook-image-puller DaemonSet for a change to anything besides labels since the last `helm upgrade` was made.
This feature also relies on the ability for us to lookup a value in a ConfigMap using the Helm 3 feature called `lookup`.
=> enable prePuller.hook.pullOnlyOnChanges by default

dev-config.yaml, jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
In #2180 I was on the lookout for a test failure. When I didn't see it I assumed everything was fine, but it wasn't. The failure didn't happen because `scheduling.podPriority.enabled` wasn't explicitly set to true in `dev-config.yaml`.
Due to this, #2180 introduced a breaking change after all. Instead of just reverting it fully, I've come up with a new strategy and to meet the goal that #2180 aimed for.
I want to transition a Helm hook resource (kind: PriorityClass) to become a Helm chart managed resource. I want this transition a) without manual interventions, and b) without renaming the resource.
I've found that I can do that if the users make an upgrade in two steps:
1. During a first upgrade add three ownership annotations/labels.
2. During the second upgrade step remove all hook …
=> Pivot strategy (from breaking to non-breaking) to make our PriorityClass resources no longer be helm hook resources

jupyterhub/templates/hub/_helpers-passwords.tpl
Self merging this to quicken up release process and avoid some merge conflicts after splitting apart a PR for readability.
Note that `dig` is introduced in helm 3.5.0 (via a new version of `sprig`, a helper library). `dig` allow us to simplify logic to get nested values without making the logic ugly.
Closes minor issue #2108. Publish test failure is unrelated.
=> fix: respect hub.config entries to override seeded secrets

jupyterhub/templates/NOTES.txt, jupyterhub/templates/_helpers.tpl
This fixes a bug where we could not properly use a seeded cookie secret because we had a failsafe checking that we explicitly had set a cookie secret. Since we now seed those secrets if they aren't explicitly set, this is no longer relevant.
=> fix: remove no longer needed safeguard for enable_auth_state

jupyterhub/files/hub/jupyterhub_config.py
JupyterHub 1.4.0 supports automatic hex-to-bytes conversion of hex
strings in cookie_secret now. This makes us no longer need to manually
convert the hex string to bytes.
Anyone that builds their own hub image will need to rebuild it when installing 1.0.0 after this so JupyterHub 1.4.0+ is included.
=> refactor: stop manual hex-to-bytes conversion

.github/workflows/test-chart.yaml, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-pull-secret.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, tools/templates/lint-and-validate-values.yaml
We have a `schema.yaml` file that we render into `values.schema.json` and ship with our Helm chart as supported by Helm 3. This file is a JSONSchema that covers _all our charts configuration options_ since #2033. `helm` will use it during `helm template` and `helm install|upgrade` to catch values that the schema considers invalid.
What this PR does is to start make use of a JSONSchema feature called [`additionalProperties`](https://json-schema.org/understanding-json-schema/reference/object.html#properties). With `additionalProperties: false` we can make the schema invalidate any `object` type field that declare a property that isn't declared in the schema.
Since we have declared almost all properties, we can set `additionalProperties: false` on all those `object` type fields and catch all …
=> schema: catch typos in template values using JSONSchema's `additionalProperties`

.github/workflows/publish.yml
Workaround for docker 5.0.0 not importing six but referencing six: https://github.com/docker/docker-py/issues/2807
=> ci: print pip packages versions for debugging

jupyterhub/schema.yaml
The table didn't render correctly with a lot of white space instead of `-` to create the space for the second line in the markdown table format.
=> docs: fix syntax error in markdown table

doc/source/administrator/advanced.md, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/templates/NOTES.txt, jupyterhub/templates/_helpers-auth-rework.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/secret.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
- __Complexity reduction of templates by removal of deprecation logic.__
- __Future complexity reduction of schema.__
Our deprecation messages are triggered by detecting deprecated values being passed, which requires them to be accepted by the schema. So by ensuring all users have stopped using deprecated values when they upgrade to 1.0.0, we can in 2.0.0 remove them from the schema.
All of the breaking changes will lead to clear error messages emitted by a `fail` statement in `NOTES.txt`. This happens before any communication to the k8s api-server has been made.
- Previously deprecated options that were required to be falsy, are now required to be _unset_.
- `auth` -> `hub.config`
- `hub.imagePullSecret` -> `imagePullSecret` (new chart wide config)
- `singleuser.cloudMetadata.enabled` -> …
=> Remove deprecated logic and emit clear messages

jupyterhub/values.yaml
CHP 4.4.0 dropped support for statsd metrics and added support for prometheus metrics if `--metrics-ip=<port>` is passed.
=> Bump CHP version to 4.4.0 (statsd dropped)

CHANGELOG.md, doc/source/administrator/advanced.md, jupyterhub/schema.yaml
=> Add changelog for 1.0.0-beta.1

jupyterhub/schema.yaml, jupyterhub/templates/hub/rbac.yaml, jupyterhub/templates/image-puller/rbac.yaml, jupyterhub/templates/proxy/autohttps/rbac.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
I am using this helm chart on GKE. The preferred method to authorize GKE workloads is using Google workload identity ( https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity )
In order to use workload identity it's necessary to add a specific annotation( `iam.gke.io/gcp-service-account` ) to the k8s serviceaccount. In this way we can link the k8s serviceaccount with google's service account. 
Adding annotations to the hub's serviceAccount was not possible with the current helm chart so I implemented it in this PR.
Let me know if you have any question
=> Add annotations to rbac serviceAccount

README.md
This PR adds a notice to the readme informing users that the repo is participating in an open source sustainability study, see https://github.com/jupyterhub/team-compass/issues/417 for details
=> Add participation in study notice to readme

jupyterhub/templates/_helpers-names.tpl
Closes #2250, which blocks fullname-overrides with Ingress objects
=> Fix fullnameOverride for Ingress & PriorityClass resources

images/hub/requirements.in, images/hub/requirements.txt
Based on jupyterhub's docs, it should be generally compatible with any sqlalchemy provider.
In our environment, we're relying on cocroachdb due to easier clusterization and scalability.
Aside from a tiny defect in jupyterhub (jupyterhub/jupyterhub#3484, it was not part of 1.4.1), which might not even be specific to cocroachdb (rather to the dummy authenticator), everything seems to work well.
Currently, we have to dynamically install `sqlalchemy-cockroachdb` upon container start. It'd be great to have it included in the base image.
P.S. If I got it right, I had to run the `dependencies freeze --upgrade` script to make sure all dependencies are added to the requirements.txt. That's why you can see two files updated instead of just one (requirements.in).
=> hub image: add sqlalchemy-cocroachdb dependency

.github/workflows/test-chart.yaml
runs on pre-commit.ci now
leaves shellcheck in there, which requires additional dependency and is run separately
It would be nice to bring shellcheck in so that it works like everything else. It can run in docker, but also needs the entrypoint wrapper in https://github.com/gruntwork-io/pre-commit/blob/HEAD/hooks/shellcheck.sh
=> Remove pre-commit from GHA

.pre-commit-config.yaml
This PR stops using a locally defined pre-commit hook to run chartpress that also assumes `chartpress` has been installed ahead of time. By instead using a remotely defined pre-commit hook in https://github.com/jupyterhub/chartpress/pull/127, `chartpress` will be automatically be installed by pre-commit which enables us to not crash trying to use the pre-commit.ci service.
After fixing this, I learned that the helmlint pre-commit hook also fail in the pre-commit.ci service because `helm` isn't getting installed but is assumed. Due to this, I simply opted to drop the helmlint hook instead. It is a trade off of course, but I feel a bit committed to trying out the pre-commit.ci service now and I don't think running `helm lint` as part of pre-commit is so important, it doesn't capture much …
=> Transition to use pre-commit hook in jupyterhub/chartpress

doc/source/administrator/advanced.md, jupyterhub/templates/hub/rbac.yaml, jupyterhub/templates/image-puller/rbac.yaml, jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml, jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
I'm not sure we would be able to install the Helm chart in a namespace with only numbers in its name, but now there is a change it could work at least.
=> templates: quote namespace in case they are only contain numbers

jupyterhub/schema.yaml
This will capture errors during template rendering instead of during runtime, and the errors will be easier to understand for users.
I wanted to do this as I've run into this myself and helped others several times to understand this is the root cause of an error they have received.
=> schema: force labels and annotations to be strings

jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml
Closes #2246 by allowing for `hub.db.type` schema to accept `other` as configuration.
=> Relax hub.db.type schema to accept unknown database types

jupyterhub/schema.yaml, tools/templates/lint-and-validate-values.yaml
This is a fix of a regression that stopped allowing extraEnv accepting lists. The recommended approach is to use a map, but lists were still supposed to be supported.
Closes #2290
=> Relax extraEnv schema to allow for array values

jupyterhub/schema.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
`prePuller.pause.image.name|tag` was used to set the user-placeholder pods image, but the user-placeholder pods didn't make use of the `prePuller.pause.image.pullPolicy|pullSecrets` or any other config to set imagePullPolicy or imagePullSecrets. With this PR the dedicated option `scheduling.userPlaceholer.image` and respective fields are added and respected for the user-placeholder pods.
`prePuller.pause.image.pullSecrets` was already defined in `values.yaml` but it was never actually used in the placeholder statefulset template.
=> Fix failure to set imagePullSecrets for user-placeholder pods (scheduling.userPlaceholder.image config added)

images/hub/Dockerfile
The official `ubuntu` image that we use as a base image for `hub` isn't updated so often, but various libraries in ubuntu are updated more often, where they also quite often have fixes to known vulnerabilities in them.
We have a system to detect if rebuilding the image fixes some known vulnerabilities, but in practice it requires a new ubuntu image to have been released - which is too seldom. So perhaps its worth doing `apt-get upgrade -y` to patch some known vulnerabilities in between the ubuntu image is updated?
I observed the image size grow from 625 to 631 which I assume is because some packages were upgraded, but overall it doesn't seem to make it grow substantially so I think this is worth it to more or less always end up with no known vulnerabilities whenever we rebuild the image. …
=> hub image: run apt-get upgrade by default to patch known vulns

jupyterhub/schema.yaml, jupyterhub/templates/ingress.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This adds the ability to set the pathType field on ingress rules for situations where Prefix is not available or appropriate, such as on GKE 1.19+ with the native ingress controller which only accepts 'ImplementationSpecific' as the pathType.
=> Add ingress.pathType config

jupyterhub/schema.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
Add configuration for arbitrary extra pod spec for the hub, chp, traefik and user scheduler deployments.
This change arose from a desire to deploy the hub and proxy on the host network. See PR #2300 for that discussion.
Following that conversation, I am pursuing an alternate strategy whereby we provide an escape hatch for the end user to specify arbitrary pod specification for the hub, chp, traefik and user scheduler deployments.
The extra pod specification can be provided in four locations in values.yaml:
1. hub.extraPodSpec
1. proxy.chp.extraPodSpec
1. proxy.traefik.extraPodSpec
1. scheduling.userScheduler.extraPodSpec
For example,
```yaml
hub:
extraPodSpec:
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```
=> Add configuration for arbitrary extra pod spec

doc/source/administrator/advanced.md, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml
Closes #2063 by:
- updating the documentation to reflect it must be a dictionary as have been enforced by schema in JupyterHub 1.0.0 and was deprecated in 0.8.0.
- removing logic to handle hub.extraConfig being a string in our jupyterhub_config.py file that now assumes its a dictionary instead
=> Remove deprecation logic for hub.extraConfig as a string

jupyterhub/templates/_helpers-names.tpl
If z2jh was used as a dependency helm chart, and it had an alias, this bug would happen which make template rendering fail.
As an example, the following Chart.yaml would cause an error.
```yaml
apiVersion: v2
description: irrelevant
name: irrelevant
version: 0.1.0
dependencies:
- name: jupyterhub
version: "1.0.1"
repository: "https://jupyterhub.github.io/helm-chart"
alias: dep-chart-alias
```
```
executing "jupyterhub.fullname" at <.Values.jupyterhub.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```
=> fix: bug if z2jh is used as a dependency with an alias

jupyterhub/values.yaml
- bump: traefik from 2.4.9 to 2.4.11
- bump: kube-scheduler from 1.19.10 to 1.19.13
- bump: pause image from 3.2 to 3.5
=> Bump patch version of: traefik, kube-scheduler, pause

chartpress.yaml, images/singleuser-sample/Dockerfile
This is the result of a lot of work in jupyter/docker-stacks surrounding https://github.com/jupyter/docker-stacks/issues/1019!
Thank you everyone involved! Thank you @sakuraiyuta, @holdenk, @mathbunnyru, @manics, @jiwidi, @parente, @AvverbioPronome, @step21, @akitanaka, and @romainx!
It makes me very happy to finally get the JupyterHub Helm chart 100% arm64 compatible!
Closes #2145
---
This PR can't be merged until https://github.com/jupyter/docker-stacks/issues/1411 is resolved sadly.
---
Wait what... the singleuser-sample could build without an arm64 compatible image was published? I'm not sure why that is... @manics do you think https://github.com/jupyter/docker-stacks/pull/1368 was sufficient? I'm very confused why the build of our singleuser-sample with arm64 succeeded if has a FROM …
=> Add support for arm64 in singleuser-sample image

jupyterhub/schema.yaml, tools/templates/lint-and-validate-values.yaml
The schema was too strict by mistake and didn't allow for any values to be passed to `proxy.traefik.extra[Static|Dynamic]Config`.
=> fix schema: accept proxy.traefik.extra[Static|Dynamic]Config

.github/workflows/test-chart.yaml, jupyterhub/templates/proxy/deployment.yaml
This changes relies on CHP 4.5.0 that was patched with https://github.com/jupyterhub/configurable-http-proxy/pull/333 to be able to listen to all available network interfaces, IPv4, IPv6, or both.
---
I note that code in CHP, that is influenced by how Z2JH configures CHP via flags, could potentially be set differently to avoid issues in different contextswhere IPv4/IPv6 either both or only one is available. I consider this due to the discussion in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2254#issuecomment-878951182.
I created this PR to trial if setting `--ip=` to a blank string would make a difference. I consider this because of @minrk's comment saying `Preferred usage is 0.0.0.0 for all IPv4 or '' for all-interfaces.` and was thinking that all-interfaces may …
=> Allow CHP to function in a IPv4 only and/or IPv6 only context

.github/workflows/publish.yml, .github/workflows/test-chart.yaml, .github/workflows/test-docker-build.yaml, dev-config.yaml
- Chartpress now includes a workaround that made us need to install `six` before.
- `helm` ships with the GitHub actions environment and doesn't have to be installed there if we want a very recent version.
- Removed patches for upgrade tests needed to not make them break before 1.1.0 was released.
=> ci: misc fixes post 1.1.0

doc/source/administrator/authentication.md, jupyterhub/schema.yaml, tools/templates/lint-and-validate-values.yaml
While trying to set `templateVars` we can't set additionalProperties, this PR fixes that
A minimal example
```
hub:
templateVars:
announcement: 'Some Text'
```
and deploying with
```
helm upgrade --install jhub jupyterhub/jupyterhub --version=1.1.1 --values config.yaml
```
fails the lint with the current schema.
=> additionalProperties should be set to True for templateVars in the schema

doc/source/administrator/authentication.md
* This PR updates the documentation to reflect the addition
of [GitHub team based authentication to OAuthenticator](https://github.com/jupyterhub/oauthenticator/pull/449)
=> Add docs on GitHub team authentication

jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/netpol.yaml, jupyterhub/templates/hub/pvc.yaml, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/ingress.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/autohttps/netpol.yaml, jupyterhub/templates/proxy/autohttps/service.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/templates/scheduling/_scheduling-helpers.tpl, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/templates/singleuser/netpol.yaml, tools/templates/yamllint-config.yaml
In the past `toYaml` created a new line that we trimmed away - but I contributed a fix to that in helm/helm so now it doesn't in the modern versions of the `helm` CLI which the JupyterHub helm chart now require anyhow :)
=> refactor: remove redundant trimSuffix of new lines after toYaml

CHANGELOG.md
Ping @sgibson91 - a patch release like this can be released by merging this changelog and then tagging 1.1.3 and pushing the tag. Go for it?
=> Add changelog for 1.1.3

dev-config-arm.yaml
We have a arm compatible singleuser image at this point in time, no need to override it.
=> Remove no longer needed arm test adjustment

doc/source/kubernetes/other-infrastructure/step-zero-microk8s.md, doc/source/kubernetes/setup-kubernetes.md
Hello! I was able to get the Zero to JupyterHub chart working on bare metal using MicroK8s. I teach at a community college and I have a number of servers that I can use for my classes which I consider pre-paid instance hours. This pull request documents the process of setting up MicroK8s so that the helm chart applies cleanly. 
I am grateful for all of the work you've done with this project. I hope that this documentation gives some folks access to it using infrastructure that they're familiar with and have already paid for. 
Please let me know if there are any fixes or changes you'd like.
=> Documenting Microk8s cluster type.

.github/workflows/test-chart.yaml
This ensures we're testing whether persistent data like the database is actually upgraded- `sqlite-memory` is not persisted when the hub restarts.
Best verified using https://github.com/jupyterhub/action-k8s-namespace-report/pull/11
e.g.
In future we could add tests to verify the persistent volumes, especially singleuser volumes, are correctly maintained across upgrades.
=> ci: use PVCs when testing upgrades

doc/source/jupyterhub/customizing/user-environment.md
show how to use classic notebook, new server, juptyerlab, and retrolab.
- consistent config, works for both 1.x and 2.x, no matter what the default is
- examples covered: notebook, lab, lab on legacy server, nbclassic, and retrolab
cf #776
=> example configurations for UI choices

.github/workflows/test-chart.yaml
In z2jh where we have kube-scheduler configured and running with a pinned k8s version binary, I think its relevant to run test against all k8s versions we support. In this PR I add the recent 1.22 available for k3s.
To clarify why it can be relevant to test all k8s versions we support, consider if our kube-scheduler binary is updated. It may start to fail to function on older versions of k8s because of how it speaks with the k8s api-server and such to schedule the pods. kube-scheduler the binary of a certain k8s release is supposed to function with k8s versions +-1 minor version, but we use one version against all the k8s versions we support. I've had some issues in the past with this, so due to that, I support testing all k8s versions in z2jh specifically.
Sibling PR to …
=> ci: test against k8s 1.22

.github/workflows/test-chart.yaml, jupyterhub/schema.yaml, jupyterhub/templates/ingress.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
Closes #2380 that contains details about the need for this PR.
=> Add ingress.ingressClassName config option

.circleci/config.yml, .github/workflows/test-chart.yaml, dev-config-local-chart-extra-config.yaml, dev-config.yaml, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/values.yaml, tests/conftest.py, tests/test_hub.py, tools/templates/lint-and-validate-values.yaml
The motivation for adding a dedicated chart configuration is that
hub.config.JupyterHub.load_roles would end up being overridden easily if
configured from multiple config files. So, having a dictionary
configuration for the same thing can help.
An example for when this would be relevant is the BinderHub helm chart. It defines a hub.service and will want to define a hub.loadRole as well. But then what happens if a user wants to configure the BinderHub Helm chart? The user will end up having overridden BinderHub's config of the JupyterHub Helm chart.
I've deliberated a while on this, and some comments are made in #2386 about it.
=> Add hub.loadRoles configuration

jupyterhub/templates/proxy/deployment.yaml
We had values and schema documenting these, but we didn't have an actual implementation for the proxy pod active.
Closes #2415.
=> Fix proxy pod's liveness/readiness probes to be fully configurable

doc/source/jupyterhub/customizing/user-environment.md, jupyterhub/schema.yaml
Following [1] and other instances in the same doc
this fixes the typo on the env var to set to use
jupyter-server in the singleuser server pod.
Also make the retro example set the env var value
in a quotes since it's a string.
Also fix the docs linkcheck job failure while in here.
[1] https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#switching-to-jupyter-server
=> Fix docs typo

doc/source/kubernetes/other-infrastructure/step-zero-microk8s.md
The `microk8s enable metallb` command previously listed there gives me the following error:
```
Your input value (10.0.0.100-200) is not a valid IP Range
```
Tested on my workstation (Ubuntu 20.04.3 LTS `x86_64`, kernel 5.11.0-41-generic, microk8s 1.22.4 installed with snap from "1.22/stable" channel).
=> Update MetalLB section in step-zero-microk8s.md

doc/source/administrator/upgrading.md
This should also fix the failing linkcheck.
=> Link to Discourse instead of the mailing list

doc/source/jupyterhub/customizing/user-environment.md
People are going to copy and paste, so use `latest` instead of a fixed tag in the example.
=> Don't pin example jupyter/minimal-notebook

jupyterhub/values.yaml
- deps: bump traefik from 2.4.11 to 2.5.6 (autohttps pod)
- deps: bump kube-scheduler 1.19.13 to 1.19.16 (user-scheduler pod)
- deps: bump pause image from 3.5 to 3.6 (pre-puller pods)
=> deps: update traefik, kube-scheduler, and pause image

jupyterhub/templates/scheduling/priorityclass.yaml, jupyterhub/templates/scheduling/user-placeholder/priorityclass.yaml
Thanks to preparing for this in 1.0.0, assuming all users will stop-gap upgrades to the Helm chart 2.0.0 by first upgrading to 1.0.0, we can stop using a workaround needed because `helm` didn't handle PriorityClass resources correctly in the past.
The workaround was that the PriorityClass resources managed by this Helm chart was installed as a "helm hook", which means that they were not really managed by Helm as one would expect. For example, without this fix, uninstalling the helm chart would mean that the priorityclass resources would remain.
---
Since this is tested reliably in the upgrade tests, I'll go for a quick self-merge and update the changelog for 2.0.0 i'm writing.
=> Remove workaround to have PriorityClass resources as helm hooks

jupyterhub/templates/_helpers.tpl
I saw https://github.com/jupyterhub/binderhub/pull/1444 and figured reusing the helper template in this helm chart was the way to do it, because then binderhub could make use of the functionality defined in this Helm chart to both create and reference a k8s Secret with image registry credentials for the various pods.
I think https://github.com/jupyterhub/binderhub/pull/1444 can be merged as it is, but think of this as the long term solution rather than a short term fix. BinderHub would need to make a version bump of the jupyterhub helm chart to include a release with this PR merged.
Note that most lines changed are indentation changes, focus your attention on 98df189c5c46e6f99b4ef10aed3c59d67b547f38 instead of the other commit.
- About using this Helm chart to create a k8s Secret with …
=> Enable parent chart's (binderhub etc) to use imagePullSecrets helper

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
**Improves** a formatting in the **nodeSelector** section in the final template.
**Previous behavior:**
When generating a helm template, the **toJson** function is applied to all nodeSelectors. The final template looks like this:
```
bash:
helm template . | grep nodeSelector
result:
nodeSelector: {"key1":"singleuser"}
nodeSelector: {"key1":"hub"}
nodeSelector: {"key1":"proxy.chp"}
nodeSelector: {"key1":"scheduling.userScheduler"}
nodeSelector: {"key1":"singleuser"}
nodeSelector: {"key1":"singleuser"}
nodeSelector: {"key1":"prePuller.hook"}
```
**Behavior after PR:**
After applying the changes, the fragment of the final template will look like this:
```
bash:
helm template . | grep -A 1 nodeSelector
result:
nodeSelector:
key1: singleuser
--
nodeSelector:
key1: hub
--
nodeSelector:
key1: …
```
=> Improved nodeSelector formatting in template

images/image-awaiter/Dockerfile
Update to golang:1.17 base image to patch 1 critical and 5 high vulnerabilities
=> image-awaiter: fix known vulns. by updating to golang:1.17 in image build stage

docs/requirements.txt, docs/source/administrator/optimization.md, docs/source/administrator/upgrading.md, docs/source/resources/community.md
Sphinx 4 has made the linkcheck emit a warning about broken internal references. This PR fixes those.
It also updated an outdated comment in the docs requirements.txt file.
=> Fix broken internal references in docs

jupyterhub/schema.yaml
The `$schema"` key has a random `"`
=> Remove typo " in schema.yaml

.github/workflows/test-chart.yaml, jupyterhub/schema.yaml, jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
If you have configured `scheduling.userScheduler.plugins`, this is a breaking change.
- When k8s <=1.20 is used, you can no longer influence the configuration via `scheduling.userScheduler.plugins`. The previous default configuration is now hardcoded for this scenario.
- When k8s >=1.21 is used, `scheduling.userScheduler.plugins` configuration should be updated to be compatible with a KubeSchedulerConfiguration of kind `v1beta3`.
As new k8s versions arrive, we should try ensure that our user-scheduler that schedules some of our pods, that relies on a k8s official kube-scheduler binary - is updated as well.
This PR bumps the kube-scheduler binary version we rely on in k8s clusters versioned 1.21 or higher to the kube-scheduler binary v1.23.4, and the associated configuration to be of a …
=> Update user-scheduler's kube-scheduler binary and config when in k8s clusters versioned >=1.21

jupyterhub/templates/proxy/autohttps/deployment.yaml
The `resources` property was not being set in the secret-sync container configuration. This is a configurable property that is described in the zero-to-jupyterhub configuration docs.
=> Fix failure to respect proxy.secretSync.resources configuration

.github/workflows/test-chart.yaml, docs/source/administrator/advanced.md, docs/source/resources/glossary.md, jupyterhub/Chart.yaml, jupyterhub/schema.yaml, jupyterhub/templates/hub/pdb.yaml, jupyterhub/templates/ingress.yaml, jupyterhub/templates/proxy/autohttps/pdb.yaml, jupyterhub/templates/proxy/pdb.yaml, jupyterhub/templates/scheduling/user-placeholder/pdb.yaml, jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
This PR closes #2591 by requiring k8s 1.20+ and dropping support for k8s 1.17-1.19 that are no longer supported by the major cloud providers.
As part of this, I also do some cleanup to not test against old versions, remove misc conditionals to support old versions, and updates misc documentation references found to old versions.
=> Require k8s 1.20+ and small cleanups based on assuming it

jupyterhub/schema.yaml
The help text refers to `hub.service.type`, but this isn't hyperlinked:
When you find `hub.service.type` there's no information, you're directed to the k8s docs.
=> `proxy.service.type`: link directly to k8s docs

jupyterhub/schema.yaml, jupyterhub/templates/_helpers-names.tpl, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/priorityclass.yaml, jupyterhub/values.yaml
I wanted to push a commit to #2574 but wasn't allowed to, due to that I decided to open a new PR built on top of #2574. @a3626a is this okay with you?
I've rebased @a3626a's commit from #2574 and added another commit with changes I wanted to see.
This PR adds another PriorityClass resource that [hook|continuous]-image-puller pods can reference in order to acquire a priority making them considered more important than user placeholder pods but still not more important than normal user pods. In practice, this resolves a bug where we could have too many user placeholder pods to fit a image-puller pod and end up with a node that didn't get their image pre-pulled for users.
I labelled it as a bugfix, its kind of a new feature as well - intended to fix a bug in behavior.
=> Enable image-puller pods to evict user-placeholder pods

.github/workflows/watch-image-dependencies.yaml
Closes #2419 and tested to work in a fork already.
I've added a note about the need to close/reopen PRs created like this until we have setup a personal access token to a bot account, as that is required to trigger tests automatically.
=> ci: add automation to update chp and traefik images

.github/workflows/watch-dependencies.yaml, jupyterhub/values.yaml
A continuation of #2694 and #2696 to open PRs to bump the kube-scheduler and pause images this helm chart references as well. Now every image used by the Helm chart is automatically bumped.
---
I've tried this PR on a fork besides the PR title change commit.
=> ci: automatically bump kube-scheduler and pause image tags

.github/workflows/watch-dependencies.yaml
This is a followup PR to #2698 that didn't manage to function flawlessly.
1. We triggered the watch dependencies workflow on merges, which I think led to a duplicated PR to bump an already bumped version.
2. We had an outdated comment about what the workflow did, only mentioning bumping two specific images.
3. We had an issue where we bumped to `traefik:2.7` from `traefik:2.6.6` which could have made sense - but doesn't for the `traefik` image that use that `major.minor` version to include pre-releases as well - and we don't want to bump to an unstable version.
=> ci: followup tweaks to dependency bumping automation

.github/workflows/vuln-scan.yaml, .github/workflows/watch-dependencies.yaml
This is associated with discussion in https://github.com/jupyterhub/team-compass/issues/516. The wish is to trigger relevant GitHub test workflows when we open new PRs, which a PR opened with a `secrets.github_token` wouldn't do.
=> ci: use jupyterhub-bot PAT to trigger github workflow on opened PRs

jupyterhub/schema.yaml
When responding to https://discourse.jupyter.org/t/sql-operationalerror-with-jh-default-config/12207/3 I realised the Z2JH docs on setting the storage group ID are a bit unclear.
- [`singleuser.fsGid`](https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-fsgid) links to https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html
- https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html doesn't contain `fsGid` so searching for it doesn't work, the property is called `fs_gid`.
- `fs_gid` maps to the K8S property `fsGroup` which is relevant when investigation cloud storage volume permissions.
It'd be nice if we could link directly to `fs_gid` in https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html but it doesn't have …
=> docs: document `singleuser.someConfig` by linking to `KubeSpawner.some_config` docs

jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
I could not push to #2663 so I'm opening this PR to complement it with required parts. Closes #2663, ping @snickell!
---
I'm a bit unhappy about adding another dedicated passthrough config to the helm chart, but I'm also afraid of the work to champion the use of hub.config.KubeSpawner at this point. I'm afraid of the effort to clarify what can and can't be set there without trouble. Some configuration has been used both by helm chart templates, and by the jupyterhub_config.py file, and that config must still be read from the dedicated config values etc.
=> Add singleuser.allowPrivilegeEscalation for KubeSpawner 2+

images/image-awaiter/Dockerfile, images/image-awaiter/go.mod, images/image-awaiter/go.sum
- Move to a newer go version
- Move to a newer version of the HTTP client we use
=> Bump versions of image-awaiter dependencies

docs/requirements.txt, docs/source/conf.py
Jupyter readthedocs sites are often referenced on the [Jupyter Discourse](https://discourse.jupyter.org/). The lack of Open Graph tags means link previews aren't useful, e.g. in the compose mode
This uses [sphinxext-opengraph](https://github.com/wpilibsuite/sphinxext-opengraph) as suggested by @choldgraf in https://github.com/pydata/pydata-sphinx-theme/pull/664
=> Add opengraph tags

.github/dependabot.yaml, .github/workflows/vuln-scan.yaml
The vulnerability scan PRs have been too noisy, and bumping github actions' versions isn't important to do fast I think. I've made them happen weekly instead of daily as part of this PR.
=> ci: reduce frequency of gha/vuln bumps

.github/dependabot.yaml, jupyterhub/templates/hub/pdb.yaml, jupyterhub/templates/proxy/autohttps/pdb.yaml, jupyterhub/templates/proxy/pdb.yaml, jupyterhub/templates/scheduling/user-placeholder/pdb.yaml, jupyterhub/templates/scheduling/user-scheduler/pdb.yaml
Closes #2649 as reported by @geoffo-dev, where policy/v1 seems to be available in the k8s cluster event though policy/v1 PodDisruptionBudgets only come around in k8s 1.21.
I was on track to get this done across other repos, and went along and did it also for this repo. The actual work was not making the PR, it was to realize there is a bug like this. Thank you @geoffo-dev!
=> Fix for PDBs in k8s 1.20

dev-config-local-chart-extra-config.yaml, dev-config.yaml, docs/source/administrator/security.md, jupyterhub/schema.yaml, jupyterhub/templates/_helpers-netpol.tpl, jupyterhub/templates/hub/netpol.yaml, jupyterhub/templates/proxy/autohttps/netpol.yaml, jupyterhub/templates/proxy/netpol.yaml, jupyterhub/templates/singleuser/netpol.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
`<hub|proxy.chp|proxy.traefik|singleuser>.networkPolicy.egressAllowRules` is introduced. They are meant to help adjust the created NetworkPolicy resource rules with a few convenient true/false values. They are all set to true by default besides for the singleuser NetworkPolicy governing the user pods. Using the default configuration, user pods are no longer granted access to [PrivateIPv4 addresses](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses).
Also note that with the introduction of the `egressAllowRules`, the configuration to allow outbound network connections moved from `.egress` to `.egressAllowRules`. This means that if users have configured `.egress` previously to not be as permissive, they may experience a permission escalation by having `.egressAllowRules` …
=> breaking: add ...networkPolicy.egressAllowRules and don't allow singleuser pods to access PrivateIPv4 addresses by default

.pre-commit-config.yaml, docs/source/conf.py, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/files/hub/z2jh.py, tests/conftest.py, tools/compare-values-schema-content.py, tools/generate-json-schema.py, tools/set-chart-yaml-annotations.py, tools/templates/lint-and-validate.py, tools/validate-against-schema.py
While this suddenly assumes the hub pod has py38+ and it could be seen as a breaking change, I don't think we should write about this in the changelog, as that version is considered internal.
What is a breaking change worth mentioning though is a transition from Python 3.8 to Python 3.9 within the hub image, see #2733.
=> maint: add pre-commit isort hook, and let pyupgrade assume py38+ in hub container

images/singleuser-sample/Dockerfile, jupyterhub/schema.yaml, jupyterhub/templates/_helpers-names.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/rbac.yaml, jupyterhub/templates/hub/serviceaccount.yaml, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/image-puller/rbac.yaml, jupyterhub/templates/image-puller/serviceaccount.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/autohttps/rbac.yaml, jupyterhub/templates/proxy/autohttps/serviceaccount.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml, jupyterhub/templates/scheduling/user-scheduler/serviceaccount.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This feature introduces a new `.serviceAccount.create` for all
`ServiceAccount` resources, which defaults to `true`. This is a breaking
change for all users with `rbac.enabled` set to `false`, as these users will get some ServiceAccount resources created where they previously ran as the default user.
For context, please see the discussion at https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2691 .
The use-case for this feature is to allow users who use `rbac.enabled=false` to provision `serviceAccounts` without rbac resources like `Role` and `RoleBinding`. It also limits the `rbac.enabled` to only refer to resources that relate to the actual rbac API in kubernetes.
=> feat: Implement `serviceAccount.create`

jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/values.yaml
See https://discourse.jupyter.org/t/jupyterhub-removes-admin-when-cull-is-used/12976
Note I haven't tested this.
=> Support idle culler --cull-admin-users

docs/source/jupyterhub/customizing/user-management.md
The current link results in a 404. It looks like is just missing the `.md` extension.
=> Fix link to authentication guide

docs/source/administrator/security.md, jupyterhub/schema.yaml, jupyterhub/templates/NOTES.txt, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/rbac.yaml, jupyterhub/templates/image-puller/rbac.yaml, jupyterhub/templates/proxy/autohttps/rbac.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
To use `rbac.create` instead of `rbac.enabled` has been a common suggestion over time as that is how most other Helm charts have named this configuration, so like this we will better align with the common practice.
This is a followup PR to #2736 that changed the behavior of `rbac.enabled` in a way that motivated some breaking change documentation in the changelog. As part of that, I figured it could be motivated to also transition `rbac.enabled` to `rbac.create` and force users having declared `rbac.enabled` to adjust to the change.
Previously, `rbac.enabled` was handling both the creation of Role/RoleBinding and ServiceAccount resources, while after #2736 it is only managing the Role/RoleBinding resources. With this PR, users that has configured `rbac.enabled` explicitly, either true or …
=> breaking, maint: replace rbac.enabled with rbac.create

jupyterhub/schema.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/values.yaml
This is a generic pattern to allow user annotations on the resulting pods.
The specific use case I have is adding `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"`. A snippet from the [cluster-autoscaler docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node):
>    What types of pods can prevent CA from removing a node?
>    - Pods with local storage. *
>    *Unless the pod has the following annotation (supported in CA 1.0.3 or later): "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
and what I see in the autoscaler logs:
```
Fast evaluation: node ip-10-10-10-10.us-west-2.compute.internal cannot be removed: pod with local storage present: user-placeholder-0
```
- EKS 1.22
- …
=> Add scheduling.userPlaceholder.annotations

jupyterhub/schema.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml
This is a generic pattern to allow user annotations on the resulting pods.
The specific use case I have is adding `sidecar.istio.io/inject: 'false'`. 
#2576 says it all and this implements the resolution in the [last comment](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2576#issuecomment-1035852061). I'm running with Istio.
- EKS 1.22
- Istio 1.13.3
- Zero-to-JupyterHub Chart 1.2.0
- Istio is enabled in the namespace where all the Jupyter stuff is.
=> Add scheduling.userScheduler.annotations

.github/workflows/test-chart.yaml, ci/common, dev-config.yaml, docs/source/administrator/upgrading/index.md
Adds a test of `hub.db.upgrade` for PostgreSQL. This requires pinning an old chart that requires a schema upgrade, in general stable will be too close to dev for there to be an upgrade.
Adds docs on why the upgrade isn't automatic for other DB provides.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2783
=> Test postgres schema upgrade in CI

.github/workflows/test-chart.yaml
Closes #2799 via a workaround patch. https://github.com/jupyterhub/action-k3s-helm/issues/59 is opened still to track possible further actions, but I'd like to avoid adding a workaround in that repo unless its clear this isn't going to resolve in k3s or some further time passes without resolution.
=> ci: workaround intermittent test failures pending upstream fix in k3s 

jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
user-scheduler support both kubernetes before 1.20 and after 1.21. It is done by helm conditionals `if ge (atoi .Capabilities.KubeVersion.Minor) 21`
`.Capabilities.KubeVersion.Minor` is not a simple number in AWS EKS environment. It is something like `22+`. So backward compatibility fallback is applied to every kubernetes clusters even if its version is greater than 1.20.
I suggest simple solution just to replace every `+` signs into empty string `''`. Helm `replace` function can do this.
[`semverCompare`](https://helm.sh/docs/chart_template_guide/function_list/#semvercompare) can achieve better result, but I am worried about its unexpected behaviors. It changes things a lot.
Refer this image for various Helm expression results.
=> Fix user-scheduler backward compatibility for AWS EKS

jupyterhub/schema.yaml
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2808
`scheduling.userScheduler.plugins` configures kube-scheduler for better scheduling of singluser pods. kube-scheduler support various extension points like queueSort, preFilter, filter, postFilter, preScore, score, reserve, permit, preBind, bind, multiPoint. However current implementation uses and allows only _score_.
Therefore, I suggest to allow other extension points.
Allow additional properties for `scheduling.userScheduler.plugins`
=> Allow additional properties for scheduling.userScheduler.plugins

docs/source/administrator/upgrading/upgrade-1-to-2.md, docs/source/jupyterhub/customizing/user-environment.md, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/schema.yaml, jupyterhub/values.yaml
update docs to explain explicit `cmd: null` use case, which works now (unlike when #2449 came in, I think)
reverts #2449
closes #2805
=> Restore jupyterhub-singleuser as the default command

jupyterhub/schema.yaml, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
Users need to be able to control how many old ReplicaSets are retained. Some users prefer to keep minimum number or even zero to clean up clutter (ArgoCD for example) or if they use `helm rollback` instead of kubectl rollout undo to roll back.
Added revision history limit property to all deployments and added default of 10 to values file.
=> Add revisionHistoryLimit to all deployments

.github/dependabot.yaml
I've not seen dependabot refreeze and keep a requirements.txt that is associated with a requirements.in updated.
So, there is instead now a [refreeze requirements.txt job in the watch-dependacies workflow](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f133567f9f739c8e7c3b3e7ee0476a1ecb1b1134/.github/workflows/watch-dependencies.yaml#L186-L233) that can be used. So, I suggest removing this dependabot bumping that doesn't seem to keep the frozen requirements.txt packages updated.
=> ci: remove dependabot bumping for hub image's req file

.github/workflows/watch-dependencies.yaml, images/hub/requirements.in
This PR makes us bump to pre-releases of jupyterhub automatically, and to as part of that PR also make sure we refreeze the dependencies in requiements.txt if jupyterhub was bumped. The refreezing part makes us duplicate code a bit, but I think it should be fine. I added a note about it.
Fixes #2828 and addresses https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2827#issuecomment-1203718287.
---
While this version bumping automation is a bit complicated, I like that it makes us codify knowledge on chore maintenance tasks so anyone can do it quickly.
=> ci: fix jupyterhub version bumping automation

.github/workflows/test-chart.yaml
With v3.0.1 of https://github.com/jupyterhub/action-k3s-helm released that includes a workaround for an intermittent issues in k3s, we no longer need to apply a workaround directly in this repo.
Correction: with v3.0.2 of action-k3s-helm things work for all k8s versions properly. Correction again, v3.0.3 should do the trick finally!
=> ci: remove no longer needed workaround for action-k3s-helm

.circleci/config.yml
We had hard to debug errors in circleci's arm tests. Not confident on what goes wrong or how to handle that, I figured we would apply a workaround applied to action-k3s-helm we maintain in the jupyterhub org as well here.
=> ci: add workaround for k3s in circleci tests as well

images/hub/Dockerfile
ruamel.yaml.clib now ships with a aarch64 wheel!
=> hub image: remove workaround for ruamel.yaml.clib on aarch64

docs/source/jupyterhub/customizing/user-environment.md
At section `Modify your config.yaml file to specify the image`. This corrects following error when running helm upgrade using incorrect config:
```Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
jupyterhub:
- singleuser.image: Additional property cmd is not allowed
=> Corrected indentation in the config.yml example

.circleci/config.yml, .github/workflows/test-chart.yaml, images/hub/Dockerfile, images/singleuser-sample/Dockerfile
- avoids copying wheels, eliminating the need to track which need compilers on arm and select those for the build stage. The build stage can now be much simpler and build all wheels
- mount pip cache as a cache dir, so cache can be used without polluting the image
Requires buildkit for `--mount`
results: smaller images (when compared with the simpler `COPY --from` for all wheels, negligible difference with the more complex, optimized build stage), simpler Dockerfiles (no need to pick 'needs compile on arm' images for the build stage), faster rebuilds (cache is actually used, which saves a lot of time)
=> Mount wheels from build stage instead of copying

.github/dependabot.yaml
We have a dedicated github workflow to smoothly update requirements that
runs on a schedule and can be run manually if needed as well. When it is
run, a PR will be created updating the requirements.txt file based on
the requirements.in file using `pip-compile`.
Closes #2858
=> ci: disable dependabot bumping singleuser-sample deps

RELEASE.md, chartpress.yaml, dev-requirements.txt, tbump.toml
- require chartpress 2 in dev-requirements (previous unbounded pinning meant we were using it already as soon as it shipped)
- set baseVersion in chartpress.yaml
- note baseVersion bump in release process
One bit of the new chartpress 2.0 process that may be useful, but I'm not sure where to write it down: since we publish versions continuously, we should bump the baseVersion e.g. 2.1.0-0.dev -> 3.0.0-0.dev in the first 'breaking' PR. It's not the _most_ important thing to get exactly right, but it will be easy to overlook. Arguably,w e could do the same for 2.0.1 -> 2.1.0 fr the first new thing. Alternately, we could always start with '3.0.0-0.dev' to indicate 'might be breaking' so we don't have to pay attention so much in mid-development.
=> Update chartpress to 2.1+ and adopt tbump in the release process

docs/source/changelog.md
Everything is ready for the major release I think!
- Closes #2743 
- Closes #2386
---
The linkcheck failure should resolve once merged, its a reference to the 2.0.0 tag that isn't around yet.
---
UPDATE: 
- Updated in #2868.
=> Update changelog for 2.0.0

docs/source/administrator/authentication.md
The JupyterHub default auth doesn't matter, it's the Z2JH default that's important.
=> docs: auth defaults to dummy

docs/source/administrator/authentication.md
Current Keycloak version is 19. Versions 17+ do not have `/auth` in their URLs https://www.keycloak.org/migration/migrating-to-quarkus
=> docs: remove /auth from keycloak URLs

docs/source/conf.py
The linkcheck is currently broken as
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/78e20694b3fca1d0dfa7ca2dcbc45625440b62a5/docs/source/conf.py#L70
expands to
`https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/2.0.1-0.dev.git.5810.hf475e7a4/images/hub/requirements.txt`
=> docs: fix git sha lookup for dev builds

jupyterhub/values.yaml
There are no GitHub releases, only tags
=> values.yaml: fix link to configurable-http-proxy releases

.github/workflows/vuln-scan.yaml
This is a followup to an optimization made by Min that started using `--mount` as part of `RUN` in some Dockerfiles. It requires buildkit, which needs to be manually enabled.
=> ci: enable buildkit for vuln scan workflow as needed for --mount

docs/source/changelog.md
Independent on removing GitHub Releases as suggested in #2861, we should probably make the changelog the source of truth with regards to changes. Currently, we have git tag descriptions, GitHub Release descriptions, and the changelog entries.
It seems that GitHub Releases were adopted with v0.4 and onwards from which we have equivalent changelog entries with details already, but there were also bundled information in the git tags going back all the way to v0.1, v0.2, v0.3, v0.3.1.
So what this PR does, is to make the git tag messages for 0.1-0.3.1 be visible in the changelog, but it seems we can already delete the GitHub Releases without discarding relevant knowledge.
=> docs: backfill early changelog entries based on git tags and github releases

docs/source/changelog.md
PR #2449 was reverted by #2820 before release, and should not be mentioned in the changelog as a breaking change. 
The reversion should be kept in the changelog, as it brought new functionality in addition to reverting the unreleased changes. Added a note referencing the reverted change for posterity. Not sure if the note is in a good spot, feel free to suggest a better place for it.
=> docs: Remove unreleased reverted change from 2.0.0 release changelog

.github/workflows/watch-dependencies.yaml, jupyterhub/values.yaml
I've got some errors about k8s.gcr.io and googled my way to find that its been deprecated, see https://github.com/kubernetes/kubernetes/pull/109938 for example.
=> Switch from deprecated k8s.gcr.io to registry.k8s.io

.github/workflows/publish.yml, .github/workflows/test-docker-build.yaml
It is more messy than needed to bump minor/patch when we can pin the major anyhow.
- Closes #2912
- Closes #2913
=> ci: bump docker action versions to v2 from v2.x.y

.github/workflows/release-tag.yml, RELEASE.md
Alternative solution for https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2861 which avoids disrupting anyone who was relying on GitHub releases.
I've tested this in
https://github.com/manicstreetpreacher/github-api-test/blob/main/.github/workflows/release-tag.yml
by manually pushing tags `0.0.1-test` and `0.0.1`, resulting in
https://github.com/manicstreetpreacher/github-api-test/releases
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2861
=> ci: Auto-create GitHub release when repo is tagged

.github/workflows/test-chart.yaml, chartpress.yaml, docs/source/administrator/security.md, images/hub/Dockerfile, images/hub/requirements.in, images/hub/requirements.txt, images/singleuser-sample/Dockerfile
The jupyterhub/k8s-hub-slim image is tested in the (stable, install) job now - it works fine and I think we don't need anything more in tooling etc, just another chartpress.yaml configuration entry.
This PR stems from a discussion in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2917#issuecomment-1293465924. It also made me discover a chartpress bug in https://github.com/jupyterhub/chartpress/issues/189.
Image | Size
-|-
(current) | 413 MB
Debian slim | 256 MB
Debian fat | 414 MB
Image | Size
-|-
(current) | Total: 625 (UNKNOWN: 4, LOW: 16, MEDIUM: 131, HIGH: 454, CRITICAL: 20)
Debian slim | Total: 95 (UNKNOWN: 0, LOW: 12, MEDIUM: 39, HIGH: 40, CRITICAL: 4)
Debian fat | Total: 625 (UNKNOWN: 4, LOW: 16, MEDIUM: 131, HIGH: 454, CRITICAL: 20)
It seems we may end up with a …
=> Add a jupyterhub/k8s-hub-slim image alongside jupyterhub/k8s-hub

.github/workflows/test-chart.yaml, docs/source/changelog.md, jupyterhub/Chart.yaml, jupyterhub/templates/hub/pdb.yaml, jupyterhub/templates/proxy/autohttps/pdb.yaml, jupyterhub/templates/proxy/pdb.yaml, jupyterhub/templates/scheduling/user-placeholder/pdb.yaml, jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/templates/scheduling/user-scheduler/pdb.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
- Closes #2935 by dropping support for k8s 1.20 that is no longer supported by cloud managed k8s clusters (GKE, EKS, or AKS).
- As part of dropping that support, we this PR also cleans away misc logic no longer needed.
=> Drop support for k8s 1.20

.github/workflows/watch-dependencies.yaml, jupyterhub/templates/scheduling/user-scheduler/configmap.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
We can't transition to kube-scheduler 1.25 unless we are on k8s >=1.24 because then that binary crashes, so we stick with kube-scheduler 1.23 if the k8s versions is too old.
=> Update kube-scheduler to v1.25 and its configuration api to v1 if k8s >=1.24

.github/workflows/test-chart.yaml
See https://github.com/jupyterhub/team-compass/issues/444#issuecomment-1420350287.
Note that I don't want to update all links to hub.jupyter.org/helm-chart as part of this so that such change becomes consistent and something we discuss first.
=> ci: fix for redirect to hub.jupyter.org

docs/source/jupyterhub/customizing/user-management.md
This is to fix the broken link detected by the [linkcheck](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/actions/runs/4128842204/jobs/7133778166#step:5:2372).
=> Fix broken link

images/singleuser-sample/README.md
Local docker run needs to bind externally for expose to work.
Remove outdated instructions running on old/new interface.
Reported via https://discourse.jupyter.org/t/how-to-test-k8s-singleuser-sample-alone-and-locally-without-deploying-to-eks/17694/1
=> Documentation fix for running k8s-singleuser-sample locally

.github/workflows/test-chart.yaml, docs/source/changelog.md, images/hub/Dockerfile, images/singleuser-sample/Dockerfile, jupyterhub/Chart.yaml, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
- Closes #2979 as GKE/EKS/AKS has dropped support for k8s 1.21 now a bit earlier than March as previously declared.
I squeezed in a few smaller docs updates into this PR that could have been separate PRs. The linkcheck failure is unrelated and reported in https://github.com/jupyterhub/jupyterhub/issues/4376.
=> Drop support for k8s 1.21

docs/source/administrator/authentication.md, docs/source/administrator/upgrading/index.md, docs/source/jupyterhub/customizing/user-resources.md, docs/source/kubernetes/amazon/step-zero-aws-eks.md, docs/source/kubernetes/google/step-zero-gcp.md, docs/source/kubernetes/microsoft/step-zero-azure.md, docs/source/resources/glossary.md, docs/source/resources/reference-docs.md
Replaces most `redirect ... - permanently to` reports from linkcheck with the destination, except for those where the redirect appears to be context dependent (e.g. country specific), and for anything in the changelog
=> docs: Replace most permanent-redirects from linkcheck

docs/source/administrator/authentication.md, docs/source/administrator/upgrading/upgrade-1-to-2.md, docs/source/changelog.md, docs/source/resources/glossary.md, docs/source/resources/reference-docs.md, jupyterhub/schema.yaml
https://jupyterhub.readthedocs.io/en/stable/ should be the most recent release, whereas latest will include unreleased changes on the main branch
It'd be even nicer if we could use `{{jupyterhub_version}}` since Z2JH is tied to particular versions of JupyterHub but unfortunately we can't https://github.com/executablebooks/MyST-Parser/issues/279
=> Use jupyterhub docs `stable` instead of `latest`

jupyterhub/templates/_helpers-names.tpl, jupyterhub/templates/proxy/service.yaml
I wanna create multi-hub for many users.
I'm trying to use an alias for this, and found out that it is supported with following PR.
[fix: bug if z2jh is used as a dependency with an alias](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2310)
However, I found some problems with it, and made this PR to fix it.
- jupyterhub version: 2.0.0
- app version: 3.0.0
Like this [PR](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2310), `existing-secret` should also be in the conditional statement.
After solving Problem 1, I succeeded in creating two hubs (each have different urls in `ingress.hosts`)
There is a bug that when spawning through one url, it randomly spawns in another hub
When I spawn singleuser via one url, other hub spawns randomly.
To prevent this, a selector was …
=> Fix bugs related to installing chart multiple times in the same namespace

.flake8, .pre-commit-config.yaml, jupyterhub/files/hub/jupyterhub_config.py
there shouldn't be any lint config in pre-commit config, because then the same linters run via other means (e.g. editor plugins) will have different results.
Config is unchanged, except for trading the flake8 config to ignore `c` as a global in favor of defining c explicitly on a single `# noqa` line.
=> satisfy flake8 in jupyterhub_config.py

images/hub/Dockerfile, images/hub/requirements.in, images/hub/requirements.txt
psycopg2-binary is [not recommended for production](https://www.psycopg.org/docs/install.html#change-in-binary-packages-between-psycopg-2-7-and-2-8), so compile and link to the host libpq.
I expected to need `libpq-dev` in build, too, but apparently it's already in the non-slim base image for some reason.
=> compile psycopg2 in hub image

docs/source/administrator/optimization.md, jupyterhub/schema.yaml
The example names in `prePuller.extraImages` in the examples [1](https://z2jh.jupyter.org/en/latest/resources/reference.html#prepuller-extraimages) and [2](https://z2jh.jupyter.org/en/latest/administrator/optimization.html#additional-sources) are invalid. When using them the following error occurs:
```output
Error: UPGRADE FAILED: pre-upgrade hooks failed: warning:
Hook pre-upgrade jupyterhub/templates/image-puller/daemonset-hook.yaml failed:
DaemonSet.apps "hook-image-puller" is invalid: spec.template.spec.initContainers[2].name:
Invalid value: "image-pull-myExtraImageIWantPulled":
a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-',
and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc',
regex used for validation is …
```
=> DOC: Fix invalid names in configuration examples

.github/workflows/publish.yml, .github/workflows/release-tag.yml, .github/workflows/support-bot.yml, .github/workflows/test-docker-build.yaml, .github/workflows/test-docs.yaml, .github/workflows/vuln-scan.yaml, .github/workflows/watch-dependencies.yaml
- A deprecated `set-output` call was around apparently (https://github.com/jupyterhub/team-compass/issues/579)
- We used ubuntu-20.04, ubuntu-latest, and ubuntu-22.04, now ubuntu-22.04 systematically
- An small opionated refactoring of a script snippet
=> ci: fix deprecation of set-output and use ubuntu 22.04 and py311

docs/source/jupyterhub/customizing/user-storage.md
The old URL intermittently fails the linkcheck
=> Replace IEC prefixes link

jupyterhub/schema.yaml
The `singleuser.uid` documentation refers to https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.uid which says
> If set to None, the user specified with the USER directive in the container metadata is used.
In Z2JH the UID always defaults to 1000.
Alternatively, could we unset
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/26fb33da64b4914a192e37e03156eb0f9e72d863/jupyterhub/values.yaml#L367
so it uses the image's default?
=> doc: singleuser.uid default is always 1000

.github/workflows/publish.yml, .github/workflows/test-chart.yaml, .github/workflows/test-docs.yaml, docs/Makefile, docs/make.bat, docs/source/conf.py, jupyterhub/.helmignore, jupyterhub/templates/_helpers-names.tpl, jupyterhub/values.schema.yaml, tools/compare-values-schema-content.py, tools/generate-json-schema.py, tools/validate-against-schema.py
We generate a file called `values.schema.json` from the `.yaml` equivalent file, so naming it like this seemed a bit more self-explanatory. This is a pure refactoring PR without any change in behavior.
=> refactor: rename schema.yaml to values.schema.yaml

.github/workflows/test-chart.yaml, docs/source/changelog.md, jupyterhub/Chart.yaml
Ready to be merged!
- Closes #3040 
Note that the `kubeVersion` constraint we declare in Chart.yaml doesn't stop a chart depending on the jupyterhub chart to be installed - only the chart directly installed's `kubeVersion` constraints are respected.
=> Drop support for k8s 1.22

docs/source/jupyterhub/installation.md
Relying on clients to follow a redirect may not be robust.
https://discourse.jupyter.org/t/helm-chart-certificate-x509-error-when-deploying-on-eks-using-aws-cdk/19524
=> Helm chart url has changed

.github/workflows/test-chart.yaml, CONTRIBUTING.md, README.md, docs/source/administrator/authentication.md, docs/source/changelog.md, docs/source/jupyterhub/customizing/user-management.md, docs/source/jupyterhub/installation.md, docs/source/kubernetes/amazon/step-zero-aws-eks.md, docs/source/kubernetes/microsoft/step-zero-azure.md, docs/source/repo2docker.md, jupyterhub/Chart.yaml, jupyterhub/README.md, jupyterhub/values.schema.yaml
We made an alpha.1 release, and I was thinking it should be alpha.1 because we were to also add oauthenticator 16 to that later - another breaking change.
I figure now, in order to unblock this release and let's not force a timeline on oauthenticator 16 and instead do another major version release once oauthenticator 16 lands.
I'd like to see us release 3.0.0 or so this friday or early next week.
=> Update changelog for 3.0.0-beta.1

docs/source/conf.py
Parses values.yaml to get the default value
I got annoyed at having to jump between https://z2jh.jupyter.org/en/stable/resources/reference.html for the docs and https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml for the defaults
=> Show default value in configuration reference

docs/source/administrator/authentication.md
Hello everybody,
I just started using JupyterHub and I had hard times understanding how to configure keycloak autorisation in order to use keycloak's client roles as JupyterHub internal's groups.
What I wanted to achieve is to have only keycloak users which have `user` role assigned allowed to connect and use Jupyter and also defining Jupyter's administrator through keycloak via an `admin` role.
I have to sneak into a tons of threads and post and no one describing how to do this. 
I finally had to go through the OAuthenticator documentation to find an example of code which achieve this (see [the docs](https://github.com/jupyterhub/oauthenticator/tree/main/examples/generic#example-configuration-with-authorization-enabled)).
I think anybody who wants to deploy it in production alongside …
=> Enhance keycloak configuration example

docs/source/administrator/authentication.md, docs/source/conf.py
As part of upgrading to OAuthenticator 16, is our authentication documentation up to date? I skimmed through it and concluded its largely relevant still, but to not burden ourselves with updating it perfectly - which is impossible anyhow - I've added a disclaimer like this.
=> docs: let auth docs link to authenticator specific docs

docs/source/conf.py, jupyterhub/values.schema.yaml, jupyterhub/values.yaml
Linked issue #3160 - Update values schema to allow key `enabled`
Closes #3160
=> Allow `enabled` config, for use by charts depending on this chart conditionally

.github/workflows/test-chart.yaml, .pre-commit-config-shellcheck.yaml, .pre-commit-config.yaml
Disabled by default, run with `pre-commit run --all --hook-stage manual`
https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
=> Include shellcheck pre-commit in main pre-commit

jupyterhub/templates/_helpers-netpol.tpl, jupyterhub/values.schema.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This chart ships with togglable predefined networking rules declared in NetworkPolicy resources that may or may not be enforced in a k8s cluster, and if they are enforced they are enforced by varying projects such as [Calico](https://www.tigera.io/project-calico/) or [Cilium](https://cilium.io/).
We have previously had a single rule ([`dnsPortsPrivateIPs`](https://zero-to-jupyterhub--3179.org.readthedocs.build/en/3179/resources/reference.html#hub-networkpolicy-egressallowrules-dnsportsprivateips)) to ensure pods have access to a k8s cluster's DNS server, but it seems that this rule isn't enogh in two known situations. This PR is adding two rules ([`dnsPortsCloudMetadataServer`](https://zero-to-jupyterhub--3179.org.readthedocs.build/en/3179/resources/reference.html#hub-networkpolicy-egressa …
=> Add and enable two egressAllowRules to ensure DNS access

docs/source/administrator/security.md, docs/source/changelog.md, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/templates/NOTES.txt, jupyterhub/templates/_helpers-netpol.tpl, jupyterhub/values.schema.yaml, tools/templates/lint-and-validate-values.yaml
Closes #3185 by superseding it. In practice, instead of making singeluser.cloudMetadata.blockWithIpTables more fine grained to not block port 53 etc, we instead let it remain a blunt tool that we recommend disabling if fine grained permissions via NetworkPolicy enforcement is available.
This PR tightens the schema to error on the ambigious configurations of blocking access to the cloud metadata server using IP tables while allowing it with a NetworkPolicy. This PR also documents breaking changes from #3179 - breaking because they add permissions that users in theory could want not to be added.
Marking this as breaking as we tighten the schema to error on ambigious configuration.
---
With this merged, I'd like to go for a 3.0.0 release!
=> maint: restrict allowed config with blockWithIpTables, add misc docs

.github/workflows/test-chart.yaml, dev-config-local-chart-extra-config.yaml, dev-config.yaml
Tests and upgrade from 2.0.0 instead of 1.2.0, and by doing so is able to coalesce development config to a single file.
=> maint: cleanup in development chart config files

docs/source/administrator/services.md
Add missing proxy egress for example of publicly available managed services.
Fixes #3187
=> docs: fix the jupyterhub managed service example's networking rules

docs/source/changelog.md, docs/source/jupyterhub/customizing/user-storage.md
Oauthenticator had a bug that was breaking for users with Google / Globus OAuthenticator and users with `c.JupyterHub.load_roles` - but the latter is something we have use by default in z2jh because of jupyterhub-idle-culler's config.
=> Add changelog for 3.0.1

docs/source/changelog.md
Oauthenticator 16.1.0 with a feature also being a bugfix in a way, and KubeSpawner 6.1.0 with an important bugfix causing orphaned user pods.
The changelog links out to a discourse post on how to clean these up orphaned pods up etc.
=> Add changelog for 3.1.0

.github/workflows/test-chart.yaml
- ci: fetch stable/dev releases using helm show to avoid cache issues
> Previously we fetched the latest stable and dev release from metadata we
have maintained, but doing that and then using `helm install` of that
version made us use two sources of data, where one could be relatively
outdated due to hitting a cache while the other may not.
>
>Using `helm show`, we rely on the helm chart repository website
returning a index.yaml listing versions etc both when checking whats the
latest versions, and when installing - like that we avoid a cache issue
I think.
- ci: cleanup unused sourcing of ci/common
---
Sibling PR to https://github.com/jupyterhub/binderhub/pull/1785
=> ci: fetch stable/dev releases using helm show to avoid cache issues

.circleci/config.yml, .github/workflows/publish.yml, .github/workflows/test-chart.yaml, CONTRIBUTING.md, RELEASE.md, chartpress.yaml, docs/source/administrator/security.md, docs/source/administrator/services.md, docs/source/changelog.md, docs/source/repo2docker.md, images/hub/Dockerfile, images/singleuser-sample/Dockerfile, images/singleuser-sample/README.md, jupyterhub/values.yaml
While we do have 'sponsored OSS' status on dockerhub, @choldgraf (whose credit card is apparently tied to the dockerhub jupyterhub account) just got a surprise multi hundred dollar bill for that organization! While I'm sure this is a mistake and can be corrected, it's IMO enough incentive for us to move away for real.
See https://github.com/jupyterhub/team-compass/issues/688 for team-compass issue about this.
TODO:
=> Use quay.io as source of docker images

docs/source/conf.py, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/values.schema.yaml, tools/templates/lint-and-validate-values.yaml
Currently prePuller, when it comes to obtaining list of images from `singleuser.profileList`, does not support the [profile_options](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.profile_list) way of redefining the images. 
This PR aims to add such a support. 
Current mitigation without such a support, is to define images second time in `prePuller.extraImages`, but this is not really convenient and overcomplicates maintenance of the actual profile list.
=> Pull images from `singleuser.profileList` found in `profile_options.choices`

.github/workflows/publish.yml, .pre-commit-config.yaml, ci/publish, docs/source/changelog.md
This is a followup to #3254 where we switched to rely on quay.io over docker hub.
- Links to other related PRs: https://github.com/jupyterhub/team-compass/issues/688#issuecomment-1825675990
=> Publish to Docker Hub alongside Quay.io

docs/source/kubernetes/redhat/step-zero-openshift.md
Hi, I have a working deployment of the Z2JH working with OpenShift. The [docs for deploying JupyterHub to OpenShift](https://z2jh.jupyter.org/en/stable/kubernetes/redhat/step-zero-openshift.html) link to a [repo abandoned in 2019](https://github.com/jupyter-on-openshift/jupyterhub-quickstart/issues/38#issuecomment-900629681).
I am amending the documentation to point to my working repository [here](https://github.com/gembaadvantage/z2jh-openshift) as a way to start this conversation :).
Please let me know if you would prefer that I attempt to merge these changes into the trunk of the Z2JH project, and create documentation for that; or if you would prefer for them to be separate due to the additional requirements OpenShift enforces.
=> update openshift documentation

.github/workflows/watch-dependencies.yaml
A change I forgot to make in #3312 that led to the incorrect automated PR #3316 for example.
=> ci: update kube-scheduler binary's minor version to bump

.github/workflows/test-chart.yaml, docs/source/changelog.md, jupyterhub/Chart.yaml
This is a routine requirement update along with the policy of supporting only the k8s version still supported by major cloud providers' services like GKE/EKS/AKS.
- Closes #3309
=> Drop support for k8s 1.24, require k8s 1.25+

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Sometimes Helm reports type float64 for integer numbers set in `values.yaml`. See this Helm issue for an example:
https://github.com/helm/helm/issues/4982
This fix replaces the type check with a simple check + integer cast.
=> Fix previously ignored revisionHistoryLimit config

docs/source/changelog.md
This is a release with everything in main branch, but with the breaking change PRs #3312 and #3319 reverted.
I'll cherry-pick the changelog into the 3.x branch if this is merged and then cut a release from there with 3.3.0.
---
Screenshot of docs preview:
=> Add changelog for 3.3.0

images/hub/requirements.in, images/hub/requirements.txt
- Fixes #3366, described in https://discourse.jupyter.org/t/suddenly-getting-oath-cert-error/24217, by pinning to an older functional version.
I tried to do `--no-binary=pycurl` etc, but we have multistage builds etc making things a bit complicated, and I didn't got it working.
=> hub image: downgrade to use pycurl with functional wheel

images/network-tools/Dockerfile
=> network-tools image: pin alpine 3.18 for legacy iptables

images/hub/Dockerfile, images/hub/requirements.in, images/hub/requirements.txt
and make sure we build it from source with `--no-binary pycurl`
Also make sure to use build-stage wheels by adding `--no-index` to pip install.
avoids installing higher-priority wheels from PyPI instead of what we built (i.e. pycurl)
`--no-index` was the part missing in #3365, because the `manylinux_2_28` wheel from PyPI was preferred at install time to the `linux_arch` wheel that we built. `--no-index` ensures no contact with PyPI at all at install time.
This is a low priority fix to unpin versions going forward, no need to trigger a new patch release.
=> unpin pycurl

docs/source/changelog.md
Flushes a jupyterhub 4.1.4 -> 4.1.5 bump, even though its just a patch of relevance for user images with jupyterhub-singleuser being executed (against old versions of jupyter_server and notebook), as it helps admins not worry about the missing patch version if they used chart version 3.3.6.
=> Add changelog for 3.3.7

ci/common, docs/source/administrator/services.md, docs/source/resources/community.md, jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/secret.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/values.schema.yaml, tests/test_spawn.py, tools/templates/lint-and-validate-values.yaml
This enables us to make a breaking change in z2jh 5 where user servers restarted once or more during z2jh 4 doesn't have to be restarted as part of the breaking change then. If we did it right away, network policy enforcement would fail for old servers for example.
Before z2jh 4, we should also get kubespawner to specify `app.kubernetes.io/component` alongisde `component`. This is done in https://github.com/jupyterhub/kubespawner/pull/835.
Also, its nice to be able to provide time for people to adjust to the new labels with a period of overlapping labels. For example, grafana dashboards working with prometheus metrics could keep working in this period and at any time transition to refering to new labels, and then when we get z2jh 5 released such dashboards could have already adjusted.
--- …
=> Add recommended chart labels alongside old labels (`app.kubernetes.io/...`, `helm.sh/chart`)

docs/source/conf.py
RTD is going to stop injecting config on the fly. This affects custom domains: https://about.readthedocs.com/blog/2024/07/addons-by-default/
=> RTD custom domain changes

jupyterhub/files/hub/jupyterhub_config.py, jupyterhub/values.schema.yaml, jupyterhub/values.yaml
Some [Storage Classes](https://kubernetes.io/docs/concepts/storage/storage-classes) (e.g. [vSphere](https://kubernetes.io/docs/concepts/storage/storage-classes/#vsphere)) provide volumes that contain a `lost+found` directory at its root (`/`) by default.
=> Add `singleuser.storage.dynamic.subPath` config

jupyterhub/values.yaml
This should allow running JupyterHub in a namespace with a `restricted` security profile according to the [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) (assuming an appropriate configuration for the singleuser pods in KubeSpawner).
=> Security context hardening

docs/source/administrator/debug.md, docs/source/kubernetes/microsoft/step-zero-azure.md
A detailed walkthrough of a debugging session is nice, but it needs to be kept up to date, otherwise it ends up misleading people. At least two people in Discourse have used the `ae885c0a6226` docker-stacks image tag which is 7 years old and is incompatible. I don't know if this is the source, but for future maintainability I'm removing the example.
=> debugging: remove old (now misleading) example

jupyterhub/templates/ingress.yaml, jupyterhub/values.schema.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
Introduces the ability to configure custom paths for the Ingress resource in the Helm chart, allowing users to define additional paths and corresponding backend services directly in the values.yaml file.
=> Add `ingress.extraPaths` config

docs/source/changelog.md, jupyterhub/templates/scheduling/user-scheduler/rbac.yaml, jupyterhub/values.yaml
=> user-scheduler: update kube-scheduler binary from 1.28.14 to 1.30.5

.github/workflows/watch-dependencies.yaml
=> ci: configure automatic bump of kube-scheduler to version 1.30.x

docs/source/administrator/upgrading/index.md, docs/source/administrator/upgrading/upgrade-2-to-3.md
I'll work on 3 to 4 separately before the release.
=> Add backdated upgrade guide for 2 to 3

images/hub/requirements.in, images/hub/requirements.txt, images/singleuser-sample/requirements.txt
- We had nullauthenticator package explicitly installed, but its now an authenticator class part of jupyterhub.
- We had pyjwt and mwoauth installed for oauthenticator, but its better we use the oauthenticator extras to install things when possible as that allows oauthenticator to put constraints on versions. So mwoauth is now installed that way, and pyjwt is installed by oauthenticator no matter what nowdays.
- The oauthenticator[googlegroups] extras has been installed as it was a requirement for full function of google groups things.
=> Add oauthenticator googlegroups extras and cleanup dependencies

docs/source/administrator/upgrading/index.md, docs/source/administrator/upgrading/upgrade-1-to-2.md, docs/source/administrator/upgrading/upgrade-2-to-3.md, docs/source/administrator/upgrading/upgrade-3-to-4.md, docs/source/changelog.md
<details><summary>Click to expand</summary>
- Bump kubespawner from 6.2.0 to 7.0.0b1 [#3520](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3520) ([@consideRatio](https://github.com/consideRatio))
- Bump oauthenticator from 16.3.1 to 17.0.0 [#3519](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3519) ([@consideRatio](https://github.com/consideRatio))
- Update jupyterhub/configurable-http-proxy version from 4.6.1 to 4.6.2 [#3431](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3431) ([@jupyterhub-bot](https://github.com/jupyterhub-bot), [@minrk](https://github.com/minrk))
- Update library/traefik version from v3.1.3 to v3.1.4 [#3504](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3504) ([@jupyterhub-bot](https://github.com/jupyterhub-bot), …
=> Add changelog for 4.0.0-beta.1

jupyterhub/templates/hub/service.yaml, jupyterhub/values.schema.yaml, jupyterhub/values.yaml
This addresses #3533 and allows `appProtocol` to be set on the `hub` Service defintion.
=> add appProtocol to hub service definition

images/hub/requirements.txt
@jrdnbradford check out this pr =) A lot of additional dependencies are no longer needed thanks to your work!
=> Update oauthenticator from 17.0.0 to 17.1.0

jupyterhub/templates/hub/deployment.yaml
By doing this, you'd be able to do `kubectl logs deploy/hub` and get the
hub containers logs no matter what. Before, you'd get the first listed
`hub.extraContainer` instead and have to add `--container=hub` to ensure
getting the hub containers logs.
I'm maintaining a deployment where we use hub.extraContainers, and by
doing so, have been required to specify `-c hub` anytime I want logs,
because its not the first container in the pod specs list of containers.
=> Ensure hub container is first by appending instead of prepending hub.extraContainers

.github/workflows/test-chart.yaml, docs/source/administrator/security.md, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.schema.yaml, tests/test_spawn.py
The [JupyterHub v5 upgrade doc](https://jupyterhub.readthedocs.io/en/stable/howto/upgrading-v5.html#user-subdomains) says
> All JupyterHub deployments which care about protecting users from each other are encouraged to enable per-user domains, if possible, as this provides the best isolation between user servers.
which sounds like a strong recommendation. This is not currently supported by Z2JH as CHP needs the `--host-routing` flag. Since CHP is not managed by JupyterHub this isn't automatically configured
https://github.com/jupyterhub/jupyterhub/blob/ab43f6beb8571e2b831801089d61144b15951b85/jupyterhub/proxy.py#L738-L739
https://discourse.jupyter.org/t/user-subdomains-oauth-state-missing/29328/4
The main downsides of using `hub.config.subdomain_host` as the condition instead of a …
=> Support subdomain_host (CHP needs --host-routing)

.github/workflows/watch-dependencies.yaml
results in miscategorization in github-activity changelogs
=> remove maintenance label from autobump PRs

images/hub/requirements.in
This should bring in kubespawner 7.0.0 and ldapauthenticator 2.0.1
=> Update kubespawner ldapauthenticator

docs/source/administrator/upgrading/upgrade-3-to-4.md, docs/source/changelog.md, docs/source/conf.py
adds 3-to-4 upgrade doc, which summarizes the relevant changes in dependencies and upgrade strategies in the chart config. I could find no changes in the chart itself that really needed upgrade docs, does anyone disagree, are there any new features we want to highlight in the upgrade doc in addition to possible breakages?
To prepare for final release, this collapses beta changelog entries into a single entry for 4.0, since I don't think we should keep changelog entries for prereleases.
I think theres some redundancy in the "version upgrade table" between the changelog and the upgrade doc. I think some redundancy is fine, but I don't have a great guide in my head for what level of info belongs where.
=> v4 upgrade doc, changelog for 4.0

docs/source/administrator/authentication.md
- `claim_groups_key` is deprecated, replaced by `auth_state_groups_key`
- `manage_groups` must be used with the above, otherwise JupyterHub fails to start
=> Update Keycloak example (currently broken)

jupyterhub/templates/_helpers.tpl, jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/job.yaml, jupyterhub/templates/proxy/autohttps/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/templates/scheduling/user-placeholder/statefulset.yaml, jupyterhub/templates/scheduling/user-scheduler/deployment.yaml
Some labels are missing in the pods, such as:
```
app.kubernetes.io/name: "jupyterhub"
app.kubernetes.io/instance: "release-name"
app.kubernetes.io/managed-by: Helm
```
The issue occurred because 'jupyterhub.matchLabels' was imported instead of 'jupyterhub.labels'.
Closes #3595
=> Add modern labels to pods controlled by deployments etc.

jupyterhub/templates/_helpers-names.tpl, jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/templates/image-puller/serviceaccount-continuous.yaml, jupyterhub/templates/image-puller/serviceaccount-hook.yaml, jupyterhub/values.schema.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This MR adds two separate dummy ServiceAccounts for hook-image-puller and continuous-hook-image-puller.
- The continuous image puller runs constantly to ensure images are always available.
- The hook image puller is temporary, used during tasks like upgrades, and is deleted afterward.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3545
=> Add dummy service accounts to hook-image-puller and continuous-image-puller pods

.github/workflows/publish.yml, .github/workflows/release-tag.yml, .github/workflows/support-bot.yml, .github/workflows/test-chart.yaml, .github/workflows/test-docker-build.yaml, .github/workflows/test-docs.yaml, .github/workflows/vuln-scan.yaml, .github/workflows/watch-dependencies.yaml, .readthedocs.yaml
Preparation for testing arm64 runners https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3605
=> Switch GitHub CI and readthedocs to Ubuntu 24.04

jupyterhub/templates/image-puller/_helpers-daemonset.tpl, jupyterhub/values.schema.yaml, tools/templates/lint-and-validate-values.yaml
We support `imagePullPolicy` for most images that can be pre-pulled (though not all, e.g. `kubespawner_override.image` which we may want to review in future).
=> Add pullPolicy to pre-pulled extraImages

docs/source/administrator/troubleshooting.md, jupyterhub/values.yaml
Make it easier to figure out how to get prometheus scraping of metrics endpoint working
=> docs(prometheus): Document how to set up scraping in kubernetes

docs/source/administrator/authentication.md, docs/source/administrator/cost.md, docs/source/conf.py, docs/source/index.md, docs/source/kubernetes/amazon/step-zero-aws.md, docs/source/kubernetes/redhat/step-zero-openshift.md, docs/source/repo2docker.md, jupyterhub/values.schema.yaml
- Add URLs failing in CI to ignored list https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3653
- Updates most "permanently redirected" links to their new destination
- Exceptions are redirected links in the changelog, and redirections with are region specific:
=> Linkcheck: update ignored and permanently redirected external URLs

tools/templates/lint-and-validate.py
The `pipes` Python module has been deprecated for a while and been removed in Python 3.13. This PR fixes warnings in CI logs caused by this deprecated `pipes` module. More specifically, this PR replaces `pipes.quote` with `shlex.quote` in `tools/templates/lint-and-validate.py` to resolve:
```
/home/runner/work/zero-to-jupyterhub-k8s/zero-to-jupyterhub-k8s/tools/templates/lint-and-validate.py:19: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
import pipes
```
See [CI log](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/actions/runs/14496221261/job/40664561393#step:5:12) for more details.
=> Replace deprecated `pipes.quote` with `shlex.quote`

docs/source/changelog.md
With JupyterHub 5.3.0 released, I think its worth flushing out a 4.2.0 z2jh release.
=> Add changelog for 4.2.0

.github/workflows/test-chart.yaml, ci/traefik-config.yaml, jupyterhub/templates/NOTES.txt, jupyterhub/templates/_helpers-names.tpl, jupyterhub/templates/httproute.yaml, jupyterhub/values.schema.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
@Kyrremann I hope you don't mind, but I've rebased your PR https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/3222 and updated it with v1 instead of v1beta, removed the GKE specific resource, and added some tests.
=> Add support for K8S Gateway API (`httpRoute` config)

docs/source/jupyterhub/customizing/user-environment.md
Added a note on postStart hook is asynchronous from ENTRYPOINT execution.
=> documentation update on postStart hook use

jupyterhub/templates/hub/service.yaml, jupyterhub/templates/proxy/autohttps/service.yaml, jupyterhub/templates/proxy/service.yaml, jupyterhub/values.schema.yaml, jupyterhub/values.yaml, tools/templates/lint-and-validate-values.yaml
This pull request addresses issue #3484. It updates the service template to enable users to expose their JupyterHub on an IPv6 address if their cloud allows it. 
EDIT: adds `[hub|proxy].service.[ipFamilies|ipFamilyPolicy]` config
=>  Add config for k8s Services' `ipFamilies` and `ipFamilyPolicy`

jupyterhub/templates/proxy/service.yaml
A followup to #3485, where we had one more k8s Service resource not being influenced.
=> Let `proxy.service.[ipFamilies|ipFamilyPolicy]` affect the `proxy-api` Service also

docs/source/kubernetes/ibm/step-zero-ibm.md
This PR fixes some links in the docs
=> Docs: Fix link formatting

.github/workflows/test-chart.yaml
We use the Bitnami PostgreSQL chart for testing only. They've deprecated support:
https://github.com/bitnami/containers/issues/83267
This switches to their legacy repo and fixes our failing CI tests.
=> test-chart.yaml: use docker.io/bitnamilegacy/postgresql
