jupyterhub/zero-to-jupyterhub-k8s

doc/source/setup.rst

This simplifies the instructions based on today's work on https://github.com/jupyterhub/helm-chart

Install chart from github releases directly

---

doc/source/conf.py

Update config with Project Jupyter

---

doc/source/extending.rst
doc/source/setup.rst
doc/source/tools.rst
doc/source/troubleshooting.rst

Except for command line uses of jupyterhub and URLs
Fixes #3

Fix capitalization in all JupyterHub mentions

---

doc/source/setup.rst

First pass at docs on creating a kubernetes cluster at Azure.

Add Azure documentation.

---

doc/source/glossary.rst

We've many many terms we are throwing around without clear
definitions

[WIP] Add a glossary

---

doc/source/extending-jupyterhub.rst

More consistent, and talks about the general method for applying
changes

Rewrite bits of the 'extending-jupyterhub' doc

---

doc/source/_templates/sidebarintro.html
doc/source/conf.py

Add badge to GitHub and link to issues

---

doc/source/setup-helm.rst

In preparation for Release 1.0 #27, this PR:
- edits the helm document for readability
- capitalizes Kubernetes consistently
- reflows text to be less than 80 characters per line (if possible) and 99 characters for long links.

Edit helm document for consistency and clarity

---

doc/source/create-k8s-cluster.rst

Edit doc in preparation for #27. Reflow text, clean up code block consistency.

Edit Google Cloud and Azure setup

---

doc/source/extending-jupyterhub.rst

First pass at providing full instructions for setting up Google OAuth2.

Add Google OAuth2 example

---

doc/source/extending-jupyterhub.rst

requirements.txt uses ``==`` (and I can never remember that lol). Also, updating pip is probably a good idea on whatever image that is, so I added that here as a slight hint.

add pip to requirements, use double equal

---

doc/source/create-k8s-cluster.rst

Create cluster before authenticating to cluster

Reorder Azure Steps

---

doc/source/extending-jupyterhub.rst

@yuvipanda mentioned that this section could use another pair of eyes to clean it up. There are a few spots that need input about specific syntax, LMK what you think.

improving the cpu/mem section

---

doc/source/extending-jupyterhub.rst

- suggest --exclude "" arg to s2i
- new section about lifecycleHooks postStart

add example for lifecycleHooks postStart to pre-populate persistent dir

---

doc/source/setup-jupyterhub.rst
doc/source/troubleshooting.rst

Follow up to #55. Move "Investigating issues" to Troubleshooting doc.

Move subsection to troubleshooting doc

---

doc/source/cost.rst
doc/source/troubleshooting.rst

Trying to flesh out the cost estimates a little bit more. We need to actually insert numbers and improve this, but curious to see people's thoughts right now.

adding cost information

---

doc/source/additional-resources.rst
doc/source/backups.rst
doc/source/cost.rst
doc/source/create-k8s-cluster.rst
doc/source/extending-jupyterhub.rst
doc/source/getting-started.rst
doc/source/glossary.rst
doc/source/resource-mgmt.rst
doc/source/security-considerations.rst
doc/source/setup-helm.rst
doc/source/setup-jupyterhub.rst
doc/source/tools.rst
doc/source/troubleshooting.rst
doc/source/turn-off.rst
doc/source/upgrading.rst

- Edit rst:
- turn-off doc
- costs doc
- extending-jupyterhub doc
- Add doc labels for reference to each rst doc

Clean up rst in docs

---

doc/source/getting-started.rst

The primary purpose of this PR is to remove the infinite reference loop that you ran into in following the instructions. 
Basically "getting started" took you to "creating your JupyterHub" telling you to go to the first section of it which was the "getting started" block.
I think what was actually meant was the next block if someone wants a straightforward introduction to a working system (the zero to jupyterhub of the title of the thing). They should just jump right to creating a kubernetes cluster on google cloud.
Everything else is just my attempt at a quick summary without reading the entirety of those documents based on the description of the target. It's not my most careful titling work, but I figure that you'll want to have input on them no matter what they are (a reasonable …

Restructure introduction and demark divisions of interest

---

doc/source/create-k8s-cluster.rst

Also clarify what 'zone' is
Partial fix for #87

Setup a cheaper instance size as default

---

doc/source/cost.rst
doc/source/getting-started.rst
doc/source/tools.rst

Don't say 'hardware' when we mean 'computational resources'

---

doc/source/extending-jupyterhub.rst

Using the content from @yuvipanda's PR #96, edit wording and prettify the formatting.

Edit section on resizing a cluster

---

doc/source/extending-jupyterhub.rst

Use jupyter-repo2docker rather than s2i directly

---

doc/source/getting-started.rst

This PR makes the Table of Contents flow a bit better into "creating a cluster" section.

Demote questions section one level

---

doc/source/extending-jupyterhub.rst
doc/source/glossary.rst
doc/source/index.rst
doc/source/user-experience.rst

This PR is a follow on to #112.

Edit user experience doc and add to index.

---

doc/source/create-k8s-cluster.rst

add APIs to enable for Google

---

doc/source/user-experience.rst

Just a code snippet including the `cpu` limitation option.

Adding a bit of CPU resource management info

---

doc/source/extending-jupyterhub.rst

add config for whitelist of github oauth

add whitelist of usernames to github

---

doc/source/create-k8s-cluster.rst
doc/source/setup-jupyterhub.rst
doc/source/turn-off.rst

These are instructions that I followed in order to get kubernetes + jupyterhub up-and-running with AWS. The guide should "just work" once kubernetes is installed with the instructions in this PR. I probably still need to add more links etc, and feedback is welcome!
@yuvipanda @willingc in particular :-)
These instructions will only work if you add in the command described here: https://kubernetes.io/docs/admin/authorization/rbac/#permissive-rbac-permissions before running `helm install`. We're not putting this into the guide yet because hopefully @yuvipanda will come up with a more secure way of doing this. We will check back in next Wednesday! So no merge before then!

[MRG] aws instructions

---

doc/source/cost.rst
draw_function.ipynb
environment.yml
requirements.txt
z2jh/__init__.py
z2jh/cost.py

This is a first pass at adding a cost estimation demo. Eventually we'd probably want this to be a proper "widget", but for now it's an IFrame serving a binder instance (nice self-promotion here :-D ).
See it live here: http://predictablynoisy.com/zero-to-jupyterhub-k8s/cost.html#interactive-estimator
We should discuss how to improve / parameterize the cost estimation widget. Maybe @yuvipanda and I can get a good first iteration done today?

cost estimation

---

doc/source/cost.rst
z2jh/cost.py

removes the autoscaling box since it's not implemented yet...also makes the Binder link point to the jupyterhub repo instead of mine

removing autoscale box

---

doc/source/user-experience.rst

should close https://github.com/jupyterhub/helm-chart/issues/69 when we figure it out. I don't know that we want to merge this yet so we can double-check that the instructions are correct

improve CPU/Mem docs

---

doc/source/tools.rst

Noticed a missing word in the docs.

Adding a missing "for"

---

README.md

This is an initial pass at updating the README. I'm going to self merge. My expectation is that there will be future PRs on the README, and this PR is simply to notify users of the current content.

Edit readme to add helm charts

---

README.md

Add note about dual license to README

---

doc/source/create-k8s-cluster.rst

The heptio based one isn't 'production ready' and probably won't be
for a while.

Add note about kops

---

.gitignore
CHANGELOG.md
jupyterhub/templates/NOTES.txt

Remaining references are still valid

Rename a bunch of stuff that was pointing to helm-chart still

---

doc/source/setup-helm.rst

Even if RBAC isn't enabled, this is the right thing to do.

Always install helm with its own SA

---

.travis.yml
build.py

- update helm-chart publish URL (still a few lingering references to jupyterhub/helm-chart)
- sudo isn't required on Travis
- only push from travis if not building a PR. We can still exercise the build step
This should get travis passing on PRs

travis fixes

---

build.py

a few lingering jupyterhub/helm-chart references

update helm-chart index url

---

.travis.yml
README.md

Relaxes the 80 character line length on 2 lines to avoid line continuation

Add travis badge and allow 120 line length

---

images/hub/Dockerfile
images/hub/jupyterhub_config.py

fixes unicode logging
(leftover debug statement cleaned up along the way)

Set LANG in hub image

---

build.py

Bump JupyterHub version to 0.8

---

doc/source/debug.rst
doc/source/index.rst

This is a first pass at giving users tips on how they can debug their kubernetes cluster. It takes the reader through one iteration of debugging and tries to highlight a few particularly useful commands.
Here's how it looks.
http://predictablynoisy.com/zero-to-jupyterhub-k8s/debug.html

Debugging guide

---

doc/source/turn-off.rst

Add more complete 'turn off' documentation

---

images/hub/Dockerfile
jupyterhub/templates/hub/deployment.yaml

Probably needs a patch release of JupyterHub including
https://github.com/jupyterhub/jupyterhub/pull/1507

Automatically upgrade the db if we're on sqlite!

---

images/hub/jupyterhub_config.py
jupyterhub/templates/hub/configmap.yaml
jupyterhub/values.yaml

closes #232 
@yuvipanda ... I think this fixes the absence of init-container handling.  Please have a look.

add handling for init-containers in singleuser deployment

---

build.py
images/hub/Dockerfile
jupyterhub/values.yaml

bump jupyterhub to 0.8.1

---

CONTRIBUTING.md

Add info on local development to CONTRIBUTING.md

---

jupyterhub/values.yaml

I think the wrong tag was mistakenly merged in from a local
change
closes #259

Switch hub tag to a working version

---

images/hub/jupyterhub_config.py
jupyterhub/templates/hub/configmap.yaml
jupyterhub/values.yaml

Might be increased for really large images that are working
with prePuller off

Allow configuring the start timeout of singleuser pod

---

jupyterhub/templates/hub/deployment.yaml
jupyterhub/templates/hub/rbac.yaml
jupyterhub/templates/pre-puller.yaml
jupyterhub/templates/proxy/deployment.yaml
jupyterhub/templates/proxy/rbac.yaml
jupyterhub/values.yaml

This lets us fully use z2jh on a cluster with RBAC enforced

Setup RBAC for pre-puller

---

images/hub/jupyterhub_config.py
jupyterhub/templates/hub/configmap.yaml
jupyterhub/templates/hub/deployment.yaml
jupyterhub/templates/proxy/deployment.yaml
jupyterhub/values.yaml

Allow setting nodeSelectors for hub, proxy and singleuser servers

---

images/hub/Dockerfile

fixes typo introduced in recent kubespawner update https://github.com/jupyterhub/kubespawner/pull/100

bump kubespawner to get typo fix

---

.github/ISSUE_TEMPLATE.md

Adds a template for github issues. Closes #301 
WDYT @yuvipanda ?

issue template

---

jupyterhub/templates/hub/configmap.yaml

Fix admin user list + whitelist user list specification

---

doc/source/debug.rst
jupyterhub/templates/hub/deployment.yaml

Matches renaming of proxy-deployment to proxy. Also adds standard
labels

Rename hub-deployment to hub

---

doc/source/create-k8s-cluster.rst

1.7 doesn't support the RBAC object versions we are using.

Get a version of kubernetes new enough for RBAC by default

---

CHANGELOG.md

And link to docs on how to do so

Add note about error when ingress config needs to be migrated

---

doc/source/debug.rst
doc/source/extending-jupyterhub.rst
doc/source/setup-jupyterhub.rst
jupyterhub/values.yaml

Bump up version to v0.5!

---

.travis.yml
ci/deploy.sh

avoids restricting testing to deployable branches

move deploy to deploy stage

---

CONTRIBUTING.md

An update to the CONTRIBUTING document to match current build process.

Fix #342: update CONTRIBUTING to match build.py

---

ci/install.sh
ci/test.sh

Use the kubectl rollout command to wait for pods in a deployment
to be ready

Minor CI improvements

---

CHANGELOG.md

From https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/346#issuecomment-350989324

Add final entry to contributors list for v0.5

---

doc/source/security.md

Cleaned it up to make it very clear that most people should use the
let's encrypt option

Re-add info about HTTPS with some clarifications

---

ci/test.sh
jupyterhub/templates/hub/deployment.yaml
jupyterhub/templates/proxy/deployment.yaml

- Print out more debugging info when we are waiting for the hub
to be up, to make it easier for us to debug failing tests
- Make the curling code a little better

Make tests a little more stable

---

doc/source/create-k8s-cluster.rst
doc/source/setup-jupyterhub.rst

This consolidates notes in z2jh so that if there are two notes side by side, they become a single node with bullet points. Similar to https://github.com/jupyterhub/binderhub/pull/401

consolidating notes

---

jupyterhub/templates/hub/configmap.yaml

Preserve JSON structures of service options

---

doc/source/security.md
images/hub/jupyterhub_config.py
jupyterhub/templates/hub/configmap.yaml
jupyterhub/values.yaml

Add a note in security doc about how to use this, with plenty of warnings.
Fixes #404

Allow specifying serviceAccountName in config.yaml

---

images/singleuser-sample/Dockerfile

Should bring in newer versions of the base package

Bump base image of singleuser-sample to newer version

---

doc/source/create-k8s-cluster.rst
doc/source/security.md

- Most people don't need to create ad accounts manually,
so remove it.
- Do not use environment variables. People might not know what
they are, and for the people who do, they can use it even if
we do not mention it
- Add several missed steps that someone on a new account might
need, such as enabling the APIs and creating a special SSH key  
Things to do:
work around for both helm init and jupyterhub itself

Cleanup Azure AKS install instructions

---

doc/source/create-k8s-cluster.rst
doc/source/setup-helm.rst

Fixup AKS instructions + include helm instructions for AKS

---

doc/source/advanced.md

Add pre-puller content to docs

---

doc/source/user-environment.rst
images/hub/jupyterhub_config.py
jupyterhub/templates/hub/configmap.yaml
jupyterhub/values.yaml

Also adds docs on how to make JupyterLab be default.
Fixes #375

Add support for setting default_url in config.yaml

---

doc/source/user-management.md

Documentation on user culling behavior.

improving user culling docs

---

doc/source/user-environment.rst

This improves the instructions for pre-populating the filesystem with data/repos/etc. @yuvipanda LMK if I've gotten something wrong here!
#66 #335 are relevant here!

Improving pre-populating instructions

---

doc/source/index.rst
doc/source/users-list.md

Add a list of 'users of this chart'

---

doc/source/user-environment.rst

Took me a while to find the configuration for the default image of the chart so added a link to the guide.

Add a link to Dockerfile for default image

---

images/hub/requirements.txt

This will be released as KubeSpawner 0.8.

Bump kubespawner version

---

images/hub/requirements.txt

Upgrade psycopg2 to 2.7.3.2.

---

doc/source/advanced.md

Clarify key for ubuntu in docs

---

doc/source/create-k8s-cluster.rst

Edit azure docs for cluster set up

---

CHANGELOG.md
CONTRIBUTING.md
doc/source/upgrading.md
tools/contributors.py

This PR includes the changelog for v0.6. It also updates the documentation around making releases in general.

v0.6 changelog

---

CHANGELOG.md

This might be more suitable for general troubleshooting section of z2jh as opposed to a release-specific issue. But since the upstream issue coincides with this particular release it is probably fine to put it here.

Add note about ingress workaround.

---

doc/source/authentication.rst
images/hub/jupyterhub_config.py
jupyterhub/templates/hub/configmap.yaml

Add the ability to whitelist github orgs

---

doc/source/create-k8s-cluster.rst

1.8 is now the default, so we do not need this anymore!

Don't make users specify k8s version with GKE

---

doc/source/user-environment.rst

Change note now that JupyterLab is in beta.

Update user-environment.rst now that JuptyerLab is in beta

---

README.md

I worked on this at Hack Illinois 2018 with @willingc.

Fix of typo in spelling of initial

---

CONTRIBUTING.md

update local install instructions for minikube

---

doc/source/authentication.rst

Minor capitalization correction.

---

CONTRIBUTING.md

cc @choldgraf @manics 
Good catch @manics 👍

Merge in changes missed in #554

---

jupyterhub/Chart.yaml
jupyterhub/values.yaml

Reverts jupyterhub/zero-to-jupyterhub-k8s#557

Revert "Add informational fields and minimal comments to jupyterhub chart"

---

doc/source/user-environment.rst

Reference: https://github.com/jupyterhub/jupyterlab-hub/issues/42

Update documentation for using Jupyterlab with hub

---

doc/source/user-environment.rst

Tells people to use the `conda-forge` channel

jlab comment for using `conda-forge`

---

images/hub/requirements.txt

gets https://github.com/jupyterhub/kubespawner/pull/147

kubespawner deletes stopped pods

---

images/hub/requirements.txt
jupyterhub/templates/hub/rbac.yaml

For https://github.com/jupyterhub/kubespawner/pull/150 to work properly.

Allow hub service account to read events.

---

doc/source/setup-helm.rst

Just a minor typo that caught my eyes while going through the documentation

Minor typo fix: cluser -> cluster

---

doc/environment.yml
doc/source/advanced.md
doc/source/authentication.rst
doc/source/conf.py
doc/source/index.rst
doc/source/tools.rst
doc/source/upgrading.md

- correcting links that fail `make linkcheck` or have new redirects
- make a couple of toctree corrections

bump sphinx to 1.7 and correct links and toctree

---

images/hub/cull_idle_servers.py

bugs fixed in the latest culler version which as been updated to support 0.9
gets fixes from https://github.com/jupyterhub/jupyterhub/pull/1807

import updates to culler

---

doc/source/amazon/step-zero-aws.rst
doc/source/google/step-zero-gcp.rst
doc/source/index.rst
doc/source/microsoft/step-zero-azure.rst
doc/source/security.md
doc/source/setup-helm.rst
doc/source/setup-jupyterhub.rst
doc/source/user-environment.rst

This is several documentation improvements for a bunch of issues that we've been collecting over time. Spot-checks a number of questions / concerns / suggestions that people have raised. Here's a list of all issues this will address:
closes #93
closes #414
closes #446
closes #64
closes #49
closes #131
closes #150
closes #58

miscellaneous doc improvements

---

doc/source/authentication.rst

Documentation for https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/649
As with the original PR I haven't tested the AD example.

Add example ldapauthenticator configuration

---

doc/source/cost.rst
doc/source/index.rst
doc/source/security.md
doc/source/tips.rst
doc/source/user-environment.rst

This updates several more small-ish documentation issues that were outstanding, I believe this is the list:
closes #623  tips for kubectl
closes #600  letsencrypt clarification
closes #648 maybe, not sure if more clarification is needed   @consideRatio what do you think?
closes #485 cost calculator clarification and links to provider calculators

miscellaneous doc updates take 2

---

chartpress.yaml

Possibly the last beta before rc and release
https://github.com/jupyterhub/jupyterhub/compare/0.9.0b2...0.9.0b3

jupyterhub 0.9b3

---

images/hub/requirements.txt

gets progress messages, timeouts, label fixes
https://github.com/jupyterhub/kubespawner/compare/6d5993c...cff7f01

bump kubespawner 6d5993c...cff7f01

---

dev-requirements.txt
images/hub/Dockerfile

fixes dependency on chartpress.yaml for images
remove empty line hack in hub Dockerfile

require chartpress 0.2

---

doc/source/amazon/step-zero-aws.rst

My RST editing is not quite right. I appreciate comments on how to fix the formatting. I don't have a good previewer outside of git.

Added encryption instructions for AWS deployment

---

chartpress.yaml

Small fixes since 0.9.
https://github.com/jupyterhub/jupyterhub/compare/0.9.0...0.9.1

jupyterhub 0.9.1

---

images/hub/requirements.txt

step 1 in fixing culling errors on mybinder.org
cc @minrk

kubespawner bump for cull fix

---

images/hub/requirements.txt

This should solve quite some bugs on LDAP authentication.

upgrade ldapauthenticator

---

doc/source/user-environment.rst

Fixes https://github.com/jupyter/repo2docker/issues/360#issuecomment-407317014

Fix parameter ordering in jupyter-repo2docker guide

---

images/hub/jupyterhub_config.py
jupyterhub/schema.yaml
jupyterhub/templates/hub/configmap.yaml
jupyterhub/values.yaml
tools/lint-chart-values.yaml

Add extra resource support for k8s-hub.
closes #795

Support extra resources for single user

---

CONTRIBUTING.md

Helm installation was missing, now step 2, and the virtual environment was not activated (now step 6.2).

Add missing local development setup steps to CONTRIBUTING.md

---

doc/source/security.md
jupyterhub/templates/proxy/netpol.yaml
jupyterhub/templates/singleuser/netpol.yaml

Fixed with @consideRatio's help
Closes #823 
Also fixes a couple of errors in related comments and docs.

Singleuser Network Policy should allow egress to hub

---

doc/source/conf.py

Going to self-merge this since the docs will be broken until it's updated!

Updating sphinx_copybutton import

---

images/hub/requirements.txt

in preparation for beta of this chart

bump kubespawner to 0.9.0b1

---

doc/source/extending-jupyterhub.rst
doc/source/google/step-zero-gcp.rst
doc/source/index.rst
doc/source/setup-helm.rst
doc/source/setup-jupyterhub.rst
doc/source/user-environment.rst

At least what I could recollect. Good night for now!

Docs changes discussed with @willingc and @minrk

---

doc/source/google/step-zero-gcp.rst

- Docs needed a indentation fix for a note
- Updated ZONE

ZONE + NOTE docs fix

---

images/hub/requirements.txt

restarts reflectors unconditionally
bumps kubespawner https://github.com/jupyterhub/kubespawner/compare/v0.9.0b1...v0.9.0b2

kubespawner 0.9.0b2

---

tools/contributors.py

for https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/878

get all contributors of all issues and closed PRs

---

README.md

also remove an extra query parameter.

http->https where possible

---

.gitignore
tools/contributors.py

Thanks @minrk for the caching solution.
I also added some notes and reduced numbers of requests made by using the `since` keyword for the API where it was made available. I learned that PyGitHub did not perfectly correspond with the actual GitHub API.

contributors.py performance by caching

---

CHANGELOG.md

Related issue: https://github.com/jupyterhub/jupyterhub/issues/2125

Restart users instructions

---

jupyterhub/schema.yaml

Better wording than in #908, thanks to @consideRatio.

Add documentation for imagePullSecret.enabled (fixed)

---

chartpress.yaml
jupyterhub/Chart.yaml

mostly bugfixes related to progress and the tokens API

install jupyerhub 0.9.3

---

doc/requirements.txt
readthedocs.yml

See https://github.com/jupyterhub/jupyterhub/pull/2156

Update doc build to pip

---

chartpress.yaml
jupyterhub/Chart.yaml

fixes 0.8->0.9 upgrade
we may want to do an 0.7.1 chart release with this, since it greatly improves the upgrade experience.

install jupyterhub 0.9.4

---

doc/source/authentication.rst
doc/source/setup-helm.rst
doc/source/setup-jupyterhub.rst

This Pull Request includes a number of re-wordings in the following files/sections:
-  Setting up Helm
- Setting up JupyterHub
- Authentication

Small rewording/grammatical issues

---

jupyterhub/templates/hub/configmap.yaml

Thanks @hans-permana for your help with this issue! Thank you @minrk for working on the configmap passthrough in #941.

Pod priority typo bugfix

---

jupyterhub/templates/proxy/autohttps/ingress-internal.yaml
jupyterhub/templates/proxy/deployment.yaml
jupyterhub/templates/proxy/netpol.yaml
jupyterhub/templates/proxy/secret.yaml
jupyterhub/templates/proxy/service.yaml

Fixes #874 
This has not been verified by me though. Thanks @cilquirm for figuring out how to solve this! :heart:

HTTPS - only require hosts for setup with letsencrypt

---

jupyterhub/values.yaml

Update default kube-lego version

---

doc/source/authentication.rst

Add example for customizing auth.custom.config.login_service

Add example for customizing login_service

---

doc/source/users-list.md

This updates the users list with @gouarin 's latest blog post

Adding users-list link

---

images/hub/jupyterhub_config.py

it was mapped to the wrong config, and thus had no effect

set consecutive failure limit on Spawner

---

doc/source/advanced.md

Caution against configuring sqlite-pvc storage classes

---

jupyterhub/values.yaml

Fixes #1044
This is a regression since #941.

Allow singleuser servers to communicate with hub with NetworkPolicy is enabled

---

images/hub/jupyterhub_config.py

with warning and everything
closes #1009

restore deprecated extraConfig string

---

jupyterhub/schema.yaml

Add profileList to schema

---

doc/Makefile

I did not update the make.bat =/
Related: #724

Add linkcheck to Makefile

---

jupyterhub/schema.yaml
jupyterhub/values.yaml

Reference docs for prePuller

---

doc/source/user-environment.rst

This adds a short section on configuring the profile list for users. It currently
uses the passthrough configuration, though I think I ran into a bug (#1097).
closes #1085 closes #1083

profile list instructions

---

doc/source/authentication.rst

Addresses https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1118#issuecomment-457321425

Describe white-listing individual GH users.

---

CONTRIBUTING.md

E.g. I used this to fix https://github.com/consideRatio/zero-to-jupyterhub-k8s/pull/6

Add note about using vagrant to simulate Travis

---

doc/source/authentication.rst

The instructions in this section misled me in https://github.com/jupyterhub/binderhub/pull/707 so this tries to clarify a bit

adding clarification for white list

---

doc/ntbk/z2jh/cost.py

They changed their html a bit, adding multiple headers in some tables
closes #1145

fix parsing of google pricing table

---

doc/source/amazon/step-zero-aws-eks.rst

[amazon] Remove arn, configmap, add necessary role

---

doc/source/amazon/step-zero-aws.rst

I didn't update https://z2jh.jupyter.org/en/latest/amazon/step-zero-aws-eks.html. It seems we keep the most information here in a usual AWS setup.

Add shared storage section, update headings

---

images/hub/requirements.txt

bump oauthenticator to 0.8.1

---

doc/source/additional-resources.rst

add STSI ansible AWS post

---

jupyterhub/schema.yaml

Same as https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1163 but for the user scheduler.

Add pdb section to schema.yaml for the user scheduler

---

chartpress.yaml
jupyterhub/Chart.yaml
tests/test_spawn.py

test with jupyterhub 1.0b1

---

doc/source/amazon/step-zero-aws-eks.rst

EKS seems to be available now in many established regions.

Updated AWS EKS region-availability statement.

---

doc/source/create-k8s-cluster.rst
doc/source/digital-ocean/step-zero-digital-ocean.rst

Digital Ocean now has a (beta) kubernetes offering.
I am adding some guidelines for the step-zero section of the documentation.

Add Digital Ocean Cloud Instructions for Kubernetes

---

images/hub/requirements.txt

fixes open-redirect when using oauth

oauthenticator 0.8.2

---

images/hub/jupyterhub_config.py

Addresses #1023
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

Set the image pull policy from Helm values

---

doc/source/user-environment.rst

This doesn't really seem like a sub-item of add-files-to-home

Change heading of multiple-profiles section

---

doc/source/user-resources.rst

Hi! :wave: 
This PR is adding instructions on how to scale a Kubernetes cluster on Microsoft Azure to the "User Resources" page of the documentation.

Update to Docs: Add Azure scale command to Expanding/Contracting Cluster section

---

doc/ntbk/z2jh/cost.py

Promo pricing broke the scraper for the Interactive Cost Estimator. 
`ValueError: could not convert string to float: '0.240 ($0.340 after promo)'`
I added a small function to extract the promotional or non-promotional pricing.

Fixed minor bug in google pricing calculator

---

doc/source/advanced.md
doc/source/optimization.md
tools/templates/lint-and-validate-values.yaml

I noticed some warnings in the linting of #1274, this should fix them.

Fix prePuller.extraImages linting etc

---

jupyterhub/schema.yaml
jupyterhub/templates/hub/deployment.yaml
jupyterhub/values.yaml
tools/templates/lint-and-validate-values.yaml

closes #1270. hopefully i got the position correct in`jupyterhub/templates/hub/deployment.yaml`

add initContainers to hub config

---

doc/source/repo2docker.rst

This adds advice to avoid a rare but possible problem that happened to bite me
today. Reviewers may judge that this is too obvious (of course you should put
quotes around the tag) or too rare an event to be worth documenting, but I
thought I'd float it for consideration.

Suggest quotes around tag.

---

doc/source/extending-jupyterhub.rst
doc/source/setup-jupyterhub.rst

`0.8.2` is the latest chart version so we might as well have it in the docs.

Update chart version to 0.8.2 in the docs

---

jupyterhub/schema.yaml

Fix link formatting for ingress.enabled

---

jupyterhub/templates/ingress.yaml
jupyterhub/templates/proxy/autohttps/ingress-internal.yaml

I ended up needing to ensure this was not causing an error, it didn't, but now that I know I figure I can document what I learned so we properly remember to not cause an issue later.

Note about future hard deprecation

---

README.md

Added Laurent Goderre as contributor

---

images/hub/Dockerfile

Useful to look at files when you are chasing stacktraces

Add vi / less to hub image

---

images/singleuser-sample/Dockerfile

Bump singleuser-sample

---

images/hub/requirements.txt

Bump kubespawner for spawner progress bugfix

---

doc/source/create-k8s-cluster.rst

DOC: fix kubernetes setup link

---

doc/source/customizing/user-management.md

Fixing URL for user-management documentation #1511

---

doc/source/setup-jupyterhub/setup-helm.rst

Missing page link for our RBAC documentation #1508

---

jupyterhub/templates/hub/deployment.yaml
jupyterhub/templates/scheduling/user-scheduler/rbac.yaml

Fix z2jh 0.9.0 user scheduler update pv error

Fix jupyter hub helm chart user scheduler template rbac error

---

jupyterhub/files/hub/jupyterhub_config.py

Fixes a detail for #1558 that was just merged.

Fix removing of named servers when culled

---

jupyterhub/files/hub/jupyterhub_config.py

WIP PR for issue #1569. Will continue till it LGTM.

Added gitlab URL

---

images/hub/Dockerfile
images/hub/requirements.txt

Using this with z2jh configuration in config.yaml will require it to be
treated as a custom authenticator at the moment as we have not written
any specific way to configure it.

Add nativeauthenticator to hub image

---

CHANGELOG.md

Based on the output of `github-activity jupyterhub/zero-to-jupyterhub-k8s --since 0.9.0-beta.3`

Changelog for 0.9.0-beta.4

---

doc/doc-requirements.txt

Same as https://github.com/jupyterhub/binderhub/pull/1070

[MRG] Pin sphinx theme

---

doc/source/microsoft/step-zero-azure-autoscale.rst

l.208 of step-zero-azure-autoscale.rst --> Add of 'sp'

Small typo fix in doc

---

doc/doc-requirements.txt
doc/source/amazon/step-zero-aws.rst
doc/source/conf.py
doc/source/customizing/user-management.md

switching to pydata theme and cleaning up a few docs errors and warnings

pydata theme

---

doc/source/microsoft/step-zero-azure.rst

https://docs.microsoft.com/en-us/cli/azure/ad?view=azure-cli-latest
should be `az ad sp` create-for-rbac

Update create service principle command.

---

CONTRIBUTING.md

This is meant to address https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1664#pullrequestreview-420783748, but it also makes small changes to the contributing documentation.

DX: final touches on CONTRIBUTING.md

---

images/hub/Dockerfile

Upgrade libc to patch vulnerability in hub img

---

doc/source/administrator/authentication.rst

I've spent some time figuring out how to integrate with yet another OAuth 2.0 / OpenID Connect provider, perhaps one more example would be helpful for others.

[Documentation] Authenticating with Auth0

---

images/hub/requirements.txt

The following command were run to upgrade dependencies in the hub image.
```
images/hub/dependencies freeze --upgrade
```

Bump KubeSpawner to 0.13.0

---

images/hub/Dockerfile

18.04 is a while ago :)
This also brings a newer version of python, I believe

hub: Switch base image to latest LTS

---

doc/source/community/additional-resources.rst

I also put a commit in to fix formatting in the same file. Tested locally and it looked all right, I'd love for there to be more whitespace between some the first sublist and the list I just put in, but I'm not sure how to enforce that in rST.
Closes #1745 .

Add terraform resources to the community resources section

---

jupyterhub/values.yaml

Update to newer version of 'pause' container

---

doc/source/amazon/step-zero-aws.rst
doc/source/conf.py

Fixes #698 
It contains a brief note about EC2 instance metadata and aligns code blocks on the same page with commands. It also has some minor additions to conf.py.

AWS documentation fixes

---

doc/source/administrator/security.md
jupyterhub/files/hub/jupyterhub_config.py
jupyterhub/templates/NOTES.txt
jupyterhub/templates/image-puller/_daemonset-helper.yaml
jupyterhub/values.yaml
tools/templates/lint-and-validate-values.yaml

Closes #1803 and closes #1408.

Soft deprecate singleuser.cloudMetadata.enabled in favor of blockWithIptables

---

jupyterhub/templates/image-puller/_daemonset-helper.yaml
tools/templates/lint-and-validate-values.yaml

In https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1764 I introduced a which is now tested for and fixed.

prePuller: fix recently introduced regression

---

.travis.yml
ci/common
dev-config.yaml
jupyterhub/values.yaml
tests/conftest.py

I consider this to be fix #1836 by considering image locality when scheduling users.﻿

user-scheduler: let image locality etc matter again

---

chartpress.yaml
images/hub/requirements.txt
jupyterhub/Chart.yaml

use jupyterhub 1.2.0

---

chartpress.yaml
images/hub/requirements.in
images/hub/requirements.txt
jupyterhub/Chart.yaml

jupyterhub 1.2.1

---

jupyterhub/templates/image-puller/_daemonset-helper.yaml

This PR closes #1891 which was very beutifully written by @jatinder91, thank you :heart: :tada:!
I intend to cut a 0.10.2 release with this merged.

Add securityContext to all image-puller pods' containers

---

CHANGELOG.md

Thank you @jatinder91 for quickly catching this and reporting it in such a beuatiful and clear way! :heart: :tada:

Changelog for 0.10.2

---

jupyterhub/templates/scheduling/user-scheduler/deployment.yaml

Avoid harmless error in user-scheduler

---

.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.md
ci/common
dev-requirements.txt
doc/source/conf.py
images/hub/dependencies
images/secret-sync/acme-secret-sync.py
jupyterhub/files/hub/jupyterhub_config.py
jupyterhub/files/hub/z2jh.py
jupyterhub/validate.py
tests/conftest.py
tests/test_spawn.py
tools/templates/lint-and-validate.py

Part one of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1899
This adds two auto-formatters:
- black for python files
- beautysh for shell scripts

pre-commit autoformat: black and beautysh

---

chartpress.yaml
images/hub/requirements.in
images/hub/requirements.txt
jupyterhub/Chart.yaml

See [the JupyterHub changelog here](https://jupyterhub.readthedocs.io/en/stable/changelog.html?highlight=changelog).

image: bump JupyterHub to 1.2.2 from 1.2.1 for bugfixes

---

.github/dependabot.yaml

ci: remove yaml anchors from dependabot config

---

.github/workflows/test.yml

ci: let pytest keep running even if one test has failed

---

ci/common

Improves reporting on failures in our CI system through the full_namespace_report bash script function.

ci: full_namespace_report improvements for restartCount > 0

---

jupyterhub/templates/_helpers.tpl

This helper was never adopted, and with #1923 coming in, it will be pointless.

Remove unused nameField helper in _helpers.tpl

---

jupyterhub/templates/image-puller/_daemonset-helper.yaml

Also pull singleuser.initContainers with pre-puller

---

.github/workflows/vuln-scan.yaml
images/hub/Dockerfile
images/image-awaiter/Dockerfile
images/network-tools/Dockerfile
images/secret-sync/Dockerfile
images/singleuser-sample/Dockerfile

vuln-scan: fix all fixable vulns, and bugfix automation, and bump singleuser-sample

---

jupyterhub/templates/image-puller/_helpers-daemonset.tpl

Fix mixup of hook/continuous-image-puller following recent PR

---

doc/source/jupyterhub/customizing/user-resources.md

Fixes: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2096

Correct the AKS GPU Link in documentation

---

images/secret-sync/Dockerfile

Must have accidentally crept in whilst debugging a build

Remove extraneous command from secret-sync image

---

jupyterhub/schema.yaml

schema: added details to hub|singleuser.extraFiles

---

.github/workflows/test-docker-build.yaml
images/singleuser-sample/Dockerfile

Thank you @jakob-keller who in https://github.com/jupyter/docker-stacks/pull/1304 already have updated the jupyter/docker-stacks images to use the latest release of JupyterHub! :heart: :tada:

singleuser-sample: update base image

---

doc/source/administrator/debug.md

I couldn't find this anywhere else in the docs

Add debug.enabled to admin debugging doc

---

.github/workflows/test-chart.yaml
jupyterhub/templates/hub/pdb.yaml
jupyterhub/templates/proxy/autohttps/pdb.yaml
jupyterhub/templates/proxy/pdb.yaml
jupyterhub/templates/scheduling/user-placeholder/pdb.yaml
jupyterhub/templates/scheduling/user-scheduler/pdb.yaml

Test against k8s 1.21 and avoid deprecation warning for old k8s api policy/v1beta1

---

jupyterhub/templates/scheduling/user-scheduler/rbac.yaml

Corrected scheduler rbac custom naming

---

.circleci/config.yml
dev-config-arm.yaml
tests/conftest.py

Experimenting with a minimal CircleCI ARM64 test.
This is currently running in my own [CircleCI account](https://app.circleci.com/pipelines/github/manics/zero-to-jupyterhub-k8s?branch=arm64-circleci), it'll obviously need to be added in the JupyterHub CircleCI account if we go ahead with this.
Closes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2146

MRG: Arm64 circleci test

---

tools/templates/lint-and-validate-values.yaml

Just wanted to add a test case I wasn't sure we covered.

ci: improve lint-and-validate-values.yaml coverage

---

doc/source/administrator/upgrading.md

If I understand correctly, `--version` for this specific example should be set to `v0.6` according to the instruction.

docs: fix weird helm upgrade example

---

.pre-commit-config.yaml
doc/source/conf.py
jupyterhub/files/hub/jupyterhub_config.py
tests/conftest.py

Test failures unrelated (https://github.com/k3s-io/k3s/issues/4054)

pre-commit: add and run pyupgrade

---

.circleci/config.yml

- ci: remove no longer needed workaround
- ci: bump circleci to latest k3s ver

ci: refresh circleci config

---

.github/workflows/vuln-scan.yaml

ci: vuln-scan, adjust to changes in trivy's json output

---

CHANGELOG.md
chartpress.yaml
images/hub/requirements.txt
jupyterhub/Chart.yaml

Release chart version 1.2.0, bump to JupyterHub 1.5

---

doc/source/kubernetes/amazon/step-zero-aws-eks.md
doc/source/kubernetes/amazon/step-zero-aws.md

I had to look up how to create a role in AWS. Adding a link here makes a bit more seamless for new users
EDIT by Erik: Closes #2515

DOC: instructions for role creation in AWS

---

doc/source/jupyterhub/customizing/user-environment.md

Porting this blog post into the docs:
https://words.yuvi.in/post/jupyterlab-settings-z2jh/

Document how to disable some labextensions with config

---

doc/source/kubernetes/amazon/step-zero-aws.md

I learned how to do this recently and wanted to upstream it here.

DOC: add extra AWS ssh info

---

docs/source/jupyterhub/customizing/user-storage.md

Restrict the topology of provisioned volumes to specific zones

Replace zone to allowedTopologies

---

.github/workflows/test-chart.yaml

Ping @manics who warned of potential issues about using this action in Gitter: https://gitter.im/jupyterhub/random?at=620e8445b8b08244823c75a7

ci: remove conditional tmate debugging session action

---

.github/workflows/support-bot.yml

https://github.com/jupyterhub/jupyterhub/blob/8d056170d7184db860c4a8bf4e0bded4d4cc7b92/.github/workflows/support-bot.yml with a few additions

Add support bot

---

jupyterhub/schema.yaml
jupyterhub/templates/proxy/autohttps/deployment.yaml
jupyterhub/values.yaml

Forgive me; the bot suggests a pull request template, but I can't find where it is.
This solves issue https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2671

Extras Init containers for traefik

---

docs/source/kubernetes/amazon/efs_storage.md

The comment implies that the problem was fixed a few versions ago, but unfortunately it wasn't.

docs: Remove a false promise regarding CHOWN_HOME

---

docs/source/jupyterhub/customizing/user-environment.md

docs: how to adjust profile_list dynamically based on user etc

---

jupyterhub/schema.yaml
jupyterhub/templates/NOTES.txt
jupyterhub/templates/hub/deployment.yaml
jupyterhub/values.yaml

This PR is motivated in #2718.
Closes #2718.

breaking: add hub.podSecurityContext, remove hub.fsGid

---

images/hub/requirements.in
images/hub/requirements.txt

This means that LTI13Authenticator won't be available yet still.

hub image: downgrade to ltiauthenticator 1.2.0

---

docs/source/changelog.md
docs/source/kubernetes/microsoft/step-zero-azure-autoscale.md
docs/source/kubernetes/redhat/step-zero-openshift.md
images/image-awaiter/README.md
images/singleuser-sample/README.md

This doesn't fill all links in the changelog, but almost all.

docs: fix most broken links in changelog

---

docs/source/administrator/upgrading/upgrade-1-to-2.md

Mainly https://github.com/jupyterhub/kubespawner/pull/545

Add breaking KubeSpawner changes to upgrade-1-to-2

---

images/hub/requirements.in
images/hub/requirements.txt
images/singleuser-sample/requirements.txt
jupyterhub/Chart.yaml

So we can do a coordinated beta cycle with Hub 3 and z2jh 2

JupyterHub 3.0.0b1

---

images/secret-sync/Dockerfile

Closes #2884 by rebulding that image as well.

secret sync image: use python 3.9

---

tools/compare-values-schema-content.py
tools/generate-json-schema.py
tools/templates/lint-and-validate.py
tools/validate-against-schema.py

I did some minor refactoring of scripts in the tools/ folder that I manually run sometimes.

ci: minor refactoring/updates of tools

---

.github/workflows/vuln-scan.yaml
.github/workflows/watch-dependencies.yaml

- Addresses https://github.com/jupyterhub/team-compass/issues/579 for this repo.

ci: fix deprecation of set-output in github workflows

---

docs/source/kubernetes/amazon/step-zero-aws.md

docs: AWS master node size needs to be larger than micro

---

docs/source/jupyterhub/customizing/user-environment.md

Note was blocked using wrong tags

note at line 554 did not render correctly

---

.github/workflows/test-docs.yaml
ci/summarise-linkcheck-output

It takes too long to read through the entire output to find out what needs fixing

Summarise linkcheck CI output

---

docs/source/jupyterhub/customizing/user-environment.md

`base-notebook` hasn't been the default for quite a while.

docs: user-env default image is not base-image

---

images/image-awaiter/Dockerfile

small revision of the dockerfile - removed the extra layer

Refactor of image-awaiter's dockerfile

---

docs/source/jupyterhub/installation.md

Remove double word cluster in installation.md

---

docs/source/changelog.md

A bug was reported in GenericOAuthenticator that has been fixed in 16.0.2 that this beta release includes.

Add changelog for 3.0.0-beta.3

---

docs/source/changelog.md

Update changelog for 3.0.0

---

docs/source/index.md

I think there are now multiple people contributing significantly to z2jh from 2i2c, and I'd love for this callout to be here!
I'd also love for other contributors to add their own institutions here :)

Add 2i2c as an institutional supporter

---

docs/source/changelog.md

Did a quick iteration to get a bugfix for oauthenticator out with https://github.com/jupyterhub/oauthenticator/pull/704

Add changelog for 3.2.1

---

jupyterhub/values.schema.yaml

Thank @ryanlovett for spotting this!

Fix documented example for proxy.chp.extraCommandLineFlags

---

ci/refreeze
images/hub/Dockerfile
images/singleuser-sample/Dockerfile

Bumping the base-image from debian bullseye (11) to bookworm (12)

Bump debian distribution for images

---

images/hub/requirements.in
images/hub/requirements.txt

fixes some bugs in the new safe slug scheme: https://github.com/jupyterhub/kubespawner/pull/856

kubespawner 7.0.0b2

---

images/hub/requirements.in
images/hub/requirements.txt
images/singleuser-sample/requirements.txt

- **Bump to kubespawner 7.0.0b3**
- **Refreeze dependencies**

Bump to kubespawner from 7.0.0b2 to 7.0.0b3

---

.github/workflows/test-chart.yaml

This is used for testing only.

ci: Bump postgresql chart

---

docs/source/changelog.md

There were a few things to release, so I figured we'd cut one.

Add changelog for 4.1.0

---

README.md
docs/source/administrator/upgrading/index.md
docs/source/conf.py
docs/source/index.md
jupyterhub/README.md
jupyterhub/templates/NOTES.txt

Making a start on https://github.com/jupyterhub/team-compass/issues/765

Replace gitter with zulip
